### ISSUE TITLE
server side sound issues and unhittable pokemons

### ISSUE THREAD

**Issue by quakeman00** [Pokecube-Development/Pokecube-Issues-and-Wiki#1002]
#BUG 1

pokemon alt forms like colored birds and deoxys forms dont make sounds on server side

#BUG 2

a few long pokemons like most snakes (tested on ekans and seviper) seems to be harder to hit or unable to hit at all, lapras is also unhittable in our server, pokemons who breed during fight and make an egg also become temporarly invulnerable.

pokecube-aio-1.18.2-3.17.7.a

**Comment by Thutmose** [comment]
next time make separate issues for each bug, as makes it easier for me to mark as finished, etc

I have the sounds part fixed at least

**Comment by Thutmose** [comment]
I cannot replicate bug 2 on my side, ekans/lapras seem to be working fine in my server-side testing

**Comment by quakeman00** [comment]
![ezgif-3-0b3b845581](https://user-images.githubusercontent.com/3716838/189519222-d29e92a6-aa50-4538-906f-fe951da4603c.gif)

another exemple of attacks not landing , this time on a golurk
