### ISSUE TITLE
Ash Issues

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#1003]
#### Issue Description:
- Several issues with ash

#### What happens:
- The solid ash block can't be placed midair
- The ash layer can't be placed past three layers
- Wet ash layers can't be placed after it changes it's state
- Ash dust gets stuck if it is raining and doesn't update afterwards
- Placing the ash layer underwater deletes the water source

#### What you expected to happen:
- Ash layers should stack to 16
- The solid Ash Block should be placeable midair
- Ash dust should still fall

#### Steps to reproduce:
1. Try to place the ash block midair
2. Try to stack ash layers past three
3. Try to stack ash layers underwater
4. Place an ash block under a block to fall when it rains
5. Ash dust will form in the rain but won't fall
6. Place ash in a single water block
...

- Waterloggable blocks usually implements `SimpleWaterloggedBlock`, similar to how `IFlowingBlock` is implemented
- The ash layer should check for water in the `getStateForPlacement` class, similar to the campfire block, which would fix the deleted water source

https://user-images.githubusercontent.com/12000593/189510459-b7c88161-27eb-4d76-8fc5-a16e7632fea4.mp4

____
#### Affected Version:

- Pokecube AIO: dev
- Minecraft: 1.18.2
- Forge: 40.1.73

**Comment by Thutmose** [comment]
the ash does implement SimpleWaterloggedBlock, via the `PartialDust` class down at the bottom
