### ISSUE TITLE
Trop kick crash the client and melee attacks dont reach when looking back

### ISSUE THREAD

**Issue by quakeman00** [Pokecube-Development/Pokecube-Issues-and-Wiki#1004]
BUG 1:

trop kick crash the client when used, crash report say something about particles but i cant confirm

BUG 2:
melee pokemon seems to be missing alot more and unable to reach thier target when facing the oposite direction of thier attacks, this problem seems more common on small and medium pokemons like aaron / sneasel / trapinch / absol while bigger pokemon like wailord and blaziken dont seem to suffer from it as much, giving a huge advantage to ranged pokemon.

these have only been tested on server side.

pokecube-aio-1.18.2-3.17.7.a
![ezgif-2-54f29fac8b](https://user-images.githubusercontent.com/3716838/189511858-027b0ce9-4ef0-4fa8-b9da-7883261841ce.gif)

**Comment by Thutmose** [comment]
please make separate issues for each one next time... the trop kick thing is already fixed for next update.

**Comment by Thutmose** [comment]
looks to me that when it jumps like that, it hasn't actually tried to attack, it is part of the combat motion instead.

In my testing, the melee attacks only fail about 5% of the time, however it does do more of that jumping than it tries to attack
