### ISSUE TITLE
Mod fail to load

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#1005]
#### Issue Description:
Perhaps it's a problem on my end, but the mod fail to load on a fresh installation. Other mods don't have this issue. It both happen with the recommended forge version, and the latest.
[crash-2022-09-11_15.50.29-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9542690/crash-2022-09-11_15.50.29-fml.txt)

#### What happens:
Mod fail to load, despite being a new installation.

#### What you expected to happen:
The mod load correctly.

#### Steps to reproduce:

1.Make a fresh install
2.Only place pokecube AIO in the mods folder
3.Mod fail to load

...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.8
- Minecraft: 1.18.2
- Forge: 40.1.0

**Comment by Thutmose** [comment]
you need to use a forge version between 40.1.72 and 40.1.79. Note that 40.1.80+ currently also crashes due to forge removing code it added in 40.1.72

**Comment by CorentG** [comment]
Ah, thanks you for the answer !
