### ISSUE TITLE
A few moves causes crashes

### ISSUE THREAD

**Issue by quakeman00** [Pokecube-Development/Pokecube-Issues-and-Wiki#1010]
using earthquake cause the client to crash but not the server

edit:
we found a magneton who also caused some crashes,.

pokecube-aio-1.18.2-3.17.8

[crash-2022-09-11_19.22.37-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9544171/crash-2022-09-11_19.22.37-client.txt)

**Comment by Thutmose** [comment]
this appears to be the same thing as #1009
