### ISSUE TITLE
Crashes when using Forge 40.1.80

### ISSUE THREAD

**Issue by N0VVAH** [Pokecube-Development/Pokecube-Issues-and-Wiki#1012]
#### Issue Description:
The Mod causes the game to crash on startup. I created a fresh pack using minecraft 1.18.2 and current latest forge 40.1.80 and added just Pokecube AIO and I get the following error every time. https://imgur.com/a/sL4bTu1

#### What happens:
Game starts to launch then crashes

#### What you expected to happen:
The game to launch

#### Steps to reproduce:

1. Install Pokecube

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.8
- Minecraft: 1.18.2
- Forge: 40.1.80

[crash-2022-09-12_12.33.33-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9547572/crash-2022-09-12_12.33.33-fml.txt)

**Comment by Thutmose** [comment]
downgrade forge, forge 40.1.80 broke compatiblity again, so you need to use a version from 40.1.73 - 40.1.79

**Comment by AzrouStone** [comment]
Same issue for the newest update: pokecube-aio-1.18.2-3.17.12

**Comment by Thutmose** [comment]
yep, use forge 40.1.73 - 40.1.79

Edit: Some reference for why this is not "fixed"

The code forge removed in 40.1.80 makes the mod development take 2-10 minutes longer per world load, from a time of less than 30s, so for a 4-20x increase. This makes it very annoying to try to do development for that version, so until forge actually puts out an update that changes anything else, I don't plan to update the 1.18.2 supported version. If this does end up being the final version for forge for 1.18.2, when 1.20 is released,  I will do a final update then to bump the forge version, as I will no longer need to run development environment for this version.

**Comment by Thutmose** [comment]
This should be fixed now with 3.19.+
