### ISSUE TITLE
Bug when you put TRUE the preload models in Pokecube AIO

### ISSUE THREAD

**Issue by Javi185** [Pokecube-Development/Pokecube-Issues-and-Wiki#103]
#### Issue Description:
When you put in pokecube_ml the option preload models in True, the game don't open (similar to crash and I only use these mod)

#### What happens:

The game don't open

#### What you expected to happen:

The option (preload=true) in Pokecube AIO is don't working

#### Steps to reproduce:

1.In options (pokecube_ml) put the preload in true
2. Open the game
3.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

-Pokecube AIO
- Minecraft: 1.12.2
- Forge: With every forge

Sorry for my bad English

**Comment by Javi185** [comment]
The affected versions too:

-Pokecube-mobs-4.16.0
-Pokecube-core-4.44.0
-Pokecube-revival-4.16.0

I don't know if old versions are affected too (this versions no:)

No bug:
-Pokecube-mobs-4.14.0
-Pokecube-core-6.42.1
-Pokecube-revival-6.16.19

**Comment by Thutmose** [comment]
This will be fixed in next update for AIO :D
