### ISSUE TITLE
Regidrago Temple does not spawn

### ISSUE THREAD

**Issue by AxolotlKing** [Pokecube-Development/Pokecube-Issues-and-Wiki#1046]
#### Issue Description:
Regidrago Temple does not spawn, did a search with commands for the structure and it was not found

#### What happens:
Regidrago Temple doesn't spawn

#### What you expected to happen:
The temple does spawn

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.11
- Minecraft: 1.18.2
- Forge: 40.1.76

**Comment by Thutmose** [comment]
where did you do this locate command?
