### ISSUE TITLE
Major Incompatibility with ProjectE

### ISSUE THREAD

**Issue by WindFox** [Pokecube-Development/Pokecube-Issues-and-Wiki#1048]
#### Issue Description:
When a player dies, all knowledge and EMC in a table is deleted and the contents of all that player's alchemical bags are voided.

#### What happens:
While this mod is installed with ProjectE, whenever a player dies, a lot of their personal data for ProjectE is erased. I know this info is stored in the player's capabilities;  is this mod just wiping everything in there?

#### What you expected to happen:
Keeping all my ProjectE knowledge when I die.

#### Steps to reproduce:

1. Make a simple modpack with just Pokecube and ProjectE (add JEI if you find that easier)
2. Create a test world with cheats on (flat is best) 
3. Place a Transmutation Table.
4. Put any number of items in the table to learn them and get some EMC.
5. Kill yourself (in game only, please)
6. Check the table and see it all disappear (It should not.)
7. Cry

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.13
- Minecraft: 1.18.2
- Forge: 40.1.79
- ProjectE: 1.0.1

**Comment by Thutmose** [comment]
hmm, it shouldn't be removing capabilities when the player dies...

I will see if I can find the cause.
