### ISSUE TITLE
Incompatibility with Blue Skies

### ISSUE THREAD

**Issue by WindFox** [Pokecube-Development/Pokecube-Issues-and-Wiki#1049]
#### Issue Description:
When this mod is installed with Blue Skies, buckets no longer work with the world. (Tanks are still OK)

#### What happens:
With both mods installed, you cannot use buckets to pick up liquid source blocks (water/lava) or place liquid source blocks.

#### What you expected to happen:
Buckets to work properly.

#### Steps to reproduce:

1. Make a simple modpack with Pokecube, Blue Skies, and it's dependance, Structure Gel (add JEI if you find that easier)
2. Create a test world with cheats on (flat is best)
3. Get a bucket of water
4. Try to empty the bucket into the world
5. Fail
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.13
- Minecraft: 1.18.2
- Forge: 40.1.79
- Structure Gel: 2.4.6
- Blue Skies: 1.3.12

**Comment by Thutmose** [comment]
can you send the startup logs from when you tried this?

**Comment by WindFox** [comment]
[Blue_Skies_Only.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9719571/Blue_Skies_Only.zip)
[Blue_Skies_and_Pokecube.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9719572/Blue_Skies_and_Pokecube.zip)

**Comment by Thutmose** [comment]
hmm, not sure, I can check if this is somehow related to #1048 though, which I have confirmed fixed for next update

**Comment by Thutmose** [comment]
was same cause as #1048, is now fixed for next update.
