### ISSUE TITLE
Auto-add pokemobs to the team the player is in

### ISSUE THREAD

**Issue by TupperBot99** [Pokecube-Development/Pokecube-Issues-and-Wiki#1056]
**Is your feature request related to a problem? Please describe.**
Right now caught pokemobs are not on the same team as the player, which can cause some issues with AI, especially when using vanilla-pokemobs and non-vanilla-pokemobs, due to normally aggressive mobs attacking your own pets and other pokemobs, as well as attacking you when there is no target.

**Describe the solution you'd like**
I believe caught pokemobs (and caught non-pokemobs) should be automatically added to the team the player/trainer is on

**Describe alternatives you've considered**
Currently I have to manually add caught mobs to a team that I am on by typing in a command, which can feel cheaty on a survival world.

**Comment by Thutmose** [comment]
the change mentioned here should now be in 3.18.1, github release is out, curseforge one is pending approval
