### ISSUE TITLE
1.19.2 Strange, Disobedient, Inventory Stealing Krabby and Right Click Issue.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#1057]
#### Issue Description:

- I caught a Krabby and he steals my stuff. Does not listen to attack orders except the move harden. Does not wander despite being told to wander.

#### What happens:

- See issue description.

#### What you expected to happen:

- The pokemob listens
- My stuff doesn't get stolen
- profit.

#### Steps to reproduce:

1. Dunno it was random.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.19.2-3.18.1
- Minecraft: 1.19.2
- Forge: 43.1.34

Server

[debug.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759445/debug.log)
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759446/latest.log)
[pokecube.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759448/pokecube.log)
[thutcore.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759449/thutcore.log)
[thutessentials.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759450/thutessentials.log)

Client

[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759451/latest.log)
[pokecube.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759452/pokecube.log)
[thutcore.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759453/thutcore.log)
[thutessentials.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9759454/thutessentials.log)

Images
![9uNMhf0 1](https://user-images.githubusercontent.com/10351221/195189636-1d0c4dad-9564-462f-9a71-c7f2617dc746.gif)

**Comment by P3rf3ctXZer0** [comment]
This is not fixed. 

Maybe this helps ... 
![2022-10-11_21 07 03](https://user-images.githubusercontent.com/10351221/195232423-5a70799b-596d-4086-b2ae-1d81e8748b41.png)

**Comment by Thutmose** [comment]
what was fixed was the part of this report that was replicated, and that you made the gif for.

Ideally you should make different issues for each thing that is wrong, makes it easier to label things as fixed.

**Comment by P3rf3ctXZer0** [comment]
Well regardless I am closing this because of the fact I lost that world due to major minecolonies issues. That made me lose that world.
