### ISSUE TITLE
When u die starting a new world, all items disappear especially ur Pokemons (PokeWatch, PokeBag...)

### ISSUE THREAD

**Issue by Raeaper** [Pokecube-Development/Pokecube-Issues-and-Wiki#1068]
#### What happens: 

-When u're starting the Game/World n receive ur first pokemon n ur equipaments if you die or type the command /kill when respawning, everything disappears (PokeBag, PokeWatch n ur first Pokemon...) except the 10 Pokécubes. .-.

#### What you expected to happen:

-That items do not disappear n be able to recover them when I return to the place of my death, especially my Pokemons...

#### Steps to reproduce:

1. Start new Game/World.
2. Talk to the professor to get ur first Pokemon n items.
3. Die anywhere or use /kill.
4.  Well done, everything disappeared until ur initial pokemon. :V
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.18.2 - 3.19.0
- Minecraft: 1.19.2
- Forge: 43.1.34

**Comment by Thutmose** [comment]
did you look in the PC?

**Comment by Thutmose** [comment]
"important" items get sent to PC on death. This includes the ones you mention as having "disappeared", see: https://pokecube.readthedocs.io/en/latest/getting_started/index.html#faq-and-common-issues

**Comment by Raeaper** [comment]
I apologize for my ignorance n confusion. I want to thank u for taking the time to answer me n above all for making this majestic n wonderful Mod for the beloved Minecraft.
Thank you very much n have a great day.
