### ISSUE TITLE
Pokemon change sex in inventory and show as opposite sex, fixes sending out and recalling

### ISSUE THREAD

**Issue by Praymettin** [Pokecube-Development/Pokecube-Issues-and-Wiki#1072]
#### Issue Description:
At the official pokecube server, sometimes while I am checking pokemobs in my inventory with shift, they show as opposite sexes, it is fixed by sending out and recalling.

#### What happens:
While checking pokemon in inventory with shift key, sex symbol sometimes show opposite sex, happens seemingly randomly. May be related to recent player death and recovering from PC. After sending out, pokemon shows the correct symbol near name and when recalled, the pokecube check with shift is also fixed.

#### What you expected to happen:
Show the correct sex regardless of inventory or released state.

#### Steps to reproduce:

1. Open inventory and check pokecubes with shift.
2. If no change, then walk a little bit and try again.
3. After a few tries, most of the pokemobs inside the inventory shows as opposite sex than they should be.
4.  Send the affected ones out to fix the sex symbol displayed.
5. When recalled, the symbol inside inventory will also be fixed.
6. I think it seemed to also affect the pokemob outside of pokecube but, couldn't repeat that.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.19.2-3.19.0.c
- Minecraft: 1.9.2
- Forge: 43.1.47
- Other mods in the official modpack, released along with 1.19.2-3.19.0.c
![pawniardmixup](https://user-images.githubus
![sentoutpawniard](https://user-images.githubusercontent.com/81359356/199587225-46755caa-b077-4d96-a8c7-ca698c4a6633.png)
ercontent.com/81359356/199587180-e029c921-eb46-44c6-a3b2-a87a60d55183.png)
![pawniardinvfixed](https://user-images.githubusercontent.com/81359356/199587317-a482cf18-eebb-43e4-b5cf-7daf9feee2eb.png)

**Comment by Praymettin** [comment]
Sorry, the secon screenshot link seem to have cut the first in half. Here is the first link : https://user-images.githubusercontent.com/81359356/199587180-e029c921-eb46-44c6-a3b2-a87a60d55183.png

**Comment by Thutmose** [comment]
this should be fixed now, let me know if it re-occurs, I can reopen the issue and look further into it
