### ISSUE TITLE
Errored spawns listed in watch

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#1073]
#### Issue Description:
on the pokemob info spawn sheet many pokemon say they can spawn in certain areas where they cant

#### What happens:
a list is given of areas where a pokemob can spawn but does not show percentages and its all the same list

#### What you expected to happen:
to give correct information about spawns of pokemobs

#### Steps to reproduce:

1. open the pokewatch and go to any pokemobs info spawn sheet 
2. scroll until you find a pokemon that cant spawn normally and have a list of places it can spawn
3.
...

____

- Pokecube AIO: 3.19.0
- Minecraft: 1.19.2
- Forge: 43.1.47

![2022-11-02_20 28 12](https://user-images.githubusercontent.com/46906554/199626896-8a354f4e-145d-4532-a1fd-a30dc9890f0c.png)
![2022-11-02_20 23 38](https://user-images.githubusercontent.com/46906554/199626943-7250c3ad-7578-4cc3-9c9c-f08af317b5cc.png)
![2022-11-02_20 23 41](https://user-images.githubusercontent.com/46906554/199626946-ca1c1c3d-139a-440c-aead-2489f36bca91.png)
![2022-11-02_20 23 45](https://user-images.githubusercontent.com/46906554/199626949-1ee8c5ad-c2c6-4e9c-9410-a1ae62dec3e5.png)
![2022-11-02_20 23 48](https://user-images.githubusercontent.com/46906554/199626952-74fa7857-aeae-443b-8376-81712e50153b.png)
![2022-11-02_20 24 47](https://user-images.githubusercontent.com/46906554/199626954-14d39655-8161-4bc2-9038-402ddecfa53e.png)
![2022-11-02_20 28 12](https://user-images.githubusercontent.com/46906554/199626956-8bcd515b-26d4-4733-a5b4-b9a040addf21.png)

**Comment by Thutmose** [comment]
those all appear to be ultraspace spawns, ultraspace has a bunch of strange things set to spawn in it

**Comment by monkeycrazie** [comment]
it seems shaymin is the only pokemon to list every biome as a spawnable one

**Comment by Thutmose** [comment]
hmm, it seems something is wrong with the thing that is supposed to filter out biomes for it, that spawn is listed as "flowers" areas, the same error shows up for one of the spawn entries deerling, oricorio, etc
