### ISSUE TITLE
Removed mooshroom spawn n bug with the generation of the biome of mushrooms fields

### ISSUE THREAD

**Issue by Raeaper** [Pokecube-Development/Pokecube-Issues-and-Wiki#1079]
#### Issue Description:

Removed natural spawn from Mooshrooms n bugged terrain generation with Mushroom fields biome.

#### What happens:

Unfortunately this wonderful mod removes the natural Spawn of the Mooshrooms making it impossible to find one on a mushroom field island and however it also bugs the terrain generation since in a place that usually appears a mushroom field island makes it not exist again in the world. Even in the F3 it appears in the name of the biome.

-Without the Pokécube mod n only the NaturesCompass mod:
![2022-11-04_13 46 01](https://user-images.githubusercontent.com/116993019/200055624-8ab1606f-1eac-4464-989e-e7ecdeec3f5e.png)

-New world but same seed, only with the Pokécube mod n the NaturesCompass mod but the Island no longer exists:
![2022-11-04_13 50 36](https://user-images.githubusercontent.com/116993019/200055755-37465ee3-7f43-466b-94a2-70abf760c06d.png)

-Here the test where it says that the Biome is the Mushroom fields but it does not exist
![2022-11-04_13 51 40](https://user-images.githubusercontent.com/116993019/200055814-fa6a2164-cd27-40da-aaa4-b48a09f9a5d2.png)

-Another Island in the same seed but unfortunately no Mooshroom spawns only Pokemons :c
![2022-11-04_13 53 16](https://user-images.githubusercontent.com/116993019/200057601-4a3d1ea9-2e4d-4cc5-8f1f-4b96c602c7d7.png)

#### What you expected to happen:

To be able to find the Mushroom field Island if it exists in the world n to be able to find the Mooshrooms in it.

Suggestion: Can Mooshrooms Spawn be made to have priority like Pokemons? or to be overwritten like pokemons?

#### Steps to reproduce:

1. Use the NaturesCompass to find the biome in question (Mushroom fields) 
2. Teleports to the Biome
3. 2 things can happen here:
      -1: find the biome
      -2: find a spot in the sea where the biome should be.
4. Surprise surprise not finding any Mooshroom only pokemons :c
...
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- NaturesCompass: 1.9.7 [https://www.curseforge.com/minecraft/mc-mods/natures-compass]
- Pokecube AIO: 3.19.3
- Minecraft: 1.19.2
- Forge: 43.1.34

**Comment by Thutmose** [comment]
there is a config option to prevent the disabling of vanilla animals: `deactivateAnimals` in `pokecube-common.toml`

As for the missing mushroom island, I am not sure what is going on there, the mod shouldn't be affecting that

**Comment by Raeaper** [comment]
oh I see bro, I'll check it out.
 Thanks for quick answer

**Comment by Raeaper** [comment]
oh I see bro, I'll check it out.
Thanks for quick answer.

and the missing island only happens to me with your mod :c

**Comment by Raeaper** [comment]
No bro, I already checked the configuration options but the mooshrooms still don't appear naturally in the Mushroom fields.
:c

**Comment by Thutmose** [comment]
are you seeing other vanilla animal spawns? ie chickens/pigs/sheep/etc?

**Comment by Raeaper** [comment]
no bro

**Comment by Raeaper** [comment]
they only spawn animals/mobs from other mods like Aquaculture 2 / Vampirism / werewolves but I haven't seen any vanilla from there

**Comment by Thutmose** [comment]
I will look into that config option, to se if something is wrong with it

**Comment by Raeaper** [comment]
okay bro ty

**Comment by Thutmose** [comment]
hmm, I get this when I set that config option then go to a mushroom biome: 
![image](https://user-images.githubusercontent.com/2363472/200144016-364145b7-6773-4e88-9fee-5ff80b971c62.png)

**Comment by Raeaper** [comment]
which configuration option bro?
deactivateAnimals to False? 
or disableVanillaAnimals to True?

**Comment by Thutmose** [comment]
`deactivateAnimals` to false.

if you do `disableVanillaMonsters` to true, it prevents them existing, as specified in the comment on that config option

**Comment by Raeaper** [comment]
yes, so I modified that configuration n for some strange reason I can't get them.

did u create a new world with the mod or a vanilla world already created then u put the mod in it?

**Comment by Thutmose** [comment]
this was a world made with the mod, but the config option set to prevent spawns, then I changed the config option, and located the biome

**Comment by Raeaper** [comment]
Let me show u bro: 
https://drive.google.com/file/d/1W9VbF06Y5AW5phKq5-nushH2A0zc-kzA/view?usp=share_link

**Comment by Thutmose** [comment]
ya, the odd thing is that when I do that, I get them spawn just fine:

Create new world:
![image](https://user-images.githubusercontent.com/2363472/200149399-c312fea5-e6ea-4ff7-b147-820851f1ca05.png)

Locate biome for mushrooms:
![image](https://user-images.githubusercontent.com/2363472/200149412-41d73f1b-8116-4b76-8e1e-142cfdbbb439.png)

TP to that biome:
![image](https://user-images.githubusercontent.com/2363472/200149418-4b4ce18e-803c-46e0-96a4-2aa1f69e3b08.png)

Config check:
![image](https://user-images.githubusercontent.com/2363472/200149437-d7245aab-151e-4a3b-a7b6-e70a0aeecf9a.png)

This was done using this modpack: https://www.curseforge.com/minecraft/modpacks/pokecube-pack and then changing the config

**Comment by Thutmose** [comment]
so it means there is probably something else involved, are you sure you are on version 3.19.3 and not an older one? I think 3.19.2 was not loading in the config options properly

**Comment by Raeaper** [comment]
That's right bro, I'm sure, in the video you can see that it's 3.19.3

**Comment by Raeaper** [comment]
3.19.3
![image](https://user-images.githubusercontent.com/116993019/200149567-b464e9ce-b12d-47cc-a95f-f9251cff0ace.png)

**Comment by Thutmose** [comment]
hmm good point, maybe check with 3.19.4, see if it still occurs there? also maybe try without natures compass and configured? incase those are somehow interferring? if so, I can look into possible mod compatiblity related problems.

**Comment by Raeaper** [comment]
okay, sure bro, let me check

**Comment by WenXin20** [comment]
Pokecube also doesn't remove any vanilla biomes, you just got unlucky and found a really small mushroom biome with no land, which is possible.

**Comment by Raeaper** [comment]
> Pokecube also doesn't remove any vanilla biomes, you just got unlucky and found a really small mushroom biome with no land, which is possible.

really?
It is the first time that it happens to me :c

**Comment by Raeaper** [comment]
what is the command to check the configuration?

**Comment by Thutmose** [comment]
it is `/pokesettings` for that particular option

**Comment by Raeaper** [comment]
okay ty

**Comment by Raeaper** [comment]
3.19.4 it's Fixed :D
![2022-11-05_21 04 13](https://user-images.githubusercontent.com/116993019/200150639-d46984ae-fedc-4da5-9e0c-1304fe2d44f4.png)

3.19.3 or less is the problem

**Comment by Raeaper** [comment]
ty very much bro
