### ISSUE TITLE
Pokedex crash

### ISSUE THREAD

**Issue by schkrisz1** [Pokecube-Development/Pokecube-Issues-and-Wiki#1082]
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by Thutmose** [comment]
please include the crash report

**Comment by Thutmose** [comment]
or at least include mod versions, forge versions, minecraft versions, etc.

It should have given you a template to fill out when you clicked new issue...

**Comment by Thutmose** [comment]
closed due to suspicion that OP is a bot, as posted identical message 4 times, 3 in the duplicated thread, 1 here.
