### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by schkrisz1** [Pokecube-Development/Pokecube-Issues-and-Wiki#1083]
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by schkrisz1** [comment]
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by Thutmose** [comment]
duplicate of #1082

**Comment by schkrisz1** [comment]
Dear developer!
The mod is very good, BUT when I use the pokedex, exactly when I want to scroll through the dex, the game crashes and closes itself.
Please fix this bug in future updates.
Thanks

**Comment by Thutmose** [comment]
I will close the other issue as well, as it appears that you are a bot.

**Comment by schkrisz1** [comment]
I'm not a bot, BUT the problem STILL EXISTS despite closing this thread. But as I can see, he is not even willing to pay attention to solving the problem.

Thanks for the BIG nothing!

**Comment by Thutmose** [comment]
oh, then why did you not provide the information requested in #1082?

**Comment by Thutmose** [comment]
when opening the issue, it gives a template to fill out, please fill that out in a new issue.

**Comment by schkrisz1** [comment]
I wrote a new #1084.
