### ISSUE TITLE
1.19.2 3.20.0 Random Crash. 

### ISSUE THREAD

**Issue by Hexblood** [Pokecube-Development/Pokecube-Issues-and-Wiki#1085]
#### Issue Description:
Game Crashed while walking around. I am no expert at reading the crash reports but I think it has to do with Thutcore and Wormhole renderer???

#### What happens:

No special actions. I was just walking around and game suddenly went to "Saving World."

#### Steps to reproduce:
All I was doing was walking around. No special action occurred

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.20.0
- Minecraft: 1.19.2
- Forge: 43.1.47

Crash Report: https://paste.ee/p/WDNdo

**Comment by Thutmose** [comment]
this particular one should be fixed in 3.20.1, which is uploaded (pending approval on curseforge) if another similar crash occurs, please provide the new crash report :D
