### ISSUE TITLE
Crashing when creating a world.

### ISSUE THREAD

**Issue by Frez7y** [Pokecube-Development/Pokecube-Issues-and-Wiki#1086]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### What happens: 
The game crashes before even loading the map on 1.19.2

#### What you expected to happen: 
Load the world.

#### Steps to reproduce:

1. Start the game and create a world.
2. ?
3. ?
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.19.3
- Minecraft: 1.19.2
- Forge: 43.1.1

**Comment by Thutmose** [comment]
please include crash report next time, but this case it is forge is wrong version, so closing
