### ISSUE TITLE
Pokeplayer: Move-selection refuses to work on re-log

### ISSUE THREAD

**Issue by TeamEeveeG** [Pokecube-Development/Pokecube-Issues-and-Wiki#109]
#### Issue Description:
When using Pokeplayer, re-logging will cause the move you were on when you logged off to be selected no matter what keys you press. Stepping on the Transformer twice (effectively reloading the pokemob you logged off as) allows you to select a move again.

#### What happens:
Losing the ability to change the selected move upon re-log

#### What you expected to happen:
To still be able to change the selected move

#### Steps to reproduce:
1. Use the Pokeplayer Transformer to become a Pokemob.
2. Re-log.
3. When your world loads, the selector in the GUI will be stuck on that move until you walk across the Transformer two more times.

____
#### Affected Versions
- Pokecube AIO: 1.15.12
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Pokecube Unit: 9.6 (Resource Pack)

**Comment by TeamEeveeG** [comment]
Suggestion from a Discord Conversation: "Maybe it could force a return to human form upon log out, and then return you to pokemon form when you log in instead of it's current behavior."

**Comment by Thutmose** [comment]
closing 1.12.2 issues, as that version isn't supported, hopefully someone will offer to update/re-write pokeplayer for 1.15.2+...
