### ISSUE TITLE
1.19.2   3.20.2   Eat Rock Crash

### ISSUE THREAD

**Issue by Hexblood** [Pokecube-Development/Pokecube-Issues-and-Wiki#1091]
#### Issue Description:

Random Crash. Report seams to indicate the Eat Rock action is at fault

#### What happens:

Random Crash while Mining. I was down around Y:58 so surrounding rock was mostly Deepslate. 

Ragnarolla, Geodude, and Rolycolly Pokemons were noticed to be around. Maybe 1-2 others I have forgottem

#### What you expected to happen:

Not to crash

#### Steps to reproduce:

1.Play down underground and wait for action from surrounding Pokemon I would figure.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.20.2
- Minecraft: 1.19.2
- Forge: 43.1.47
- Crash Report: https://paste.ee/p/bQop6

**Comment by Thutmose** [comment]
one of your mods is making the blocks return an un-editable list of drops, I can have this fixed for 3.20.4 though

**Comment by Thutmose** [comment]
this should be fixed now
