### ISSUE TITLE
3.20.3 Crash While Launching

### ISSUE THREAD

**Issue by Hexblood** [Pokecube-Development/Pokecube-Issues-and-Wiki#1092]
#### Issue Description:
Crash during launch. In-game message points to Pokecube Revival

#### What happens:
Crash on Launch

#### Steps to reproduce:

1. Install 3.20.3

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.20.3
- Minecraft: 1.19.2
- Forge: 43.1.52
- Crash Log: https://paste.ee/p/I3BGj

**Comment by Hexblood** [comment]
I saw that there was also an Update to the Compat mod and took a closer look at the Crash Report and saw that mentioned a few times. I am guessing that was the issue.

**Comment by Thutmose** [comment]
yep, the compat update should fix this
