### ISSUE TITLE
minior is immortal

### ISSUE THREAD

**Issue by Drewskalegend** [Pokecube-Development/Pokecube-Issues-and-Wiki#11]
#### Issue Description:
Minior's ability is bugged - everytime it's hp drops to 50 or so the pokemob straight up revives instead of changing form.

#### What happens:
Minior revives when its hp drops to a certain point

#### What you expected to happen:

For it to die

#### Steps to reproduce:

1.Find/spawn a minior
2.attempt kill it
3.notice it cant die
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

Pokecube-aio-1.12.2-1.7.1

**Comment by Thutmose** [comment]
This bug is fixed for next update
