### ISSUE TITLE
Crash while creating boat model

### ISSUE THREAD

**Issue by LemoneJamTart** [Pokecube-Development/Pokecube-Issues-and-Wiki#1108]
Crash when booting up the game. I do have a lot of mods but this was the one explicitly mentioned in the crash report. latest.log and the crash report attached.
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/10533491/latest.log)
[crash-2023-01-30_01.29.10-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/10533492/crash-2023-01-30_01.29.10-client.txt)

**Comment by WenXin20** [comment]
On line `4405` of the latest.log, you can see that the crash is actually being caused by BYG. You will need to delete the BYG config folder to fix it. 
`java.lang.IllegalArgumentException: Jankson file reading for "D:\Curse\Minecraft\Instances\All the Mods 8 - ATM8\config\byg\trades.json5`

**Comment by LemoneJamTart** [comment]
Thank you very much!
