### ISSUE TITLE
Can we monetize youtube videos showcasing the pokecube mod or is it gonna be copyright striked by nintendo?

### ISSUE THREAD

**Issue by BartGarceau** [Pokecube-Development/Pokecube-Issues-and-Wiki#1111]
Because i'm gonna add it to my modpack only if we can

**Comment by Thutmose** [comment]
No idea, that doesn't have anything to do with our mod itself, you would need to ask someone who deals with legal things related to Nintendo.

Can other "pokemon related" minecraft mods have monetized videos? if so, this one probably follows the same rules.
