### ISSUE TITLE
Pokecube and Treasure2 are incompatible and can't create or load a world

### ISSUE THREAD

**Issue by RunicLover** [Pokecube-Development/Pokecube-Issues-and-Wiki#1129]
Issue Description:
Pokecube and [Treasure2 ](https://www.curseforge.com/minecraft/mc-mods/treasure2) are seemingly incompatible.

What happens:
The game will load up fine, but when you attempt to create a world you will receive the "Errors in currently selected datapacks prevented the world from loading" error.

What you expected to happen:
For the world to load up without an issue.

Steps to reproduce:

1. Start Minecraft with Pokecube and Treasure2
2. Create a new world.
3. Get error message.
...

____
Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.18.2-3.23.0
- Minecraft: 1.18.2
- Forge: 40.2.9

**Comment by RunicLover** [comment]
Closing this as it seems to be a universal problem with Treasure2 itself, as it's incompatible with numerous mods in my pack.

**Comment by StardustPassingBy** [comment]
Had this same issue. Was able to get into the world creation screen after disabling Treasure2. Oddly enough it isn't incompatible with anything else in my 550+ mods.

**Comment by Moses24713** [comment]
Same Issue
