### ISSUE TITLE
Pokemon cannot damage entities that may be related to the player (tamed lycanite, tf2 mercenaries)

### ISSUE THREAD

**Issue by Hemeter** [Pokecube-Development/Pokecube-Issues-and-Wiki#1137]
#### Issue Description:
Pokecube mods, or pokemon, cannot harm entities that may be related to the player.
- It cannot damage tamed lycanite mobs
- it cannot damage rafradek tf2 stuff mercenaries, save for burning them
- pokemobs damage owner is set to true
- pokemobs harm npcs is set to true
- npcs are trainers is set to false

#### What happens:
Pokemon, when ordered to target tamed lycanite mobs or tf2 mercenaries, even if not recruited (tamed), are unable to damage said entities with damage moves, ranged or melee. however, they can be damaged by tamed lycanite mobs and tf2 mercs

#### What you expected to happen:
for tamed lycanite mobs and tf2 mercenaries to be harmed by pokemon ordered to attack by player

#### Steps to reproduce:
for lycanite mobs:
1. give appropriate category treat to tameable entity, and tame
2. ask pokemon to target tamed mob
3. pokemon cannot damage tamed mob. can be damaged pre-tamed by pokemon, and can damage similar species as long as not tamed
for reloaded rafradek tf2 stuff mod:
4. target a tf2 mercenary, regardless of their team, and regardless of team player is in. bosses can be damaged however
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.18.2
- Lycanites Mobs: 2.0.8.9
- Minecraft: 1.12.2
- TF2 Stuff Reloaded: 1.7.2a
- Forge: 14.23.5.2680

**Comment by Hemeter** [comment]
tested with only lycanites and pokecube. issue persisted. tested it with 1.16.5 too; cannot damage mobs owned by the player (summons and tames).

**Comment by Thutmose** [comment]
Hmm, I can look into this, starting with the tamed mobs related issue

**Comment by Thutmose** [comment]
I tested attacking tamed/tameable mobs, the following are working as intended presently:

Wild pokemobs can damage tamed mobs fine.
You presently cannot order your pokemob to attack another one of your tamed mobs.

I can look into configs that would allow enabling you to attack your own mobs, that was disabled due to excessive friendly fire events when players had difficulty managing their pokemobs

**Comment by Thutmose** [comment]
Testing the NPCs part, and that is definitely a bug rather than a feature.

**Comment by Thutmose** [comment]
The npcs were being stopped by the `aggroBlacklist` config in pokecube core's config. Try setting that to a blank array, and see if it helps?

**Comment by Hemeter** [comment]
i didnt find a file named pokecube core on config. Are you talking about pokecube.cfg? There is an aggroBlacklist on pokecube-common.toml on 1.16.5, but I didnt find an aggroBlacklist in the config pokecube folder on 1.12.2

**Comment by Thutmose** [comment]
hmm, for those older versions, it might be using `guardBlacklistClass` instead? I haven't dealt with the 1.12.2 codebase for 5 years or so, so harder for me to try to look up where things are used.

**Comment by Hemeter** [comment]
solved! guardBlacklistClass indeed prevents aggro and damage. They are classified under the "merchant npc" tag. Removing it allows pokemon to attack tf2 mercenaries
