### ISSUE TITLE
(1.14) Calling a move crashes Minecraft

### ISSUE THREAD

**Issue by TeamEeveeG** [Pokecube-Development/Pokecube-Issues-and-Wiki#114]
#### Issue Description:
Having a Pokemob use a move crashes 1.14

#### What happens:
The game crashes with the game claiming the following:
The game crashed whilst ticking entity
Error: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:sweepAttack

#### What you expected to happen:
The move (Tackle in this case) to be used.

#### Steps to reproduce:

1. Send a Pokemob that has a damage-dealing physical move (I don't know if Special moves are also affected)
2. select that move and call your Pokemob to attack a target entity
3. Minecraft should crash at this point.

____
#### Affected Versions
See crash report 125-133

____
#### Crash report
[crash-2019-10-12_10.24.40-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/3720853/crash-2019-10-12_10.24.40-client.txt)

____
#### Random extra suggestion
A "1.14" tag to show that it's an issue with the experimental version of the mod.

**Comment by Thutmose** [comment]
wait until it is not in alpha.
