### ISSUE TITLE
Pokecube Button Reposition Config Option

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#119]
**Is your feature request related to a problem? Please describe.**
- Currently, the mod Curios API also places a button in almost the exact same spot, which makes it difficult to click on either button in Minecraft v1.14.4

**Describe the solution you'd like**
- A config option to move the Pokecube Button to another corner of the player preview box.

**Describe alternatives you've considered**
None that I could think of.

**Additional context**
![2019-11-11_19 45 36](https://user-images.githubusercontent.com/12000593/68721048-c81f5d80-0576-11ea-8afb-14abea755771.png)

**Comment by Thutmose** [comment]
the option will be under config/thut_wearables/
