### ISSUE TITLE
1.19.2 Mining ores is no longer possible

### ISSUE THREAD

**Issue by Sephiroth91** [Pokecube-Development/Pokecube-Issues-and-Wiki#1198]
I updated the mod from version pokecube-aio-1.19.2-3.24.0.h to pokecube-aio-1.19.2-3.24.0.i. After the update I was no longer able to mine ores with an iron pickaxe that require an iron pickaxe. For example, I can no longer mine diamond ores with an iron pickaxe. I can no longer mine other ores from mods like zinc that require an iron pickaxe.
To test that it is not related to another mod, I removed all mods from the modpack except for Pokecube and TheOneProbe and the result remains the same - it is not possible to mine the ores.

- pokecube-aio-1.19.2-3.24.0.i
- Minecraft: 1.19.2
- Forge: 43.3.0

![2024-02-14_23 00 41](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/8442016/779bf20f-eb27-4181-8cad-c5e580c4b903)

[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/14289164/latest.log)

**Comment by Thutmose** [comment]
Can you include the debug.log if present? nothing seems to appear in that latest.log related to breaking of blocks

**Comment by Thutmose** [comment]
it seems to work in my dev environment at least:

![image](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/assets/2363472/2cab6e62-0c5f-4607-b48c-cb0f587ba759)

this used supposedly identical code to what is in pokecube-aio-1.19.2-3.24.0.i

**Comment by Sephiroth91** [comment]
It also works for me with a diamond pickaxe but it doesn't work with an iron pickaxe even though it also has to be able to mine diamond
[debug.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/14289523/debug.log)
