### ISSUE TITLE
Sneasel & Absol Pokemob Models are Broken

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#120]
#### Issue Description:
The Sneasel & Absol pokemob models are broken. 

#### What happens:
These I found spawned naturally, so I don't know if other models are broken. Others that had spawned in looked normal.

#### What you expected to happen:
Models shouldn't be broken.

#### Steps to reproduce:

1. Find a Sneasel or Absol
...

____
#### Affected Versions: 
- Pokecube AIO: v2.0.a
- Minecraft: v1.14.4
- Forge: v28.1.87

This is displayed in the log, not sure if its related or not:
```
[22:19:35] [Client thread/INFO]: [pokecube.core.interfaces.capabilities.impl.PokemobGenes:setSize:499]: EntityDimensions w=0.6, h=0.9, fixed=true 1.0 0.6 0.9 0.6
[22:19:41] [Server thread/INFO]: [pokecube.core.interfaces.capabilities.impl.PokemobGenes:setSize:499]: EntityDimensions w=1.2, h=1.2, fixed=true 1.0596114 1.2715337 1.2715337 1.2715337
```
![2019-11-12_22 19 54](https://user-images.githubusercontent.com/12000593/68733368-13983280-059c-11ea-8f94-fd5618d9f1d1.png) ![2019-11-13_09 31 18](https://user-images.githubusercontent.com/12000593/68779098-b3d07480-05f9-11ea-9932-44d159fae635.png)

**Comment by Thutmose** [comment]
this affects most of the older models in 1.14.4 currently, being one of the primary reasons that release is an alpha, it affects the models using the older model format .tbl
