### ISSUE TITLE
Is there any way to block PMs in certian condition?

### ISSUE THREAD

**Issue by Unknown-Tokyo** [Pokecube-Development/Pokecube-Issues-and-Wiki#1211]
**Is there any way to block PMs in certian condition?**
PMs spawning everywhere, without light or other conditions, and there battle killing other mobs frequently.
I have tried config, but it seems there is only way to block their spawning by biomes and dims, can't stop the spawning on some certian condition, as a result, my ranch and railway are full of PMs 

**Describe the solution you'd like**
if there could be a new config to block PMs' spawning above a block list?

**Describe alternatives you've considered**
or add a block to prevent spawning in a radius?

**Comment by WenXin20** [comment]
Use the Repel Block

**Comment by Unknown-Tokyo** [comment]
> Use the Repel Block

thank you, I did not noticed this
