### ISSUE TITLE
can't make gene selector

### ISSUE THREAD

**Issue by Unknown-Tokyo** [Pokecube-Development/Pokecube-Issues-and-Wiki#1212]
#### Issue Description:
written selector book not recognized

#### What happens:
write a book as selector, but not recognized as a selector in gene extractor, nor can be crafted with nether star

#### What you expected to happen:
the selector book can be recognized in gene extractor
better if there are some pre-defined selectors, this way is a little complicated...

#### Steps to reproduce:

1.write single line with 'all', with or without enter to switch next line in an vanillian book
2.sign 'Selector' to the book
3.it doesn't counted as a selector, can't place in the machine or craft with nether star

the book was written like this guide:
https://pokecube.fandom.com/wiki/File:Reanimating_Fossils-1

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.24.0.k
- Minecraft: 1.19.2
- Forge: 43.4.4
- no other mods, tried in en_us and zh_cn
![QQ截图20240927202038](https://github.com/user-attachments/assets/26c0afc1-36cd-485c-b541-e2cf27ed6a0e)
![QQ截图20240927202245](https://github.com/user-attachments/assets/f19f9ff4-c6a3-45af-95e1-4947784b9d0f)

**Comment by Thutmose** [comment]
It was changed to require `genes:` at the top of the text, so:

```
genes:
all
``` 
should work now

**Comment by Unknown-Tokyo** [comment]
> It was changed to require `genes:` at the top of the text, so:
> 
> ```
> genes:
> all
> ```
> 
> should work now

It works now, thanks.
