### ISSUE TITLE
pokemon mode change

### ISSUE THREAD

**Issue by PokecubePlayer** [Pokecube-Development/Pokecube-Issues-and-Wiki#122]
AIO mod pack, the pokemon, when trying to mode change(like tornadus, using reveal glass) dose not work, when clicked with the items to mode change they don nothing, and only open the pokemons inventory, the ones i tested were:

hoopa-prison bottle
tornadus-reveal glass
lunala/necrozma-n lunarizer
zygarde-zygarde cube

**Comment by Thutmose** [comment]
these work as intended in my development environment, maybe it is fixed for next release, not sure.
