### ISSUE TITLE
PC GUI Buttons & Search Bar Issues

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#123]
#### Issue Description:
- In the PC GUI, the buttons will overlap items in the Favorites List
- Pressing shift while trying to type in the search bar will exit the GUI.

#### What you expected to happen:
- Items should be able to go around the GUI buttons.
- Pressing shift while typing should enter capital letters.

#### Steps to reproduce:

1. Place the PC blocks
2. Enter the GUI
3. Add many blocks to the JEI Favorites by pressing `A` while hovering over an item.
3. Also try typing in the search bar while holding shift.
4. Profit
...

____
#### Affected Versions:

- Pokecube AIO: v2.0.a
- Minecraft: v1.14.4
- Forge: v28.1.92

![2019-11-23_21 05 33](https://user-images.githubusercontent.com/12000593/69489471-d6565f00-0e3d-11ea-9115-0a2fa726fe7e.png)

**Comment by WenXin20** [comment]
Found another couple of bugs:
- Typing `e` in the search bar will exit the inventory.
- When a slot is darkened when a search doesn't find something, it becomes see-through.

**Comment by Thutmose** [comment]
next update should fix the e issue as well as that texture issue for the overlay

**Comment by Thutmose** [comment]
this issue is fixed, so closing it.
