### ISSUE TITLE
Scrambled Megas

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#124]
#### Issue Description:
Mega evolution's always have scrambled names.

#### What happens:
A Mirage Spot appears and spawns a Mega Evolution, the Mega Evolution's name is scrambled even though the base of the Mega Evolution has been captured.

#### What you expected to happen:
Once a base evolution of a Mega has been captured I expect the name to appear so as not to think that the Mega is a new capture.

#### Steps to reproduce:

1. Wait for a Mirage Spot to appear and spawn a Mega Evolution.
2. Compare to Pokemob captured in Pokewatch.
3. Requires base Pokemob 

#### Affected Versions (Do *not* use "latest"): 
- Pokecube AIO: 1.16.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
I am leaving this open until it is also fixed in the 1.14 code
