### ISSUE TITLE
Unregistered

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#125]
#### Issue Description:
Pokemobs not being recorded in Pokewatch

#### What happens:
When your inventory is full Pokemobs getting returned to the PC are not recorded in the Pokewatch.

#### What you expected to happen:
That caught Pokemobs are recorded regardless of whether they stay in your inventory or not.

#### Steps to reproduce:

1. Have a full inventory.
2. Catch a Pokemob.
3. Check record in Pokewatch.

#### Affected Versions (Do *not* use "latest"): 
- Pokecube AIO: 1.16.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
I am leaving this open until it is also fixed in the 1.14 code
