### ISSUE TITLE
Ditto Eggs

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#126]
#### Issue Description:
Ditto's laying eggs.

#### What happens:
When bred with something that cannot breed a Ditto lays a ditto egg. (eg Porygon Z with a Ditto)

#### What you expected to happen:
The Ditto to be unresponsive to unbreedable Pokemobs. (Dittos breeding with Dittos would be fine with Ditto eggs.

#### Steps to reproduce:

1. Leave Ditto and unbreedable Pokemob alone together.
2. Check egg left behind.
3. Ditto egg should be present. 

#### Affected Versions (Do *not* use "latest"): 
- Pokecube AIO: 1.16.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

(Apologies if this is intended just seemed off to me at the time.)

**Comment by Thutmose** [comment]
this is not a bug
