### ISSUE TITLE
Pokemon Do Not Damage the Dragon

### ISSUE THREAD

**Issue by Kaitocain** [Pokecube-Development/Pokecube-Issues-and-Wiki#128]
#### Issue Description:
Pokemon do not damage the ender dragon

#### What happens:
This is what happens in the log 
11-29 20:15:56 [INFO] §aMewtwo§r used §r§aPsychic§r!§r
11-29 20:15:56 [INFO] move queue took 726.0

#### What you expected to happen:
For the move to damage the dragon

#### Steps to reproduce:

1. Enter the end with a pokemon
2. Fight the Dragon with the pokemon
3. Profit?
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.12.2-1.16
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
It turns out, pokemobs can damage the dragon, they just don't agro it :D

**Comment by Thutmose** [comment]
I will leave this issue open until I have it fixed also on the 1.14 version
