### ISSUE TITLE
Server crash bug

### ISSUE THREAD

**Issue by Horhe-debug** [Pokecube-Development/Pokecube-Issues-and-Wiki#129]
Issue Description:  Server crashed upon press G while riding a Groudon to make it use Earthquake on a Koffing in the nether

What happened:   [https://pastebin.com/P4iCahvY](url)

Expected: Groudon to attack Koffing normally

Reproduction:
 1 Put a saddle on a Groudon 
 2 ride it 
 3 Press g to command it to attack a Koffing in the nether with erthquake
 4 .. potential crash..?

**Comment by Thutmose** [comment]
Fixed for 1.12.2, labelling as 1.14.x as reminder to fix on that side as well
