### ISSUE TITLE
Arceus not changing forms with badges

### ISSUE THREAD

**Issue by heroblind** [Pokecube-Development/Pokecube-Issues-and-Wiki#13]
#### Issue Description:
Arceus not changing forms

#### What happens:
I put a badge on Arceus and he does not change I have tried it with all badges.

#### What you expected to happen:
change forms.

#### Steps to reproduce:

1.get a badge
2. put a badge on Arceus
3. then does not change
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube-aio-1.12.2-1.7.1.jar and Pokecube-aio-1.12.2-1.6.24.jar
- journeymap-1.12.2-5.5.2.jar
- CustomNPCs_1.12.2(26aug18).jar
- FoamFix-0.10.1-1.12.2.jar
- thuttech-1.12.2-6.1.0.jar
- jei_1.12.2-4.12.1.217.jar
- JustEnoughResources-1.12.2-0.8.9.48.jar
- XRay-58-vDLB.jar
- Minecraft: 1.12.2
- Forge:1.12.2-14.23.4.2760
------===============------
here ares some badges on him
![arceus1](https://user-images.githubusercontent.com/44307416/47475499-43ce3100-d7e1-11e8-884e-f417da3f6293.png)
![arceus2](https://user-images.githubusercontent.com/44307416/47475500-46308b00-d7e1-11e8-8a82-c99fd56efd00.png)
![arceus3](https://user-images.githubusercontent.com/44307416/47475502-47fa4e80-d7e1-11e8-8793-52d0240bb42f.png)
![arceus4](https://user-images.githubusercontent.com/44307416/47475505-4f215c80-d7e1-11e8-83b3-b8b083cd550e.png)
![arceus6](https://user-images.githubusercontent.com/44307416/47475511-50eb2000-d7e1-11e8-9b6b-598840a24c80.png)
![arceus7](https://user-images.githubusercontent.com/44307416/47475515-55173d80-d7e1-11e8-9931-2d60a9019ae0.png)
![arceus9](https://user-images.githubusercontent.com/44307416/47475516-56e10100-d7e1-11e8-9681-aabb10eda3e5.png)
![arceus8](https://user-images.githubusercontent.com/44307416/47475519-59435b00-d7e1-11e8-9864-f782a0feebaa.png)
![arceus5](https://user-images.githubusercontent.com/44307416/47475527-63655980-d7e1-11e8-928d-358f4f0f49e7.png)

**Comment by Thutmose** [comment]
This bug will be fixed for next release, finally got time to work on bug fixes.

The fix will also deal with a similar issue with silvally
