### ISSUE TITLE
Inventory Erased on Death

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#130]
#### Issue Description:
- If Pokecube is installed, all items will be erased when death occurs.

#### What happens:
- This major issue can simply be replicated by using `/kill @a`, after that, any items in the inventory will be erased instead of dropped.
- Setting the gamerule `keepInventory` to `true` works as a temporary fix.

#### What you expected to happen:
- Items should drop on the ground or allow gravestone mods to store the inventory.

#### Steps to reproduce:

1. Install Pokecube AIO
2. Add items to the inventory
3. Use `/kill @a`
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- `Pokecube AIO: v2.0.a`
- `Minecraft: v1.14.4`
- `Forge: v28.1.96`

**Comment by Thutmose** [comment]
the inventory isn't being erased, it is being set to PC

**Comment by Thutmose** [comment]
this will be fixed for next update, the PC will properly only take filled cubes and pokedexs again

**Comment by WenXin20** [comment]
Nice, thanks!
