### ISSUE TITLE
Trainer Targetting

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#132]
Issue Description:
Trainer Pokemobs targetting players over pokemobs.

What happens:
When trainers start combat the pokemobs target the player before they attack the pokemob.

What you expected to happen:
Pokemobs to attack the opposing pokemob.

Steps to reproduce:
Attack a trainer at close range.

Affected Versions (Do not use "latest"):
Pokecube AIO: 1.16.1
Minecraft: 1.12.2
Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
This might have been fixed in the fix I just pushed for #115, I will need to test it
