### ISSUE TITLE
Trainer Overpopulation

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#133]
Issue Description:
Trainers overpopulating areas. (mainly top of plateaus and in towns)

What happens:
Large amounts of trainers bunching up in specific areas.

What you expected to happen:
Regular trainer behaviour

Steps to reproduce:
No steps required.

Affected Versions (Do not use "latest"):
Pokecube AIO: 1.16.1
Minecraft: 1.12.2
Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
I am closing issues on 1.12.2, as that isn't supported for updates anymore, I think this was fixed for 1.15.2 though?
