### ISSUE TITLE
Wurmple Pokedex

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#134]
Issue Description:
Pokedex has a formatting issue.

What happens:
When inspecting evolution requirements Wurmples info shows a formatting error.

What you expected to happen:
Correct information to be available.

Steps to reproduce:
Open pokedex
Inspect Wurmples pokedex entry.

Affected Versions (Do not use "latest"):
Pokecube AIO: 1.16.1
Minecraft: 1.12.2
Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
marking as 1.14.x as is fixed for previous ones in next update
