### ISSUE TITLE
Cannot create routes

### ISSUE THREAD

**Issue by iiRevenii** [Pokecube-Development/Pokecube-Issues-and-Wiki#143]
#### Issue Description:
Cant use Spawn.xmls to create certain spawns

#### What happens:
correct code is in spawn xml, but when using trainer editor, the route i made doesnt appear

#### What you expected to happen:
I expect to find my route in the list

#### Steps to reproduce:

1.Attempt to make a route
2.Check if its in the trainer editor
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.
Pokecube AIO
- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.12.2
- Forge:

**Comment by Thutmose** [comment]
Hmm, this is working in my development version of AIO (route1 is showing in the editor, and shows in watch properly)
