### ISSUE TITLE
Exp share causing pokemon to attack each others.

### ISSUE THREAD

**Issue by CosmicRune** [Pokecube-Development/Pokecube-Issues-and-Wiki#144]
Hello, I'm having this bug to where the pokemons I have out started attacking each others after I told my primary pokemon to attack something. They're all not on guard mode either. They all have exp share execpt the primary pokemon. Upon taking out the exp share from the pokemons that have them, they stopped attacking each others when I tell the primary pokemon to attack something. So it seems like exp share is causing it.

**Comment by Thutmose** [comment]
This might have been fixed in my recent fix for #115, I will test

**Comment by Thutmose** [comment]
can you confirm whether this bug is fixed? if so, I can close the issue

**Comment by violencedotorg** [comment]
I've had this issue before in an earlier version. I don't have it anymore, so I think it's fixed.
