### ISSUE TITLE
Gene splicing moves does not work correctly

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#146]
#### Issue Description:
Splicing move genes does not work properly

#### What happens:
taking moves genes and trying to give it to a new pokemon through the splicer fails and ends up making the pokemon have no moves at all.

#### What you expected to happen:
pokemon to get moves from the extraced genes and having a custom moveset

#### Steps to reproduce:

1.extract move genes from one pokemon
2.go to gene splicer with said genes
3.put pokemon in splicer to end up with a pokemon with no moves and moves it had deleted
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core: 1.16.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by Thutmose** [comment]
this is fixed for 1.14.4/1.15.2 for the next update of them

Note that it might require multiple splicing attempts for the moves to apply, but they will eventually.
