### ISSUE TITLE
1.12.2 1.17.0 pokedex fixes list

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#147]
Here are the listed issues found with the pokedex moves lists anything marked with a - is fine.

Gigantamax and Dynamax pokmobs need their info fixed on the watch, such as where they come from and what they breed with.

[pokemon galar fixes.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4030154/pokemon.galar.fixes.txt)

**Comment by Thutmose** [comment]
can you modify those into the json, and then send update or do a pull request? the relevant jsons are here:

https://github.com/Pokecube-Development/Pokecube-Mobs/tree/master/src/main/resources/assets/pokecube_mobs/database

https://github.com/Pokecube-Development/Pokecube-Mobs/tree/master/src/main/resources/assets/pokecube_mobs/database/pokemobs
