### ISSUE TITLE
Ability "null"

### ISSUE THREAD

**Issue by violencedotorg** [Pokecube-Development/Pokecube-Issues-and-Wiki#150]
#### Issue Description:
Certain abilities like corrosion will not show up on pokemob.

#### What happens:
Get ability "null".

#### Steps to reproduce:

Force spawn Salazzle with corrosion or Mareanie with merciless or Doublade.
or
Wild pokemon occasionally spawn with a the ability "null".

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- pokecube-aio-1.12.2-1.17.0

**Comment by Thutmose** [comment]
those abilities are not yet in the codebase, so they show up as that

**Comment by violencedotorg** [comment]
Oh ok. Thanks for the response and keep up the good work!
