### ISSUE TITLE
Trainer issue with Recurrent Complex

### ISSUE THREAD

**Issue by Huskyn1nja** [Pokecube-Development/Pokecube-Issues-and-Wiki#153]
Issue Description:
Trainers are not battling as intended when randomly generating in with recurrent complex or other custom structures.

What happens:
When trainers are generated using Recurrent Complex or any mod that creates them they spawn and send out all of their pokemon consecutively and then get flagged as defeated, without any of the pokemon being defeated. The pokemon that are sent out are accurate, and all other details about them are correct.

Recurrent Complex version - RecurrentComplex-1.4.8.1.jar
Pokecube Version - pokecube-aio-1.12.2-1.18.2.jar

What you expected to happen:
Trainers to be spawned in and battle as intended

Steps to reproduce:
Generate a random trainer, have them battle once spawned.

**Comment by Thutmose** [comment]
can you also include the affected versions? ie of RC, Pokecube, etc?

**Comment by Huskyn1nja** [comment]
Sorry about that. The post has been updated with the versions.

**Comment by Thutmose** [comment]
closing 1.12.2 related issues, let me know if it still occurs in 1.15.2+
