### ISSUE TITLE
Forge version 2788+ causes log spam and delayed boot

### ISSUE THREAD

**Issue by schindlershadow** [Pokecube-Development/Pokecube-Issues-and-Wiki#16]
#### Issue Description:
Forge version 2788+ causes log spam and delayed boot. 
Already talked to Thutmose on Discord about this issue, he mentioned:
"I will look into that and see exactly what they don't like about my datawatcher stuff"

#### What happens:
...
Dec 07 21:51:49 MCMA2_Linux_x86_64[25120]: [21:51:46] 0 [WARN] defineId called for: class pokecube.core.entity.pokemobs.GenericPokemob_grovyle from class pokecube.core.interfaces.capabilities.impl.PokemobBase
...

It also does the same thing on the client but it does not slow down boot nearly as much.

#### What you expected to happen:
No log output, faster boot

#### Steps to reproduce:

1. install forge version 2788 or newer
2. install pokecube
3. start client/server

____
#### Affected Versions

- Pokecube AIO: pokecube-aio-1.12.2-1.7.1.jar
- Forge: 2788+

https://pastebin.com/raw/KYimXeBj

**Comment by Thutmose** [comment]
This is fixed for next update.
