### ISSUE TITLE
Items Missing Tooltip Localization

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#160]
#### Issue Description:
Several items are missing tooltip localization.
 - Also noticed the several tooltips start with a lowercase letter, while others are capitalized.

#### What happens:
- Several items are missing tooltip localization, including:
  - Bag (Also missing the item tooltip)
  - PokeWatch
  - Cracked & Chipped Pots
  - Rusted Sword & Shield
  - Azure Flute
  - N-Lunarizer & Solarizer
  - Reveal Glass
  - Prison Bottle
  - Zygarde Cube
  - Crystal Shard
  - Rainbow & Silver Wings
  - Ruby
  - Sapphire
  - Orange, Blue, & Green Runes
  - Gray Orb
  - All Mint Types
  - All Wearable Items
  - Secret Base Biome (For Minimaps)

#### What you expected to happen:
- The player should be able to read the tooltips.

#### Steps to reproduce:

1. Find an item in the list
2. Check the tooltips.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.f`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by Thutmose** [comment]
are any of these still missing?

**Comment by WenXin20** [comment]
The Gray Orb seems to be the only one missing. It says `legends.grayorb.tooltip`.

**Comment by WenXin20** [comment]
Also noticed a misspelling, the Sky Brick is called "Sky Brck"

**Comment by WenXin20** [comment]
Found another:
In the PokéWatch, the stats pg for Pokémobs say AB: `ablity.simple.name`

**Comment by Thutmose** [comment]
this watch ability issue was fixed in with the watches fix
