### ISSUE TITLE
Silvally Ability: RKS System 

### ISSUE THREAD

**Issue by JustHmm** [Pokecube-Development/Pokecube-Issues-and-Wiki#163]
There is no "memory items" so i tested it with other items such as Thunder Stone, Electrizer, Berries but its type is always Normal in pokedex. Jei shows there are many type of it, for example: Ender IO Broken Spawner, Soul Vials and RFTools Syrine shows each 18 type of silvally entity.silvally.name, entity.silvallyelectric.name etc. 
Is this ability working? How can i use it?

pokecube-aio-1.12.2-1.18.2.jar
forge-1.12.2-14.23.5.2847-universal.jar

**Comment by Thutmose** [comment]
try using badges

**Comment by JustHmm** [comment]
Thank you, its working.
