### ISSUE TITLE
Pokecenter spawning needs improvement

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#164]
#### Issue Description:
Pokecenters need spawning improvements.

#### What happens:
- Currently, Pokecenters can spawn partially inside of hills, with entrances being blocked.

#### What you expected to happen:
- The structure should spawn similar to villager buildings, to prevent abrupt changes in terrain near the structure.
- Perhaps the Minecraft Structure Blocks could be used to spawn in the building instead, the way villager buildings are

#### Steps to reproduce:
1. Create a new world.
2. Find the Pokecenter partially buried.
...

#### Screenshot:
![2020-01-29_11 26 14](https://user-images.githubusercontent.com/12000593/73382938-14349100-428e-11ea-9f3c-455291173036.png)

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.g`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by Thutmose** [comment]
ya, it currently doesn't work quite right if there is wide variations in the ground level, I need to look into that

**Comment by Thutmose** [comment]
See if 2.0.0.h fixes this issue enough, it made some adjustments to how they are spawned in

Note that it also re-adds a bunch of missingnos so people complain about them instead of broken models.

**Comment by WenXin20** [comment]
I don't see 2.0.0.h anywhere yet?
