### ISSUE TITLE
Blocks don't drop items when broken

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#166]
#### Issue Description:
Several blocks don't drop anything when broken

#### What happens:
- When a block is broken in survival with an axe, pickaxe, etc, nothing drops.
- This includes logs, planks, bricks, spawn blocks, all the ultra blocks, the Cloning Device, and possibly others that I haven't tested yet.
- Machine blocks are almost impossible to break with a pickaxe and also drop nothing, such as the PC, the Pokecenter, the TM Machine, & Trading Machine.

#### What you expected to happen:
- The player should be able to break and retrieve the block.

#### Steps to reproduce:

1. Place a log/planks.
2. Break it in survival.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.g`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by Thutmose** [comment]
seems I need to add the loot tables for the blocks, and need to re-implement the drops via stick for the other items if you own them

**Comment by WenXin20** [comment]
Fixed, at least with the blocks I tested.
