### ISSUE TITLE
Crash when a Cloning Device is broken

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#167]
#### Issue Description:
After I had broken a Cloning Device in survival, my game crashed soon afterwards.

#### What happens:
- After I had broken a Cloning Device in survival, my game crashed soon afterwards.
- [Crash Report](https://gist.github.com/WenXin20/86265829bace9133638bf65a924d7c85)

#### What you expected to happen:
- The Cloning Device should drop an item when broken.

#### Steps to reproduce:

1. Place a Cloning Device
2. Break it in survival.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.g`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by Thutmose** [comment]
this seems to be related to something else, I need to find better replication instructions before attempting a fix

**Comment by WenXin20** [comment]
I got this crash again, and it's definitely not related to a cloning machine. 
But I have no idea what caused it since I was bone mealing a sapling at the time and hadn't done anything with pokémobs yet. It seems it might be completely random.

**Comment by Thutmose** [comment]
that log doesn't seem to have anything relevant at all in it, just a bunch of optifine and texture errors

**Comment by Thutmose** [comment]
do you have a new crash report?

**Comment by WenXin20** [comment]
I think you only saw the truncated version of the file, the error starts a lot further down.

**Comment by WenXin20** [comment]
Here it is: [Crash Report](https://gist.github.com/WenXin20/a0ac1932dad658b6ba20db8fc1fecd61)

**Comment by Thutmose** [comment]
If you have this issue occur again, please make a new report for it, or ask to re-open this one
