### ISSUE TITLE
Internal crash when healing a pokeball

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#168]
#### Issue Description:
Attempting to heal a Pokemob in a PokeCenter doesn't work.

#### What happens:
- After I had placed a Pokeball in a PokeCenter, nothing happened when I tried to heal it.
- After checking the logs, it appears as if it crashes/errors internally.
- Possibly related to the Sound Control mod.
- No crash report, but here is what was printed in the [logs](https://gist.github.com/WenXin20/ed18b16d8cb22eeefe126b3198af20dc).

#### What you expected to happen:
- The Pokemon should be healed when the heal button is pressed.

#### Steps to reproduce:

1. Place a PokeCenter
2. Try to heal a Pokemon.
...

____
#### Affected Versions:
- `Sound Control: v0.0.4.0`
- `Pokecube AIO: v2.0.0.g`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by Thutmose** [comment]
This particular log was related to a trainer starting to battle something, not related to the pokecenter block, I will try to look into both issues

**Comment by Thutmose** [comment]
either this is fixed for the next update, or somethin else is going wrong on your end, healing works fine in my current development environment (and I didn't specifically try fixing the bug yet?)

**Comment by WenXin20** [comment]
Hmm, I'll try it again with version h. 
Does it instantly heal it when I press the heal button?

**Comment by Thutmose** [comment]
it should

**Comment by Thutmose** [comment]
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/2.0.0.i

**Comment by WenXin20** [comment]
Yup, it works for me now.
