### ISSUE TITLE
Wild Pokémobs in Pokécubes can be picked up

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#169]
#### Issue Description:
Pokémobs in the process of being caught can be picked up.

#### What happens:
- If a Pokécube is punched immediately after trying to catch a wild Pokémob, it will be picked up but is still considered wild.

#### What you expected to happen:
- The Pokécube shouldn't be able to be picked up while catching a Pokémob.

#### Steps to reproduce:

1. Find a wild Pokémob.
2. Throw a Pokécube.
3. Punch it.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.i`
- `Minecraft: v1.14.4`
- `Forge: v28.1.116`

**Comment by WenXin20** [comment]
Also found out that Trainer's Pokécubes can be picked up if they don't immediately open.

**Comment by Thutmose** [comment]
this issue should be fixed now, they now release if you try to pick them up

**Comment by WenXin20** [comment]
I'll test it out tomorrow :)

**Comment by WenXin20** [comment]
That seems to work, but I found a new bug. 
Walking over a Pokécube that's trying to catch a wild Pokémob will stick the Pokécube to you, so whenever you move, it moves with you until it breaks free/is caught.

**Comment by Thutmose** [comment]
these should be fixed with the new pokecube movement code
