### ISSUE TITLE
An Improvement in Meteors

### ISSUE THREAD

**Issue by NelkGames** [Pokecube-Development/Pokecube-Issues-and-Wiki#17]
One suggestion I wanted to make is about the meteors.
Although it is a different mechanic in the mod, many disable it by destroying areas of the map and causing lag.

So ... my suggestion is to reshape the meteor and do the same mechanics as Applid Energisitc, where you dig a place to find it or it appears on the surface and an area around it would be set the sub-biome meteor.

It would be more practical and the meteor radar that stays in pokéwatch would be more used.
![screenshot_4](https://user-images.githubusercontent.com/19228548/50922511-d6ba5700-1431-11e9-8725-e29a30e6ae21.png)

**Comment by P3rf3ctXZer0** [comment]
@NelkGames yeah please help @Thutmose fix this because I absolutely hate current meteors and I always change meteor spawns to use 'ruins' instead.

**Comment by Thutmose** [comment]
this request is in the PR from 2020, so closing issue :D
