### ISSUE TITLE
Option to decrease meteor explosion size

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#179]
**Is your feature request related to a problem? Please describe.**
- Currently, the meteor explosion size can spawn in quite big, which can make a big mess at spawns

**Describe the solution you'd like**
- A config option to decrease it's random explosion size.

**Describe alternatives you've considered**
- None that I can think of.

**Comment by Thutmose** [comment]
there is a config for this, you can change the max size
