### ISSUE TITLE
mc 1.14.4 Pokemobs T posing 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#182]
#### Issue Description:
I chose Scorbunny and it only t poses.

#### What happens:
T posing

#### What you expected to happen:
Animations

#### Steps to reproduce:

1. Grab Scorbunny
2. Throw Scorbunny
3. Enjoy Tposing
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- AIO pokecube-aio-1.14.4-2.0.0.m.jar
- Minecraft 1.14.4
- Forge: 1.14.4 - 28.2.0

this was my only mod.

**Comment by Thutmose** [comment]
add this as a comment to #319 if this issue still occurs please
