### ISSUE TITLE
NBT Editor Doesn't Change Model to Nurse Joy

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#185]
#### Issue Description:
NBT Editor doesn't change the models.

#### What happens:
- The NBT Editor does not change the model of the healer to Nurse Joy

#### What you expected to happen:
- It should change to Nurse Joy.

#### Steps to reproduce:

1. Summon in a npc
2. Use the NBT Editor to change its type to healer.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.0.n`
- `Minecraft: v1.14.4`
- `Forge: v28.2.0`

**Comment by Thutmose** [comment]
this is fixed at least in the 1.15.2 current development environment, should be in the next update.
