### ISSUE TITLE
Problems loading minecraft when loading Pokecube aio ..crashes and says not supported .  

### ISSUE THREAD

**Issue by melissap12345** [Pokecube-Development/Pokecube-Issues-and-Wiki#19]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core:
- Pokecube Revival (if applicable):
- Pokecube Mobs (if applicable):
- Minecraft: 1.12.2
- Forge:

**Comment by Thutmose** [comment]
Top line of this issue tells me to close it immediately, please read what you post as an issue next time.
