### ISSUE TITLE
NPC pokecube crash.

### ISSUE THREAD

**Issue by DiggsMC** [Pokecube-Development/Pokecube-Issues-and-Wiki#194]
#### Issue Description:
java.lang.IllegalStateException: Pose stack not empty
[MC Crash.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4221269/MC.Crash.txt)

#### What happens:
NPC seems to be trying to catch a mob but the pokecube just remains then the game crashes when attempting to pick up said pokecube dropped by the NPC.

#### What you expected to happen:
fix please

#### Steps to reproduce:

1. wait for npc to try catching invisible mob then try to pick up pokecube.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: pokecube-aio-1.15.2-3.0.0.b
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.14

**Comment by Thutmose** [comment]
this crash is caused by something breaking in the rendering system, but I am not sure what, if you can figure out how to replicate it, I can get it fixed.

**Comment by Thutmose** [comment]
npcs don't try to catch mobs, though, I can test some more with battling them.

**Comment by DiggsMC** [comment]
I've never played the mod before so not entirely sure what its all meant to do yet. I've had the same crash when telling my poke to attack an NPC but that doesn't crash every time. Walking over an NPCs dropped poke cube crashes MC every time. I've got 100+ other mods active so i'll try it out on its own(several of which modify mobs). If there's any more info i can provide just let me know. Love to get this working for my niece.

**Comment by DiggsMC** [comment]
Tried without any other mods or interacting with NPCs. Entered a Gym and crashed.
[MC Crash.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4233326/MC.Crash.txt)

**Comment by Thutmose** [comment]
see if this still occurs in this version here: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/1.15.2-2.0.0.t

**Comment by DiggsMC** [comment]
nice one.. no crashes. just the pokemod textures and portals are still messed up. Structures spawn with dirt and trees inside which sometimes means no room for the NPCs.
 Are there any config options to make the NPC players and mobs passive until attacked? I just get slaughtered as soon as i start. Everything just attacks as soon as they see me.
Cheers

**Comment by clyver0** [comment]
have the same problem here, also in this version the bug that the NPC just throws his pokeball continues, mas when i go to the pokeball instead of crashing - that was happening in the oteher version - the pokemon appear and hit me
and yes there's a lot of bugs in textures etc its annoying

**Comment by Thutmose** [comment]
I have not seen this one happen recently, if it does, please make a new report, or request this one be re-opened
