### ISSUE TITLE
Blocks don't drop in 1.15.2

### ISSUE THREAD

**Issue by arata00** [Pokecube-Development/Pokecube-Issues-and-Wiki#202]
In the 2.0.0u  version for 1.15.2 the blocks don't stop they Just disappear

**Comment by Thutmose** [comment]
which blocks specifically?

**Comment by arata00** [comment]
All the blocks that i tried dirt, carpete, planks and sand.

**Comment by Thutmose** [comment]
the blocks seem to be dropping fine in my development environment, maybe things will be fixed when I release the next update?

**Comment by arata00** [comment]
Probably, for now i will keep playing ou 1.14.4. Thanks

**Comment by Thutmose** [comment]
this doesn't appear to be occuring anymore, so closing the issue
