### ISSUE TITLE
Non-host players cannot interact with NPCs in LAN worlds

### ISSUE THREAD

**Issue by LustrousBlue** [Pokecube-Development/Pokecube-Issues-and-Wiki#203]
#### Issue Description:
In a LAN SMP world, all players besides the host are unable to interact with NPC's from this mod outside of trainer battles and selecting your starter from Professor Cedar.

#### What happens:
Players besides the host cannot buy or sell things to Pokecube NPC's

#### What you expected to happen:
Players to be able to trade as normal

#### Steps to reproduce:

1. Host a LAN world 
2. Have another player join via the same network
3. Attempt trading with an NPC, eg. Professor Cedar
...

____
#### Affected Versions (Do *not* use "latest"):

- PokeCube AIO: 1.14.4-2.0.0.u
- Minecraft: 1.14.4
- Forge: 28.2.0

**Comment by Thutmose** [comment]
not been reported lately, so closing this for now, if it happens again, please re-submit a report
