### ISSUE TITLE
Pokémob hit by arrow causes game crash

### ISSUE THREAD

**Issue by Travis9x** [Pokecube-Development/Pokecube-Issues-and-Wiki#23]
[crash-2019-01-25_16.09.49-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/2798214/crash-2019-01-25_16.09.49-client.txt)

#### Issue Description:
More specifically, when a Pokémob is hit by an arrow from an **enchanted** bow, the game crashes.
I am not sure if the enchanted bow is added by another mod or not.

#### What happens:
See above.

#### What you expected to happen:
I would expect the arrow to damage the Pokémob like any other mob (and apply any relevant special affect, depending on the enchantment), and not crash the game.

#### Steps to reproduce:

1.  Find a skeleton carrying an enchanted bow
2.  Use your Pokémob to engage in battle with the skeleton
3.  Hopefully the skeleton will shoot your Pokémob with an arrow, before your Pokémob kills it
4.  Game should crash as a result

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokécube AIO:  1.8.2
- Minecraft:  1.12.2
- Forge:  14.23.5.2808

**Comment by Travis9x** [comment]
[crash-2019-01-25_16.31.19-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/2798245/crash-2019-01-25_16.31.19-client.txt)
Actually, I this crash was due to a regular arrow, not from an enchanted bow.

**Comment by Thutmose** [comment]
Seems to be a bad interaction with OpenModularTurrets, I will look into this.
