### ISSUE TITLE
Dead pokemon in enchanted pokecubes can't be crafted with revives

### ISSUE THREAD

**Issue by Verylism** [Pokecube-Development/Pokecube-Issues-and-Wiki#24]
**What happens:**
Unable to craft a dead pokemon in an enchanted pokeball with a revive

**What you expected to happen:**
I expect it to work the same as crafting a normal dead pokemon with a revive

**Steps to reproduce:**
1. Have an enchanted pokeball
2. Catch a pokemon with the enchanted pokeball
3. Let pokemon die
4. Attempt to craft it with a revive

**Affected Versions**

- Pokecube AIO: 1.8.0
- Minecraft: 1.12.2

**Comment by Thutmose** [comment]
this appears to be working in my version in development, so if it re-occurs after next update, please re-open this issue.
