### ISSUE TITLE
Black starters

### ISSUE THREAD

**Issue by Nogitsu** [Pokecube-Development/Pokecube-Issues-and-Wiki#241]
#### Issue Description:
When selecting the starters in the gui, some of them have black parts

#### What happens:
Starters' models had black parts in the gui

#### What you expected to happen:
The starters' models to be correctly colored

#### Steps to reproduce:

1. Create a game in single player (without gui in config)
2. Move
3. Close the game
4. Enable the gui in config
5. Go back to the single player game

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.3
- Minecraft: 1.14.4
- Forge: 28.2.3

**Comment by Thutmose** [comment]
this should be now fixed in 2.0.4+
