### ISSUE TITLE
Factory biome not being crated.

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#25]
#### Issue Description:
When trying to make the Sub biome factory in a chunk it does not register them and does not turn it into the facotry.

#### What happens:
(read above)

#### Steps to reproduce:

1.Place furnaces in a chunk 
2.Check F3 to see if sub biome has changed
3. 
...

____

-Pokecube AIO 3.30.0
- Minecraft: 1.12.2

**Comment by Thutmose** [comment]
this will be fixed in next update.
