### ISSUE TITLE
Crash w/ Lost Cities

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#253]
#### Issue Description:
World Gen crashes when Lost Cities is enabled.

#### What happens:
- After creating a new world, my game crashed during world generation because of Lost Cities.
- [Crash Report](https://gist.github.com/WenXin20/061692c2089acc3a1c093d2275017a16)

#### What you expected to happen:
- No crashes

#### Steps to reproduce:

1. Create a new world
2. Enable Lost Cities
3. Crash
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.7`
- `Minecraft: v1.15.2`
- `Forge: v31.1.18`

**Comment by Thutmose** [comment]
hmm, seems that lost cities method only takes serverworlds, despite allowing IWorlds as an argument, I can get it fixed for next update
