### ISSUE TITLE
Heracross Mega

### ISSUE THREAD

**Issue by etrotta** [Pokecube-Development/Pokecube-Issues-and-Wiki#254]
#### Issue Description:
Heracross mega evolution is behaving weirdly.

#### What happens:
When I tell it to mega evolve, it doesn't seems to changes form (model) nor change the ability

#### What you expected to happen:
Model change

#### Steps to reproduce:

1. Get a heracross
2. Try to mega evolve it (after giving the stone & having a mega item yourself)
____
#### Affected Versions
- Pokecube AIO: 2.0.6
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
does this still happen?
