### ISSUE TITLE
Secret base entrance

### ISSUE THREAD

**Issue by etrotta** [Pokecube-Development/Pokecube-Issues-and-Wiki#257]
#### Issue Description:
After using a Secret Base block, it turns into a normal stone block.
...also a few more weird things before, like being sent to spawn the first time I left using the block
...plus the wrong messages from inside
...and the block being called "Entrance" even though I'm inside, instead of connection or exit or whatever, but that one is more of a nitpick
#### What happens:
After using a Secret Base block to enter your base from the overworld, it turns into a normal stone block.

#### What you expected to happen:
For it to remain as a Secret Base Entrance

#### Steps to reproduce:

1. Use secret power
2. Enter your base
3. Use it on something inside
4. Exit via that block
5. Go back to your entrance
(6. repeat 2~5?)
____
#### Affected Versions

- Pokecube AIO: 2.0.8
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by etrotta** [comment]
+Spawn Issue;
when you die in the secret bases dimension, you're sent to the spawn of that dimension

**Comment by Thutmose** [comment]
this bug is giving some issues with replicating it, at least the first part
