### ISSUE TITLE
"encountered an error during the load_registries event phase"

### ISSUE THREAD

**Issue by groosen** [Pokecube-Development/Pokecube-Issues-and-Wiki#259]
#### Issue Description:
When I try to run the 2.0.9 1.15.2 version of Pokecube AIO, I get this error during loading:

"Pokecube core (pokecube) encountered an error during the load_registries event phase 

MALFORMED"

instead of it starting. I'm only using Pokecube, so I'm decently sure it's not an incompatability.
Also this is the first time trying to play with pokecube since it was in 1.12.2.
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4395880/latest.log)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.9
- Minecraft: 1.15.2
- Forge: 31.1.0(also happens on 31.1.27)

**Comment by groosen** [comment]
So I found a... solution? I read the log and noticed a bunch of things about resource packs, so I just moved my resourcepack folder to my desktop. It works now I guess, but I hope you can find out why this would happen, because I of course would want to use resource packs.
Also to note, this happens with 2.0.8 and 2.0.7 as well, and that's as far as I've tested.

**Comment by Thutmose** [comment]
your Original Chests.zip has an invalid pack info file, an error at line 4 column 56 

I can make this not crash the game anymore for the next update however

**Comment by Thutmose** [comment]
this mod uses resourcepacks as an additional area to add mobs from, so this crash occured when it was scanning them to check for mobs,

MALFORMED generally indicates that the zip file is corrupted somehow, but the other error indicates that it is something wrong with the pack's info file, maybe that is somehow causing the malformed error as well

**Comment by Thutmose** [comment]
you might want to check that your resourcepacks are actually formatted correctly as well

**Comment by Thutmose** [comment]
this was fixed in the mentioned commit ^
