### ISSUE TITLE
Pay Day isn't dropping gold nuggets.

### ISSUE THREAD

**Issue by BalHum** [Pokecube-Development/Pokecube-Issues-and-Wiki#26]
#### Issue Description:
Pay day used to drop a gold nugget after hitting a mob (pokemob or not) at least twice, dropping another gold nugget after each successful hit. No gold nugget drop.

#### What happens:
When the pokemob uses Pay Day, even if hitting twice or more, no gold nugget is dropped. The animation isn't showing as well.

#### What you expected to happen:
My beautiful Meowth throwing his coins to make golden stuff to papa ;-;

#### Steps to reproduce:

1. Catch a Meowth not much above level 30 (or cancel evolution when he's lvl.28). Must have the move.
2. Uses pay day on zombies or other pokemobs, making sure they can stand one hit at least.
3. Profit.

Note: I haven't tried pay day with other pokemob via TM, nor via leveling the meowth, but i've tried with an alolan and a normal one. I've also tried at the official multiplayer server.

____

- pokecube-aio-1.12.2-1.8.0:
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by Thutmose** [comment]
Check pokecube.cfg

is pokemobsDamageBlocks enabled? that config also enables misc other world effects of moves, such as payday, or, add payday to damageBlocksWhitelist
