### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#267]
#### Issue Description:
The server crashes during world gen

#### What happens:
- In the modpack that I created using the Aternos server, I got an error in the log that closed the server while it was preparing spawn.
- [Server Log](https://mclo.gs/PI9jW4j): Error starts at line `14590`

#### What you expected to happen:
- It should load without crashing

#### Steps to reproduce:

1. Create a server
2. Create a new world w/ PokeCube
...

____
#### Affected Versions:

- `Pokecube AIO: v2.0.10`
- `Minecraft: v1.15.2`
- `Forge: v31.1.35`

**Comment by Thutmose** [comment]
that error message starting on line 14590 is unrelated to what made your server crash, that happens every time my server starts up as well, I haven't had time to look into why yet, and it didn't appear to cause any problems on my end.

Does this crash happen every time?

**Comment by Thutmose** [comment]
For reference, here is the debug and latest logs from the fresh install of 31.1.35 server that I made for testing this:

[debug.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4428309/debug.log)
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4428310/latest.log)

**Comment by WenXin20** [comment]
Its probably being caused by another mod. I was able to get it working this time.
