### ISSUE TITLE
Crash when putting a pokémon egg 

### ISSUE THREAD

**Issue by StitchSparda** [Pokecube-Development/Pokecube-Issues-and-Wiki#268]
#### What happens:
Sometimes minecraft crash when I put a pokemon egg on the ground.

#### What you expected to happen:
Minecraft do not crash 

#### Steps to reproduce:

1. Put the egg on the ground
2.
3.
...

____ 

- Pokecube AIO: 2.0.10
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
does this still happen in 2.0.11?
