### ISSUE TITLE
Genesect bottles lacking genes

### ISSUE THREAD

**Issue by etrotta** [Pokecube-Development/Pokecube-Issues-and-Wiki#269]
#### Issue Description & What happens:
Sometimes when I extract DNA from Dome Fossils on a Gene Extractor, I get bottles without DNA at all, instead of getting Genesect (or Kabuto) DNA

#### What you expected to happen:
For the bottle to contain Genesect Species DNA and be usable on the cloning device.

#### Steps to reproduce:

1. Extract Species DNA from a Dome Fossil
2. Repeat until you get that isn't Kabuto

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.11
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by BlackRainGER** [comment]
3 hours, im able to get (genesect- 0 Genesect / 0 Genesect). im stuck there. 
combining 2 of them makes a kabuto again xD
is there a hidden trick? like taking more than 1 species to get something dominant with genesect genes?

**Comment by Thutmose** [comment]
genesect extraction is possibly worthless at present due to the legendary genes being too unstable to extract
