### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by DigiGlitch** [Pokecube-Development/Pokecube-Issues-and-Wiki#27]
#### Issue Description:
ability to duplicate items using Minecraft's saving mechanic (including server side). causing the server to revert a chunk to a previous state before any changes were made including removing items and blocks.

#### Steps to reproduce:
requirements: two single chests, 47 book and quil, an area outside of spawn chunks.

1. fill 50 pages with symbols such as the following; 쿠ᦦ␏ꤜ, each page must be unique.
2. this is repeated until you have 24 signed books that all have the same 50 pages. then again for the remaining 23 books all signed the same and with 50 more unique pages from step 1
3. create a checkered pattern in the first chest in the chunk starting with the book with 24 copies. then filling in the spaces with the one with 23 copies. there should be 8 of each book remaining. place them in the second chest as it and get the chunk to be saved, (single player just save and quit then load back up on a server walk far enough away from the chunk for the server to unload it then head back to the chunk)
4. now that the chunk has saved do the checkered pattern again on the second chest with only 8 of each book filling the top row first then remove anything that is to be duped from it. once done cause the chunk to be "saved" then return to the chunk everything that was removed from the change after the first time saving the chunk should have returned.

#### what's happening
minecraft cannot easily compress the characters that are filled in the books and the pattern makes it harder causing the chunk file size to be too large so it reverts back to its last saved state.

#### Possible fix
two options exist
first, the least likely possible is to increase the size a chunk's file can be when saving currently is about 1mb if I'm correct
second would be to prevent copy and pasting into books in Minecraft as it is extremely tedious if not impossible for the characters needed
...
____
all versions of minecraft

side note: all 100 pages with these characters are publicly available i can provide it to you for testing if you wish but recomend not here as the easier the information is given the easier to persue

**Comment by Thutmose** [comment]
Hmm, I don't think there is anything I can easily do about this bug unfortunately.

Hopefully vanilla or forge fixes it at some point...
