### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#275]
### Issue Description:
- Multiple blocks are rendering incorrectly.

#### What happens:
- The leaves blocks cause an x-ray effect when placed next to solid blocks
- Mushrooms render opaque when placed
- PC and legendary blocks render without shadowing (Render super bright instead)

#### What you expected to happen:
- Blocks should render correctly
- PC and legendary blocks should render similarily to the cloner or the trading machine which do have shadows rendering on the side. (It's more obvious when looking at a block corner, the corner is indistinguishable when looking at the PC blocks.)

#### Steps to reproduce:

1. Place blocks
1. Observe
...

![2020-04-09_12 28 40](https://user-images.githubusercontent.com/12000593/78923891-84b21800-7a5e-11ea-931a-485754b653b0.png)

![2020-04-09_12 37 46](https://user-images.githubusercontent.com/12000593/78924271-1d489800-7a5f-11ea-9d55-c6fdaa9f954d.png)
____
#### Affected Versions:
- `Pokecube AIO: v2.0.11`
- `Minecraft: v1.15.2`
- `Forge: v31.1.39`

**Comment by WenXin20** [comment]
Crops are also rendering incorrectly when viewed from certain angles.
![2020-04-12_16 19 27](https://user-images.githubusercontent.com/12000593/79080350-bbe02d80-7cd9-11ea-9c57-e1def8a28baf.png)

**Comment by Thutmose** [comment]
pc seems to render fine on my end: 
![image](https://user-images.githubusercontent.com/2363472/79135101-d4edea80-7d7c-11ea-9a17-94096141a80d.png)

**Comment by Thutmose** [comment]
I can replicate the crop render issue: 
![image](https://user-images.githubusercontent.com/2363472/79135192-fa7af400-7d7c-11ea-9f64-282f14a521e3.png)

**Comment by WenXin20** [comment]
The PC is probably an Optifine bug and not Pokécube's then. I started noticing that even some vanilla blocks look like that.

**Comment by Thutmose** [comment]
working on the other ones: 
![image](https://user-images.githubusercontent.com/2363472/79135927-1e8b0500-7d7e-11ea-8f29-e5a33f9d6e13.png)
just the leaves left at present

**Comment by Thutmose** [comment]
![image](https://user-images.githubusercontent.com/2363472/79136447-0962a600-7d7f-11ea-9217-2029e62e595a.png)

**Comment by Thutmose** [comment]
these have been fixed, so closing the issue
