### ISSUE TITLE
Add Forge Tags to Gems

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#277]
**Describe the solution you'd like**
Adding tags to sapphire and ruby gems, such as `forge:gems/ruby` and `forge:gems` would allow compat with other mods that use rubies or sapphires in their recipes.

**Describe alternatives you've considered**
N/A

**Comment by Thutmose** [comment]
feel free to submit a pull request with the needed tag, there should be some examples for adding things to the forge tags there?
