### ISSUE TITLE
Crashed from flying or from a possible mod conflict with 

### ISSUE THREAD

**Issue by RonYuma** [Pokecube-Development/Pokecube-Issues-and-Wiki#280]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

Apparently the first and second time I crashed was from another mod called "far landers" from the crash logs. But It started when I was flying with the pokemon Corviknight, prior to the crash I have been flying with him and had not crashed. But I did experience some stuttering, maybe because the other mods and my world is on amplified, but my computer can handle it. 

#### What happens:

After the crash I tried to resume playing but I couldn't even load, it would load world, go grey and crash again and again. I removed the pokecube modpack from thut and loaded it back. Everything was fine, before moving I saved and quit, put pokecube back in my mod folder and everything was back to normal but all the pokemon I had returned to the PC. Also one of my pokemon I was training "torkoal" went back to level 10 when I was level 30 from me training. 

The game was running fine after catching up, but after flying again the game crashed and I got some error. But this time the game loaded fine, I did crash again but this time I had two pokemon out, corviknight and Torkoal who had both disappeared after the crash. I was able to retrieve  Torkoal with the /pokecube restore give @p but not Corviknight. The strange thing is I did see a level 2 Rookidee that might have been duplicated in the PC after I died and exited the game about 3 days ago. 

#### What you expected to happen:
I expected to load the game and find the pokemon I lost after doing the command but I only got Torkoal back and not the lv 40 Corviknight

#### Steps to reproduce:

1. fly with Corviknight
2. land and start training two pokemon (torkoal had exp share)
3. crashed while loading new terrain
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

crash 1 on the 14th 
[crash-2020-04-14_17.56.42-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4484129/crash-2020-04-14_17.56.42-server.txt)

crash 2 today on the 15th 
[crash-2020-04-15_14.12.31-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4484130/crash-2020-04-15_14.12.31-server.txt)

crash 3 happened right after 
[crash-2020-04-15_14.16.55-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4484133/crash-2020-04-15_14.16.55-server.txt)

crash where I lost pokemon 
[crash-2020-04-15_14.30.44-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4484134/crash-2020-04-15_14.30.44-server.txt)

**Comment by Thutmose** [comment]
can you confirm if this still happens with pokecube aio 2.0.12?

**Comment by Thutmose** [comment]
so several fixes recently should address this.

There are still some cases where it can occur though, from a vanilla minecraft bug, as flying on pokemobs can trigger this:

https://bugs.mojang.com/browse/MC-176240
