### ISSUE TITLE
TM Reward from Pokedex

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#282]
#### Issue Description:
TM reward from pokedex is broken

#### What happens:
When receiving the TM reward from the pokedex/watch you receive the item item.pokecube.tm1 rather than the correct TM Cut, this TM cannot be used to teach the move Cut.

#### What you expected to happen:
TM reward with the correct move installed

#### Steps to reproduce:

1.  Receiving the reward for capturing a specific amount of pokemon
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.12
- Minecraft: 1.15.2
- Forge: 31.1.9

**Comment by Thutmose** [comment]
did you try using the tm? it does actually contain cut, is just labelled wrongly
