### ISSUE TITLE
villages, trainers, scattered/ruin structures and mirage spots spawning in dimensions

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#287]
#### Issue Description:
I can find villages, trainers, scattered/ruin structures and mirage spots all spawn in the end and nether

Same for the Ultra wormhole, except they also have meteors spawning in there, might be spawning in the end and nether too, but I haven't seen any yet.

#### What happens:
I go into the end, and find villages, trainers, scattered/ruin structures and mirage spots,
for the nether I find the dungeon structure and trainers. For the Ultra wormhole, I can find meteors

#### What you expected to happen:
to not see any villages, trainers, scattered/ruin structures and mirage spots
in these dimensions

#### Steps to reproduce:

1. make a nether portal or end portal
2. go into that dimension
3. and if you search around you can find villages, trainers, scattered/ruin structures and mirage spots (for faster find do /locate)
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
Affected versions

Pokecube AIO: 2.0.10, 2.0.11 and 2.0.12

My mods-

- Pokecube AIO: 2.0.12
- JustEnoughitems version 6.0.0.2
- Biomesoplenty 10.0.0.345
- Journeymap 5.7.0beta1
- Kiwi 2.6.5
- snow is real magic 1.7.4
- serene seasons 3.0.0.68
- thuttech 8.0.2
- mixinbootstrap 1.0.2
- Minecraft: 1.15.2
- Forge: 31.1.24
- Minecraft: 1.15.2

**Comment by Thutmose** [comment]
some ofthese are supposed to be there, like the mirage spots/ruins

the villages are not, except in ultraspace, that has villages here

**Comment by Thutmose** [comment]
seems this has re-occured at some point in the last few patches

**Comment by HeroBlindNation** [comment]
All the structures in the nether are on the bedrock roof (unobtainable) unless you cheat.  (except for groudon temple)
