### ISSUE TITLE
Water issues

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#293]
#### Issue Description:
Water related problems

#### What happens:
Pokeballs wait to sink to the bottom if they have no target before opening but the model of the pokeball will stay close to the surface.

Pokemon that are land based sometimes do not move in water (this was only tested on a gallade but will follow up on other tests)

Movement is slow in water for every type even water but only in combat will revert to travel speed when out of combat.

(This issue is unrelated to water but when small pokemon are close to the edges of blocks a pokemon thats attacking them will get stuck close to the top of a block without actually trying to get around it causing the pokemon to stick until given another command)

#### What you expected to happen:
Pokeballs to open when they hit the surface of the water (this might be tricky to implement)

Freedom of movement in water (maybe not rock types although they take damage anyway)

Pokemon to at least move at normal walking speed while in combat underwater.

(to get up on top of the block fully when trying to initiate combat)

#### Steps to reproduce:

throw a pokeball into deep water with no target

use a land based pokemon close to the edge of the water to attack a water type (this maybe a combat range issue)

initiate combat underwater

(on guard mode let a pokemon target a smaller pokemon up one block)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.12
- Minecraft: 1.15.2
- Forge: 31.1.9

**Comment by Thutmose** [comment]
I have just done some work related to re-balancing flying mobs, I will next look into swimming ones

**Comment by Thutmose** [comment]
how many of these issues are still around?

**Comment by MetaltyrantMk2** [comment]
these have all been fixed the guard mode issue has a separate page now ill close this.
