### ISSUE TITLE
Rayquaza as a quest legendary

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#296]
**Describe the solution you'd like**
you can find a Sky Pillar Structure in the ocean somewhere, and when you get to the top there will be a legendary spawner where you need the a new item called the "Jade orb" to spawn rayquaza. (or just make it be the green orb) (Message "[Rayquaza] does not trust you enough for that. Get [Kyogre, Groudon] to Catch this Pokemob."

**Describe alternatives you've considered**
for a less fun/realistic way. Just make it so you need to have Kyogre or groudon to capture rayquaza (just like Eternatus)

**Additional context**
what it looks like from the games
![300px-PRS E_SkyPillar](https://user-images.githubusercontent.com/43615714/80125661-9532ba00-8557-11ea-99ef-e933f6384aab.png)

**Comment by Thutmose** [comment]
this was added in the recent versions, so closing the issue
