### ISSUE TITLE
Getting advancement "welcome to ultra space" in other dimensions

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#298]
#### Issue Description:
Getting advancement "welcome to ultra space" while going in other dimensions

#### What happens
when I go into either the end or nether I get the advancement "Welcome to Ultraspace"

#### What you expected to happen:
not to get it

#### Steps to reproduce:

1. build nether portal or end portal
2. enter it
3. you get the advancement
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.0.12
- Minecraft: 1.15.2
- Forge: 31.1.24

**Comment by Thutmose** [comment]
seems this is a bug that only occurs in the 1.15.2 side, not 1.14.4
