### ISSUE TITLE
A Config To Blacklist/Whitelist Specific Pokemobs

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#301]
**Describe the solution you'd like**
To be able to ban a certain pokemobs With a Config or in-game command

**Describe alternatives you've considered**
I haven't thought of any Alternatives.

**Comment by Thutmose** [comment]
there are already configs for that, just make a resource/datapack which removes spawns for the ones you don't want

**Comment by HeroBlindNation** [comment]
got it
