### ISSUE TITLE
Fishing pokemobs not working

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#304]
#### Steps to reproduce:

1. use a fishing rod near water pokemon
2. wait
3. nothing will happen
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
relabelling this, as it is somewhat working as intended, just should be modified to work better.
