### ISSUE TITLE
No lake/ cave lake biomes

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#309]
#### Issue Description:
What previosly was considered a lake and cave lake sub-biome is no more

#### Steps to reproduce:

1. Find a body of water either above or below the surface
2.Get in the water
3. check your pokewatch
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by HeroBlindNation** [comment]
you can't be in the water, you need to be next to it.

**Comment by HeroBlindNation** [comment]
You can't be in the water, you need to be next to it.
