### ISSUE TITLE
Message Error

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#313]
#### Issue Description:
Sending an invitation

#### What happens:
Get an incorrect message back
![invite message](https://user-images.githubusercontent.com/58304543/80386816-0e7b3580-88e7-11ea-8ebf-423756e73b80.jpg)

#### What you expected to happen:
Get a "message sent" message

#### Steps to reproduce:

1. Send out a team invite
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: [2.1.0]
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
this is in the wrong spot, please re-make the issue here: https://github.com/Thutmose/ThutEssentials/issues
