### ISSUE TITLE
General Mod Compatibility Suggestions

### ISSUE THREAD

**Issue by Thutmose** [Pokecube-Development/Pokecube-Issues-and-Wiki#316]
# Master List of cross-mod support ideas

Please comment with your suggestions, with the mod name, and then a list of compatibility points. Note that this will only apply for mods on 1.14.4/1.15.2, preferably both, though definitely the latter.

## List of suggested mods

-  [ ] Hwyla, TOP, Damage Indicator
-  [ ] Placeholder

### Hwyla, TOP, Damage Indicator

- [ ] Support to allow these to also obfuscate names of unknown pokemobs (issue #162 )

### Placeholder

text

**Comment by WenXin20** [comment]
- Currently, the Neat Bar hides Pokemob's names until a Pokedex is used, but [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla), [TOP](https://www.curseforge.com/minecraft/mc-mods/the-one-probe), & [Damage Indicators](https://www.curseforge.com/minecraft/mc-mods/ama-damage-indicator) make this redundant. (#162)
