### ISSUE TITLE
Regis wont be summoned once exploded

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#317]
#### Issue Description:
Note: After spawning the regi trio, they have the possibility of knowing the move explosion and using it , wich would lead to you having the need to summon them again in order to catch them, the problem is, once you obtain all the requirements for the summon when clicking the regi block with the respective core nothing happens

#### Steps to reproduce:

1.summon a regi with explosion
2.let him explode himself
3.get the recoursces and try to summon him again
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by HeroBlindNation** [comment]
There is a cooldown on summoning legends again when they die. But then knowing the move Self-Destruct Is very annoying.

**Comment by Nueph** [comment]
That´s what´s suposed to happen, the thing is that i waited two days and it still doesnt work

**Comment by HeroBlindNation** [comment]
Two days in game?

**Comment by Nueph** [comment]
No, real days, meaning it was several ingame days.
