### ISSUE TITLE
Clauncher

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#318]
#### Issue Description:
Clauncher has no recorded spawns

#### What happens:
Unsure if clauncher will naturally spawn or if its just a text error in the pokedex

#### What you expected to happen:
Spawn information recorded in the dex

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.1.0
- Minecraft: 1.15.2
- Forge: 31.1.27

**Comment by Thutmose** [comment]
this is fixed for next update
