### ISSUE TITLE
Frozen models with Custom NPC

### ISSUE THREAD

**Issue by Javi185** [Pokecube-Development/Pokecube-Issues-and-Wiki#32]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Frozen NPC

#### What happens:

The models of pokecubes become frozen when you create a NPC (the NPC have the model of pokecube). The animation is frozen and the arms get up. Only with the new models.

#### What you expected to happen:

I think is a configuration because in the preview of the NPC the model are not frozen, and I tried other versions and other mods with the same type of models and this problem in your mod is only with the new models.

#### Steps to reproduce:

1. Create a NPC
2. Use a new model of pokecube (Buzzwole for example)
3. When you create them the NPC become frozen
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube Core: 1.12.2 lastest
- Pokecube Revival (if applicable): 1.12.2 lastest
- Pokecube Mobs (if applicable): 1.12.2 lastest
- Minecraft: 1.12.2
- Forge: lastest version of 1.12.2

**Comment by Thutmose** [comment]
This will be fixed in pokecube AIO version 1.10.1, or pokecube core 6.42.1
