### ISSUE TITLE
Ultra wormhole creation

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#320]
**Describe the solution you'd like**
For Lunala, Solgaleo and Necrozma to be able to create ultra wormholes (uses tons for baseHunger and has a cooldown.

**Describe alternatives you've considered**
Or they can just teleport you into the dimension.

**Comment by Thutmose** [comment]
something similar to this is in the new versions, though is not particularly controllable
