### ISSUE TITLE
Structure in the end not spawning in all biomes

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#327]
#### Issue Description:
There are very few structures in the end dimension due them only spawning in the same biome as the one where we fight the ender dragon

#### What you expected to happen:
structures generating in all end biomes

#### Steps to reproduce:

1.go to the end and explore
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Nueph** [comment]
Might wanna check other strucs as well since now there are more sub types of everybiome

**Comment by Thutmose** [comment]
Can you confirm whether this issue still occurs?

**Comment by Nueph** [comment]
been searching and not only in the end but ultra space and overworld seem to have some areas where nothing generates while other areas where structures spawn in abundance, by areas i mean parts of the world  not biomes.

**Comment by Thutmose** [comment]
any specific patterning on this you noticed?
