### ISSUE TITLE
Being able to see a pokemon´s held item in the pc

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#329]
**Is your feature request related to a problem? Please describe.**
Cant find my exp shares , i know some of my pokemno have them but i have too many to know wichs one have them.

**Describe the solution you'd like**
While hovering the mouse over a pokecube, showing the held item of the pokemon just like it shows its name, lvl, etc.

**Describe alternatives you've considered**
Pheraps being able to find pokemon holding the sought item by typinf the item name in the text box?

**Comment by Thutmose** [comment]
this can be done by holding alt and ctrl, I will also change it so just ctrl alone works for the held item
