### ISSUE TITLE
The Pokémon stay on the player's shoulder.

### ISSUE THREAD

**Issue by NelkGames** [Pokecube-Development/Pokecube-Issues-and-Wiki#33]
it would be something more visually, but the mechanics of the pokémon to be in the shoulder was something fun if it looked, if this function returned would be incredible.

**Comment by Thutmose** [comment]
it is there, shift right click a mob with a stick, it should go on shoulder

**Comment by CorentG** [comment]
Are you talking about the pokemon staying in the shoulder even if you jump off a block ? Because before the pokemon would stay on the shoulder even if you jump. Have you changed something Thutmose ? It would be nice if it come back. ( i'm pretty sure it's a bug)

**Comment by Thutmose** [comment]
this was a result of the code having to be changed to use the same mechanics as parrots. This is now fixed for the next update, which puts the code back to how it was before
