### ISSUE TITLE
Incredble low spawnrate of some legends

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#332]
**Is your feature request related to a problem? Please describe.**
Some pokemon such as the lake trio, meloetta etc have a spawnrate of 0,00x

**Describe the solution you'd like**
Increase some spawn rates to 0.x

**Describe alternatives you've considered**
nothing

**Comment by Thutmose** [comment]
hmm, those ones should probably be increased, they were originally set to essentially nothing as placeholders for deciding on if they should get shrines, etc

**Comment by Thutmose** [comment]
this can now be done with statues/pokedolls. If you buy a pokedoll of the mob you want to spawn, and place it somewhere that it has a very low spawn rate, and apply a redstone signal under the doll, then you can boost the spawn rate
