### ISSUE TITLE
Cant remove Teleport locations on Pokewatch

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#334]
#### Issue Description:
Cant remove Teleport locations on Pokewatch

#### What happens:
I go to the "Teleport Locations" on the Pokewatch and click on the X by a certain teleport location, but it doesn't delete it (tried it with other teleport locations also)

#### What you expected to happen:
for it to remove/delete it/them

#### Steps to reproduce:

1. create a teleport location with the pokewatch by right clicking a poke center block
2. go to your watch and click on "Teleport locations"
3. click the X on the teleport location you created
4. and then it doesn't delete it
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.2.75
- Minecraft: 1.15.2
- Forge: 31.1.24

**Comment by Thutmose** [comment]
you need to click the X, followed by the Y that is enabled right next to it
