### ISSUE TITLE
Using Destiny bond automaticly kills the pokemob

### ISSUE THREAD

**Issue by Nueph** [Pokecube-Development/Pokecube-Issues-and-Wiki#336]
#### Issue Description:
When using the move destiny bond , the pokemob automaticly faints

#### Steps to reproduce:

1.go to a lake
2.target a woobufet
3.watch
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
so here is what is happening:

destiny bond is not implemented yet
so the code read the description, saw the words "the user faints" and decided that what this move does is kill the user :D
