### ISSUE TITLE
Single player unable to battle npc's

### ISSUE THREAD

**Issue by lite567** [Pokecube-Development/Pokecube-Issues-and-Wiki#346]
#### Issue Description:
Npcs not deploying their pokemobs in singleplayer

#### What happens:
Putting down your pokemob close by or attacking the npcs doesnt initiate a battle they run or stare and do nothing. Some npcs still walk towards the player and wait but nothing happens 

#### What you expected to happen:
To be able to battle the npcs in single player

#### Steps to reproduce:

1. load single player
2. attempt to battle npcs
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

Hwyla
Just Enough Items (JEI)
Pokecube AIO
Thut Essentials
Thut's Elevators
ThutPerms
Xaero's Minimap
Xaero's World Map

**Comment by Thutmose** [comment]
are you in creative mode or survival mode?

**Comment by MetaltyrantMk2** [comment]
I tested this as well in survival mode trainers will sit there and stare at you. They will give off villager noises as well. They do combat each other in towns and I could get one to throw pokemon at me by punching them but looking doesn't initiate anything. Nameplates are by default turned off for pokemon. Assumption is that you need to find the prof at the start of the world to get started?

**Comment by MetaltyrantMk2** [comment]
The /help may need to be paged as well as there are more commands than what can fit on the /help screen.

**Comment by Thutmose** [comment]
/help is a vanilla thing, not mine, so that would be up for them to page

**Comment by Thutmose** [comment]
the trainers seem to be battling me just fine, I did as follows:

Created new world in survival mode
Selected starter
wandered around town, and walked in front of a trainer
trainer initiated a battle

**Comment by lite567** [comment]
I tried both in survival and creative. I attempted to make a server and got it running which is when I discovered the npc issue tested on single player and had the same issue went to the official server and everything worked fine there

**Comment by lite567** [comment]
I am using the twitch app to install the mod

**Comment by lite567** [comment]
Deleted the mod and did a fresh install everything working as intended

**Comment by Thutmose** [comment]
it seems this might be related to going into creative mode on the world

**Comment by CockyCock** [comment]
I have had a similar issue. Although, what happened to me was caused when I switched to and from creative mode to spruce up the village I started in. NPC trainers would not challenge me unless I were to hit them. I've launched another Single Player map, and the npcs challenge me perfectly fine.
