### ISSUE TITLE
Rillaboom Breeding

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#347]
#### Issue Description:
Rillaboom breeding problem
Breeding scorbunny and sobble from evoled forms are still possible.

#### What happens:
Rillaboom when bred will give the end result of a rillaboom egg.

#### What you expected to happen:
Rillaboom to give a thwackey egg as a breeding result

#### Steps to reproduce:

1. Breed a Rillaboom (this step was repeated twice to ensure bug regularly occurs)
2. Receive rillaboom egg
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 4.4.0
- Minecraft: 1.15.2
- Forge: 31.1.77

**Comment by Thutmose** [comment]
I get grooky eggs from breeding ditto with rillaboom.

Tested as follows:

/pokemake rillaboom <playername>
/pokemake ditto <playername>
they immediately bred
ditto produced a grooky egg

**Comment by MetaltyrantMk2** [comment]
ill try again with the rillaboom i have see if it replicates
