### ISSUE TITLE
Snagcube crashed the game

### ISSUE THREAD

**Issue by NelkGames** [Pokecube-Development/Pokecube-Issues-and-Wiki#35]
#### Issue Description:
The snagcube crashed the game when it captured a mob.

#### What happens:
when I used the snagcube to capture a creeper, it was captured and then the game crashed.

#### Steps to reproduce:

1. take the snagcube.
2. spawn a mob.
3. try to capture it.
4. if capturing the message will appear in the chat.
5. the game will freeze and close.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.10.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2824

[crash-2019-04-02_11.11.22-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/3034718/crash-2019-04-02_11.11.22-server.txt)

**Comment by Thutmose** [comment]
current workaround, make sure you have a few empty inventory slots when using it. I will fix this when I can.
