### ISSUE TITLE
Dispenser not pulling water back

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#350]
With pokecube installed on latest version, dispensers are dropping water but not pulling the water back into the bucket, on the next signal it drops the empty bucket into the water instead of sucking it into the water bucket in its own inventory.

**Comment by Thutmose** [comment]
found the cause and fixed for next update

**Comment by GogaTheAcute** [comment]
Still not worling thut, still dispensing the empty bucket
