### ISSUE TITLE
Legendaries shouldnt be seen at below lvl 40

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#351]
just as in the games all legendaris should be a minimum level 40,

making it much more awesome and exciting seeing them.

if possible this should be extended into trainer battles, where legendaries dont appear in their inventory until such trainer is able to have lvl 40 pokemon.

would totally add to my experience

**Comment by Thutmose** [comment]
this is possible to do with configs, default configs are set for lvl 1, but it can be set to whatever you want it to be

**Comment by GogaTheAcute** [comment]
Can this become default? or can we have it applied in the server?
