### ISSUE TITLE
Gathering Pokemobs Gather Blocks Below Items

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#356]
seems that if two pokemobs try to gather the same item, the second pokemob will pick the block under the item after the item was already picked up by the first pokemob.

**Comment by Thutmose** [comment]
what block was below?

**Comment by Thutmose** [comment]
I think this is fixed, can you let me know when you next are able to test on the server?
