### ISSUE TITLE
Pokemobs are starving too early but take no damage

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#36]
#### Issue Description:
If owned pokemobs doesnt have foods, they'll "fake starve" while spamming the message with "??? is starving !". It's more of a visual bug.

#### What happens:
When below ~75% of they're hunger bar, pokemobs will starve while not taking damage. They will however start taking actual damage when then have low hunger bar, like normal.

#### What you expected to happen:
Pokemobs starve and take damage only at less than 25% of there hunger bar, like before.

#### Steps to reproduce:

1.Give yourself a pokemob
2.Send it out in the world
3.Wait till the hunger bar drop a bit
4.He should start starving but not taking damage nor really starving.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.10.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2824

**Comment by Thutmose** [comment]
I suspect it is trying to do something like 0.01 damage to them, which is then reduced to 0, I will see about making the messages only appear when it is actually enough to deal damage
