### ISSUE TITLE
DEF and DEFSPE are invalid

### ISSUE THREAD

**Issue by 1105931340** [Pokecube-Development/Pokecube-Issues-and-Wiki#37]
#### Issue Description:
Damage is not reduced by defense.
The same pocket monster. Different defenses IV/EV, but The damage is The same.
(moves ascension So it is with)

#### What happens:
Invalid defense value

#### What you expected to happen:
DEF＆DEFSPE  become useful

#### Steps to reproduce:

1.Spawn two elves of the same race.()
2.Different extreme  IV/EV
3.pokemon attack each of them (same action).

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- pokecube-aio-1.12.2-1.10.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2796

**Comment by Thutmose** [comment]
This was fixed in AIO 1.10.4

**Comment by Thutmose** [comment]
If the bug still occurs after updating mod, please make a comment, and then I will re-open the issue and look into it further
