### ISSUE TITLE
Staying Mon's Vertical Gathering Range

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#370]
**Is your feature request related to a problem? Please describe.**
Pokemobs tend to gather items in a huge vertical place, droppig from towers to get an item at teh bottom and teleporting back.

**Describe the solution you'd like**
A vertical Range limit for gathering mon's gathering AI

**Describe alternatives you've considered**
a range in general, say 5/6 blocks max away from the mon

**Additional context**
looks very silly for them to dive and also emphasises the already weird teleporting back to its stay place if no path is found

**Comment by Thutmose** [comment]
this should be in for the next update, and is deployed on the server, can you test if it is working as intended?
