### ISSUE TITLE
Snagcube not working with phantoms

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#373]
#### Issue Description:
Throwing snagcube at phantom will catch it but will not give you a snagcube with phantom in it. or a snagcube at all.

#### What happens:
Throwing snagcube at phantom will catch it but will not give you a snagcube with phantom in it. or a snagcube at all.

#### What you expected to happen:
to receive a snagcube with a phantom in it in my inventory. 

#### Steps to reproduce:

1.get snagcube
2.throw at phantom and catch it
3.get no snagcube
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.5.0.jar
- Minecraft: 1.15.2
- Forge: 31.1.77

**Comment by Thutmose** [comment]
snag cubes drop the cube, it does not return to your inventory, the phantoms capture just fine, the cube ends up on the ground
