### ISSUE TITLE
1.15.2 Pokecube Adjusted Starter Spawn Rates 2.5% Default.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#374]
**Is your feature request related to a problem? Please describe.**
Starters don't spawn enough

**Describe the solution you'd like**
Starters need to spawn more.

**Describe alternatives you've considered**
My alternative is 4.0% spawnrate

**Additional context**
I really like fennekin

**Comment by GogaTheAcute** [comment]
In games they dont spawn... they should be ridiculously rare imo

**Comment by Aunknownperson** [comment]
ya starters are super rare, but if you want to change the spawn rate, you can go in the game files and change it your self :P

**Comment by Thutmose** [comment]
this can be done easily via datapacks now
