### ISSUE TITLE
Eternatus Eternamax and Dynamax band.

### ISSUE THREAD

**Issue by HeroBlindNation** [Pokecube-Development/Pokecube-Issues-and-Wiki#377]
**Describe the solution you'd like**
 for wishing stars < to be found on the ground as a block, then right clicking it will give you only 1 then the block disappears . It can be used to create a dynamax band which allows your pokemob to dynamax/gigantamax  (recipe is like mega ring but a wishing star instead of a mega stone)

having the ability that you can gigantmax Eternatus into (Eternatus Eternamax) when at a max power spot.

( Information on wishing stars from pokemon https://pokemon.fandom.com/wiki/Wishing_Star )

**Describe alternatives you've considered**
for Dynamax bands to be sold from a merchant for 16 or 32 emeralds instead of finding them and creating one.

**Additional context**
> Wishing Star 3D <
![Wishing_Star_SwSh](https://user-images.githubusercontent.com/43615714/82095073-eac83580-96c3-11ea-9c97-22a1e0c94894.png)
> Wishing Star Pixeled sprite item <
![Bag_Wishing_Star_Sprite](https://user-images.githubusercontent.com/43615714/82095374-86f23c80-96c4-11ea-94e9-791afa6f350e.png)

**Comment by Thutmose** [comment]
the mod just uses mega ring/etc for dynamaxing, so we already have this
