### ISSUE TITLE
Flying on pokemobs in ultra space gets you kicked for flying

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#379]
#### Issue Description:
flying on certain pokemobs in ultra space kicks you from the server with the error (flying is not enbaled on the server)

#### What happens:
flying on a pokemob kicks you in ultra space 

#### What you expected to happen:
to be able to fly without getting kicked in ultra space 

#### Steps to reproduce:

1.ride a flying pokemob
2.start moving foward in the air in ultra space
3.get kicked
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.6.0
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by monkeycrazie** [comment]
![2020-05-17_22 12 58](https://user-images.githubusercontent.com/46906554/82168301-7391cd80-988c-11ea-92f8-6e61b124b4de.png)

**Comment by YaraDada** [comment]
This also seems to be happening in the overworld
