### ISSUE TITLE
PC pokemon Disappear

### ISSUE THREAD

**Issue by 1105931340** [Pokecube-Development/Pokecube-Issues-and-Wiki#38]
#### Issue Description:
The next page of the PC will load pokemon.
Pokemon before loading,"Shift+The left mouse button"Place the pokemon.
Quickly shut down the PC , the newly placed Pokemon disappears.

#### What happens:
Pokemon disappear

#### Steps to reproduce:

1.Open the PC
2.next page
3.Quick "shift + left mouse button" to place pocket monster(Before the Pokemon load is completed)
4.Fast closing PC(Before the Pokemon load is completed)

____

- Pokecube AIO:1.10.4
- Minecraft: 1.12.2
- Forge:14.23.5.2796

**Comment by 1105931340** [comment]
Single player game ＆ server Have tried it all.

**Comment by Thutmose** [comment]
Current workaround: Wait for things to load before interacting with it.
