### ISSUE TITLE
Galar mr.mime glitch

### ISSUE THREAD

**Issue by FireGod123** [Pokecube-Development/Pokecube-Issues-and-Wiki#382]
#### Steps to reproduce:

1.try to capture galar Mr.mime
2.if the pokecube gets trapped between the galar mr.mimes legs it should be working
3.then it should multiply
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- whatever is in the twitch modpack for the mod

**Comment by Thutmose** [comment]
Has this actually happened recently? no idea, as you did not list the actual version numbers
