### ISSUE TITLE
Low Priority: Pokemon on shoulder

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#386]
#### Issue Description:
Pokemon on shoulder

#### What happens:
When lighting torches using a charmander if you shift click too fast charmander ends up on your shoulder despite being labelled false in the json file.

#### What you expected to happen:
Charmander not to be mounted on my shoulder

#### Steps to reproduce:

1. Have charmander out
2. Equip a stick to light and shift click fast to light a torch
3. Charmander should end up on your shoulder. 
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.6.0
- Minecraft: 1.15.2
- Forge: 31.1.77

**Comment by Thutmose** [comment]
shoulder code has been re-worked, so this shouldn't be a problem after next update
