### ISSUE TITLE
pokemon hunger

### ISSUE THREAD

**Issue by Aunknownperson** [Pokecube-Development/Pokecube-Issues-and-Wiki#388]
pokemon hungers completely bugs out, like itll flash between green and going negative, i couldnt find any relations between the pokemon so i picked a variation of pokemon, but all the new/reworked pokemon are all bugged, as well as alot of older pokemon(as seen in the screen shots, i picked some newer ones and older ones)

<img width="388" alt="hunger 1" src="https://user-images.githubusercontent.com/64693020/82500410-52fe8900-9ac1-11ea-8242-878ca462beb8.png">

<img width="387" alt="hunger 2" src="https://user-images.githubusercontent.com/64693020/82500420-585bd380-9ac1-11ea-8cba-07d811aad9d0.png">

<img width="413" alt="hunger 3" src="https://user-images.githubusercontent.com/64693020/82500433-5c87f100-9ac1-11ea-9ca9-8318e679d90b.png">

<img width="431" alt="hunger 4" src="https://user-images.githubusercontent.com/64693020/82500443-5f82e180-9ac1-11ea-844c-c326daee10a7.png">

<img width="415" alt="hunger 5" src="https://user-images.githubusercontent.com/64693020/82500447-63166880-9ac1-11ea-8308-a8aa17a285ae.png">

<img width="396" alt="hunger 6" src="https://user-images.githubusercontent.com/64693020/82500454-66115900-9ac1-11ea-8699-b2844c77813f.png">

- Pokecube AIO:  2.6.3
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
Please include the actual mod version, else I will close this like I closed #389
