### ISSUE TITLE
Visual glitch with mega evolution

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#391]
#### Issue Description:
When you mega evolve a pokemon and take him back to the pokecube, a visual glitched copy of him appears on the place that you took him.

#### What happens:
When you mega evolve a pokemon and take him back, he glitches out and dupe himself, but is just a visual glitch, if you relog on the server he'll disappear.

#### What you expected to happen:
Take my pokemon back normally after mega evolve him.

#### Steps to reproduce:

1.Sent out your pokemon;
2.Mega evolve him;
3.Take him back to his pokecube.
...

____
#### Affected Versions 

- Pokecube AIO: 2.6.3
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
this should be fixed in 2.6.4, I will close the issue once the fix is released
