### ISSUE TITLE
Guard AI

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#392]
#### Issue Description:
Guard AI miscalculation

#### What happens:
While on guard the pokemon attempts to attack the trainer (this attack does no damage but is called in the actions window)

#### What you expected to happen:
While on guard to defend you from damage not attack you

#### Steps to reproduce:

1. Set pokemon on guard mode.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.6.3
- Minecraft: 1.15.2
- Forge: 31.2.0

**Comment by HeroBlindNation** [comment]
4.6.1 Is Version 1.12.2 of minecraft. (this is an old version)
