### ISSUE TITLE
Underground Spawns

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#393]
#### Issue Description:
Pokemon spawning underground

#### What happens:
Pokemon are spawning inside blocks and objects

#### What you expected to happen:
Pokemon to not spawn in inaccessible places

#### Steps to reproduce:

1. Hang around spawn inspect where new pokemon appear.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 4.6.1
- Minecraft: 1.15.2
- Forge: 31.2.0

**Comment by HeroBlindNation** [comment]
This is Still an old version.

**Comment by Thutmose** [comment]
is this on the server? in which case it is 4.6.3 rather than 4.6.1

**Comment by Thutmose** [comment]
also, how far under ground?

**Comment by MetaltyrantMk2** [comment]
Oh apologies misread version numbers its 2.6.3 also only a single level of blocks so you can see the names but not the bodys.
