### ISSUE TITLE
EXP Share not giving EXP

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#395]
## Read and then Delete this section - If this is in your bug report, it will be closed.
as title

#### Issue Description:
normal lvl 30 vs lvl 25 battle, two lvl 2s holding exp share, no exp gained after battle

#### What happens:
no exp gained by exp share holders

#### What you expected to happen:
exp gained

#### Steps to reproduce:

thow two mon out
give exp to one
fight mon 
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: Latest
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
Can you try this again with the exp share holder set to follow and not to sit?

**Comment by GogaTheAcute** [comment]
ok further investigation: sitting or not is not the problem. the problem is trainer battles. only getting exp from wild battles. trainer battles of all varieties, agroed or not

**Comment by Thutmose** [comment]
trainer battle exp is disabled on the server you are playing on, so it won't be giving exp from that, you can blame the people who had stuffed 20 trainers in small boxes to grind exp for that one
