### ISSUE TITLE
energy siphon see through glitch

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#396]
#### Issue Description:
energy siphon becomes see through if carpet or another small item is placed next to it.

#### What happens:
can see through to other side of siphon, only side textures are see through, top and front are still correct.

#### What you expected to happen:
whole block to be solid and not see through whatever is placed next to it

#### Steps to reproduce:

place siphon down
place carpet on ground next to it
check siphon

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

latest modpack on twitch and connected to server

**Comment by Thutmose** [comment]
you really should include screenshots with this kind of report.

this is a known issue, the siphon is waiting on a real model to fix this bug
