### ISSUE TITLE
pokemob just disappear

### ISSUE THREAD

**Issue by welder95** [Pokecube-Development/Pokecube-Issues-and-Wiki#397]
## Issue Description:
i sit my flying pokemon down while i go inside a building and all of a sudden when i go in and come back out they are gone without a trace like i never owned them i have lost 2 now including my charizard which i started out the world with it makes me not wanna play this mod pack anymore because its frustrating 

#### What happens:
my pokemob disappears without a trace like I never had it to begin with 

#### What you expected to happen:
for himto sit and be there wheni get back out briefly

#### Steps to reproduce:

1.
2.
3.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
Please include the actual mod versions, also, is this on singe player or on a server? and did you set it to stay somewhere?

**Comment by welder95** [comment]
I’m not sure mod versions I got fed up with losing everything and deleted
the mod and single player and yes set to stay and sit but never left range
of the Pokémon he always stayed in the top left corner but then when I go
back outside he disappears from the top left and the world

**Comment by Thutmose** [comment]
if you set it to stay, it will disappear from the top corner.

if you set it to sit, it will disappear from the top corner.

mobs set to stay, will try to be in the area where you first set them to stay ,and will tend to go back there if you try to move them

**Comment by welder95** [comment]
Then why do they disappear and they were not in my inventory not in my pc
or anything . They are just gone not around in the over world where I put
them not in my inventory nowhere to be found

**Comment by Thutmose** [comment]
that could possibly be a bug then, what other mods are you using? also, you still have not included the version number of AIO responsible, see if it still occurs in the release 2.7.0, which is about to be uploaded, and if so, please re-make this issue, but with the version number.

**Comment by welder95** [comment]
I literally just added Pokémon adventures didn’t add or take off any mods
and I don’t know the version number I can look tomorrow and see which one
it is when I download it from twitch

**Comment by welder95** [comment]
The version is 1.10.2 is what I had downloaded

**Comment by Thutmose** [comment]
that is an extremely outdated version...

your bug report says minecraft 1.15.2, which this is definitely not the case...

please update to a modern version of minecraft, and see if the issue still persists, whoever made the Pokémon adventures modpack did so with an older, buggy version of the mod, and has not updated it since then

**Comment by welder95** [comment]
How do I go about that cause I just downloaded all Minecraft requirements
like 2 weeks ago and downloaded newest versions I thought

**Comment by Thutmose** [comment]
check the last time thatpack updated, it was years ago.

here are some more updated ones:

https://www.curseforge.com/minecraft/modpacks/pokecube-pack

https://www.curseforge.com/minecraft/modpacks/pokecube-evolved

or you can just manually install the mod by itself from here:

https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi
