### ISSUE TITLE
Battling Still Slow

### ISSUE THREAD

**Issue by GogaTheAcute** [Pokecube-Development/Pokecube-Issues-and-Wiki#398]
not sure if i should report it, and not sure if it was meant to have been fixed in latest update, but battling is still not working properlyu, my mon are still walking around each other scarcely throwing moves, sometimes dying without doing any damage to the wild mob 10 levels below it.

**Comment by Thutmose** [comment]
you really should fill out the form that is suggests when you make an issue.

This is probably something still being worked on, re-report after the next update (with a properly filled form!)
