### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#402]
#### Issue Description:
A localisation

#### What happens:
text locators appear instead of text

#### What you expected to happen:
text to be printed rather than target

#### Areas that need a fix
Mega evolving results in a target after recent fix
e.g. "Pokemon" Mega-evolved into entity.pokecube.gallade_mega
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.7.1
- Minecraft: 1.15.2
- Forge: 31.2.0

**Comment by Thutmose** [comment]
Can you make another issue for the teams part in the thutessentials issue tracker?

issues should be separated by mod, rather than in one place, as the fixes are separate.

https://github.com/Thutmose/ThutEssentials/issues
