### ISSUE TITLE
Water Pokemon

### ISSUE THREAD

**Issue by MetaltyrantMk2** [Pokecube-Development/Pokecube-Issues-and-Wiki#403]
#### Issue Description:
Specific types of water pokemon disappear really quickly after they spawn or have stopped spawning in their entirety.

#### What happens:
Moving around near waterways after the last change occured resulted in many pokemon dying and dropping loot in the water, this may be the cause of hunger but at the same time i have seen very few pokemon respawning back into those areas and some species not at all.

#### What you expected to happen:
All pokemon to spawn in line with their spawnrates.

#### Steps to reproduce:

1. wander near a discovered but inactive water area since the last change.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.7.1
- Minecraft: 1.15.2
- Forge: 31.2.0

**Comment by Thutmose** [comment]
can you confirm if this happens for any newly spawned mobs, it isn't really worth time trying to deal with this if it only affects those that spawned before the AI rework

**Comment by MetaltyrantMk2** [comment]
I'm gonna close this issue i can't replicate it all I can see is the occasional water type dying here or there now. I do know that some new pokemon have spawned before and perished quite quickly but I didn't observe what caused the deaths so this is most likely not an issue that I thought it was.
