### ISSUE TITLE
Level Cap Issue??

### ISSUE THREAD

**Issue by JavinAzrael** [Pokecube-Development/Pokecube-Issues-and-Wiki#405]
### Issue Description:
I cant seem to find any wild pokemon above level 28-30.

#### What happens:
I've been trying to level my pokemon. No matter where I go, though, I seem to hit a wild pokemon level cap at around 28 or 30. And what's more is levels will suddenly dip as well. Even when starting from spawn, picking a direction and just traveling in a (relatively) straight line, pokemon will reach high 20's, then suddenly drop back down. I even just recently found pokemon at level 2 and 3 ages away from spawn. Its even affecting gyms and wild trainers.

#### What you expected to happen:
As what seemed to be happening when starting the world, I expected increased levels the further out I went, or at least some level plateauing between rises as distance increased if just constantly rising as I went out.

#### Steps to reproduce:

1. Turn off vanilla spawns in config
2. change shiny appearance rate (I'm a terrible person, I know)
3. Play
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 5.19.9
        (Running with Adventures, mobs, and Mystery Dungeon)
- Minecraft: 1.12.2
- Forge: 14.23.5.2854

Very new to doing things on github, so not sure how to add tags. Sorry if this is an inconvenience.

**Comment by Thutmose** [comment]
the levels do not just increase with distance, they follow the function in the config:

https://github.com/Pokecube-Development/Pokecube-Core/blob/master/src/main/java/pokecube/core/handlers/Config.java#L496

the default is: `abs((25)*(sin(x*10^-3)^3 + sin(y*10^-3)^3))` where x is the displacement along the x-axis, relative to spawn, and y is the displacement along the z-axis, relative to spawn.

the output then has a variation of 0-5 levels added to it, resulting in a maximum level of around 55

**Comment by Thutmose** [comment]
try plotting that function on any 3-d plotter, with say x and y ranging from -3000 to 3000, you will see some spots where the average is around 45-50, some lines of the lvl 30ish you noticed, and a few spots of lvl 0-5

**Comment by JavinAzrael** [comment]
Thank you very much for the quick reply. I will give this a looking at, graphically, next time I am on.

**Comment by JavinAzrael** [comment]
![MSP51491719671g350ii1a000003cagc73eh4i9h660](https://user-images.githubusercontent.com/12321439/82837824-19da6600-9e7f-11ea-9d7e-0c3fd7ba7b69.gif)
threw it into a grapher. Should I be getting something that looks like this?

**Comment by Thutmose** [comment]
Yep, so those shoulders in the circles are your lvl 30ish areas, the yellow circles are lvl 45-50, and the red areas are low levels, as you can see, there are 2 directions you can walk from spawn, which will result in you never finding anything above lvl 5-10

**Comment by JavinAzrael** [comment]
Yeah, it lines up pretty exact with my experience as well. Id gone back to spawn and headed west in a straight line. Was very confused when I suddenly hit 5s after the 30s. its pretty cool how you have it set up. And again I super appreciate your quick responses. Was the 3000 and -3000 you said earlier, realistic, or were you just using them as examples?

**Comment by Thutmose** [comment]
that plot you made is actually the spawn lvls map, in block coordinates, with 0,0 being spawn location

**Comment by JavinAzrael** [comment]
Alright. Thanks. It's nice to see active modding communities. Appreciate the assistance.
