### ISSUE TITLE
pokemobs spawn inside blocks

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#407]
#### Issue Description:
pokemobs spawn inside farmland and path blocks 

#### What happens:
pokemobs spawn inside farmland and path blocks

#### What you expected to happen:
for them to spawn on top of the blocks or not on them at all

#### Steps to reproduce:

1.wait for pokemob to spawn
2.notice its inside block (farmland or dirt path)
3.???
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.7.2
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by MetaltyrantMk2** [comment]
this is most likely related to #393

**Comment by Thutmose** [comment]
possibly, the fixes I mentioned for #393 were for a different cause than this case however, so it looks like multiple bugs with similar end effects
