### ISSUE TITLE
teleport locations being deleted

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#409]
#### Issue Description:
teleport locations that were set now are being deleted

#### What happens:
teleport locations being deleted from the watch and no longer able to use

#### What you expected to happen:
to have all my teleport locations and not have them disappear 

#### Steps to reproduce:

1.set a teleport location
2.???
3.notice it got deleted
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.7.2
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
this does not occur in development environemnt, so it might be fixed for next update.

the fix for some warppad things might have fixed it, as it uses related code for locations
