### ISSUE TITLE
Item copy BUG!

### ISSUE THREAD

**Issue by 1105931340** [Pokecube-Development/Pokecube-Issues-and-Wiki#41]
#### Issue Description:
Item copy BUG.

#### What happens:
Maybe if you look at the steps, you'll know what's going on.

#### What you expected to happen:
If you can, please solve it as soon as possible.

#### Steps to reproduce:

1. Put items in pokemon's Backpack
2. To burn oneself with flint
3. Use ExchangeMachine,Put the pokemon in.
4. Waiting for death
5. After death,pokemon/pokeBlock Appear at the place of death.(Your computer will have the same Pokemon)
6. Collect items from Pokemon backpacks on the ground,Recall Pokemon on the ground.
7. This time it's PC's pokemon.Release it and you'll find the same items in the Pokemon bag.
PS: Similarly, the treatment machine can also show the same BUG effect.
____

- Pokecube AIO : 1.10.4
- Minecraft: 1.12.2
- Forge: 14.23.5.2796

**Comment by 1105931340** [comment]
Translate for one hour and report for ten minutes.

**Comment by Thutmose** [comment]
I will see about getting this fixed asap.
