### ISSUE TITLE
Npcs not wanting to trade.

### ISSUE THREAD

**Issue by Shadowknight2017** [Pokecube-Development/Pokecube-Issues-and-Wiki#413]
Issue Description
trade with npcs

What happens:
you click on them does nothing some time say he does not want to battle

What you expected to happen:
can trade

Steps to reproduce:
1.click on a npc (like a trainer after beating them or the Professor
2.
3.
...

**Comment by igorsstaker** [comment]
Hi , im having the same issue.Whenever i try to trade with the mods NPCs the trade screen flash and then close.

**Comment by Thutmose** [comment]
are you in creative or survival mode? has the game been in one of these?

**Comment by igorsstaker** [comment]
Survival , didn't use Gamemode change in this world.

**Comment by Thutmose** [comment]
ok,I will see about getting this fixed for next update, it seems to be an issue with how their AI decides if they should trade or battle or not
