### ISSUE TITLE
rainbow sword selling in merchants

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#418]
**Is your feature request related to a problem? Please describe.**
I think it's a little too much to have to kill ho-oh twice and lugia him once to make Keldeo's summoning sword

**Describe the solution you'd like**
Put Rainbow Sword selling on merchants

**Describe alternatives you've considered**
It could be sold in Merchants like the orbs of the other legendary ones, because honestly I think a lot to get a simple mythic

**Additional context**
Can use the another rainbow sword for change keldeo form

**Comment by HeroBlindNation** [comment]
Selling the rainbow sword for 32-64 emeralds would be too easy to obtain, if you capture ho-oh and lugia, you will have enough to make the rainbow sword.

**Comment by Thutmose** [comment]
the keldo sword was split off as a different spawn requirement, I did find a bug with the loot for the rainbow_wings though, it was supposed to give 2 when you caught hooh. This will be fixed for next update
