### ISSUE TITLE
Pokemon Can't change Moves or follow

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#419]
#### Issue Description:
When you sent out the pokemobs, they don’t follow you, and you’re unable to switch moves

#### What happens:
they just stand still without moving with rays of light coming out and you can't get them to follow you beyond being unable to put them sitting, standing or guarding.

#### What you expected to happen:
The pokemobs can follow, change the moves and i can set commands stay/sit/guarding

#### Steps to reproduce:

1.sent out que pokemobs
2.and the pokemobs gonna bugged

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
does this always happen, or only when there is massive lag?

if the server isn't loading in the chunks properly, then this will happen as the mobs will not tick if not loaded nearby, to prevent the server crashing

**Comment by deathxf** [comment]
sometimes even without lag it has happened a lot
