### ISSUE TITLE
Switchboard swindlers

### ISSUE THREAD

**Issue by 1105931340** [Pokecube-Development/Pokecube-Issues-and-Wiki#42]
#### Issue Description:

A way to cheat pokemon.

#### What happens:

Using BUG to make two identical pokemons,Then exchange with others.
The Pokemon after the exchange,Other party Released Pokemon,But it can't be controlled.
I have control.

#### What you expected to happen:

Solve it

#### Steps to reproduce:

1.according to [https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues/41](url) Manufacturing two pokemon.
2.Exchange with others.
3.If the exchange is successful, the other party releases Pokemon first.
4.You'll find that the other person can't control pokemon.You can control that pokemon.

____
- Pokecube AIO : 1.10.4
- Minecraft: 1.12.2
- Forge:14.23.5.2796

**Comment by 1105931340** [comment]
It seems that the link won't open.
That link is another BUG report for me today.

**Comment by prjohns** [comment]
How are you going about this exchanging?

**Comment by 1105931340** [comment]
I think the main reason is to make two pokemons. If they are repaired, they will be all right.

**Comment by Thutmose** [comment]
How did you go about exchanging the pokecubes though?

Did you place it in a chest, and let another pick it up? or did you use trading table?

If you used chest, then it will still belong to original owner

**Comment by 1105931340** [comment]
> How did you go about exchanging the pokecubes though?
> 
> Did you place it in a chest, and let another pick it up? or did you use trading table?
> 
> If you used chest, then it will still belong to original owner


Repeat Pokemon bugs.The new version fixes the bug. 

How should I send you a Chinese translation?
I'm making a Chinese wiki. Where should I talk to you?

**Comment by Thutmose** [comment]
it is probably easiest to contact me here: https://discord.gg/medHvkA

**Comment by Thutmose** [comment]
If discord isn't an option, you can use this issue instead.
