### ISSUE TITLE
shulker shell drop

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#425]
**Is your feature request related to a problem? Please describe.**
and the server now has more vanilla mobs, do not have to take more shulker box

**Describe the solution you'd like**
has no mobs that can drop shulker shell

**Describe alternatives you've considered**
shulker shell could be added to Shellder's drop, clamperl, omanyte

**Additional context**
I like the bag but the shulker box can separate things more easily

**Comment by HeroBlindNation** [comment]
I have the coding for this, but it must be hard to get as that is end game loot. (low chance drop)
