### ISSUE TITLE
Pokemob Hunger Task Crash

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#430]
#### Issue Description:
- The game crashed after loading a world.

#### What happens:
- The game crash seems to be related to Pokemobs eating.
- [Crash Report](https://gist.github.com/WenXin20/fe1fe72516a0947d251dba1d44ecce4a)

#### What you expected to happen:
- No crashes.

#### Steps to reproduce:

1. Have pokemobs eat.
2. ?
...

____
#### Affected Versions:

- `Pokecube AIO: v2.7.8`
- `Minecraft: v1.15.2`
- `Forge: v31.2.5`

**Comment by Thutmose** [comment]
this has the wrong crash report linked, you linked the one for #429 twice I think?

**Comment by Thutmose** [comment]
this is the one for here: https://gist.github.com/WenXin20/478432a12889b46d83e6658302746219

**Comment by WenXin20** [comment]
Oh, oops. Sorry bout that!
