### ISSUE TITLE
Structures generate w/o bases w/ Biomes You'll Go

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#431]
#### Issue Description:
- Structures generate without natural ground.

#### What happens:
- This seems to happen if the mod Biomes You'll Go is installed.

#### What you expected to happen:
- Structures should generate with natural ground that blends into the terrain.

#### Steps to reproduce:

1. Install Biomes You'll Go
2. Find a structure.
...

____
#### Affected Versions:

- [`Biomes You'll Go: v0.4.1-Beta`](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
- `Pokecube AIO: v2.7.8`
- `Minecraft: v1.15.2`
- `Forge: v31.2.5`

**Comment by Thutmose** [comment]
do vanilla villages generate with their bases?

**Comment by WenXin20** [comment]
It seems like they are generating normally

**Comment by WenXin20** [comment]
Fixed with v0.9 of Biomes You'll Go. :)
