### ISSUE TITLE
crystal block texture bugged

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#434]
#### Issue Description:
The texture of crystal blocks make x ray

#### What happens:
crystal blocks when placed against vanilla blocks cause an xray effect like an old bug in the textures of certain pokemon

#### What you expected to happen:
that the textures do not bug and could maintain a transparency effect

#### Steps to reproduce:

1.put crystal blocks near a vanilla blocks
2.make the xray

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
can you include some screenshots?

**Comment by TelepathicGrunt** [comment]
He/she's talking about the Temporal Crystal. I actually came here to report the same thing lol.  The block just needs .notSolid() to be called in the block builder passed into its constructor

![image](https://user-images.githubusercontent.com/40846040/83822875-5177b800-a6a0-11ea-8320-da11a28209c6.png)
