### ISSUE TITLE
Legendary capture issue

### ISSUE THREAD

**Issue by KageOkami020** [Pokecube-Development/Pokecube-Issues-and-Wiki#439]
When going up against a legendary it would let me/us capture it properly , instead it is sensed to us in a pokeball but we don't own it , it will be wild if sent out of this so pokeball , but it gives us a warning that the Pokemon doesn't fit in this area so it has something to do with the new area add-on you added

**Comment by Thutmose** [comment]
please actually fill out the issue form for this
