### ISSUE TITLE
Legendary capture issue 

### ISSUE THREAD

**Issue by KageOkami020** [Pokecube-Development/Pokecube-Issues-and-Wiki#440]
#### Issue Description:
You can capture legendarys and it will say they are wild in the pokeball

#### What happens:
When I was trying to capture kyouger , he came back to me in the pokeball (it was an ultracube) as a wild Pokemon

#### What you expected to happen:
Him to come to me as a claimed Pokemon 

#### Steps to reproduce:

1.stand next to a. Building or block 
2.throw pokeball at legendary 
3.when the Pokemon dissapers it will be in your invatory , throw it out and it will say it's wild

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
check to see if this happens in the current version on the server, I think it might fix it
