### ISSUE TITLE
Possibility to restore pokemon health when player sleeps

### ISSUE THREAD

**Issue by MGracia2020** [Pokecube-Development/Pokecube-Issues-and-Wiki#448]
In some pokemon games players can restore the health of their pokemon when they rest on a bed. I think this feature should be added in this mod.
When a player holds fainted pokemon or pokemon without full health and then sleeps in a bed, pokemon should be now full healed.

**Comment by Thutmose** [comment]
this will be in the next update, it will apply on waking up
