### ISSUE TITLE
Texture bugs in some pokemon

### ISSUE THREAD

**Issue by MGracia2020** [Pokecube-Development/Pokecube-Issues-and-Wiki#449]
#### Issue Description:
Some pokemon have their eyes purple and black because these parts of textures are missing for some reason.

#### What happens:
some pokemon, like eevee, articuno and female gyarados have their eyes with the texture of a missing texture block.
![2020-06-11_13 13 06](https://user-images.githubusercontent.com/64058722/84412759-b0c45380-abdd-11ea-9d66-bcaefb6f3f18.png)
![2020-06-11_13 13 26](https://user-images.githubusercontent.com/64058722/84412786-bc177f00-abdd-11ea-99b6-3a0279c08731.png)
![2020-06-11_13 14 18](https://user-images.githubusercontent.com/64058722/84412798-c174c980-abdd-11ea-9faa-818ee3b9f13d.png)

#### What you expected to happen:
The eyes texture should be shown correctly

#### Steps to reproduce:

1. spawn a eevee (for example)
2. look at the eyes texture
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.7.9
- TLSkinCape: 1.10
- Minecraft: 1.15.2
- Forge: 31.2.5

**Comment by MetaltyrantMk2** [comment]
I'd suggest trying the game without tlskincape running to see if this is a compatibility issue.

**Comment by MGracia2020** [comment]
I ran the game without skincape and textures now are shown normally.
