### ISSUE TITLE
Vivillon textures

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#451]
#### Issue Description:
Vivillon no change the textures when evolve

#### What happens:

vivillon does not change the textures and evolved in different biomes

#### What you expected to happen:
vivillon depending on the biome, it evolves with a different texture

#### Steps to reproduce:

1.evolve the scatterbug in different biome
2.he evolve in the same type vivillon

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.7.9
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by MetaltyrantMk2** [comment]
Theres a texture and model issue page here:
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/issues/319

**Comment by deathxf** [comment]
Meta, thut said this is a bug in the code, the same problem he had with the unown's that only spawned only the letter A

**Comment by MetaltyrantMk2** [comment]
Ah, I should've talked to Thut more about it then the unknown issue I never would've found cause I don't run into them very often.
