### ISSUE TITLE
[MC 1.12.2] Clientside error and disconnect when using TOP addons and Pokecube

### ISSUE THREAD

**Issue by aztectornado** [Pokecube-Development/Pokecube-Issues-and-Wiki#452]
#### Issue Description:
When playing as a client on a server running Pokecube and [The One Probe addons](https://www.curseforge.com/minecraft/mc-mods/top-addons), looking at a pokemob with probe enabled with cause a clientside error and disconnect.  I am unsure whether this is an issue more with TOP or pokecube, but it appears to be pokecube specific. I isolated it to these two in specific, but since it is just a clientside error and disconnect, there is no crash report. Instead I'm including the log file.
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4766763/latest.log)

#### What happens:
It appears that there's an issue with TOP addons attempting to read the pokemob as a tank, and somehow resulting in an overflow when trying to draw a bar for that. This causes the client to hang, then disconnect. Strangely, this only happens in client-server situations, playing in singleplayer works just fine.

#### What you expected to happen:
I expected to get a regular probe readout of the pokemob I was looking at.

#### Steps to reproduce:

1. Install on a server The One Probe, TOP addons, and pokecube. (Curse export provided) [Tester's choice-1.0.0.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/4766764/Tester.s.choice-1.0.0.zip)
2. Connect and ensure your probe is set to extended mode, select any pokemob. (I chose Popplio in testing)
3. Toss your starter mob out and attempt to look at it
4. Crash

____
#### Affected Versions

- Pokecube AIO: 1.18.2
- Minecraft: 1.12.2
- Forge: 14.25.5.2854
- [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe): 1.4.28
- [TOP Addons](https://www.curseforge.com/minecraft/mc-mods/top-addons): 1.13.0

**Comment by aztectornado** [comment]
oh that's embarrassing. I sent the first draft out instead of finishing the report properly.

**Comment by aztectornado** [comment]
Edited to properly include all data.

**Comment by Thutmose** [comment]
that log indicates the issue is something with one of the packets sent by topaddons

**Comment by aztectornado** [comment]
I don't suppose there's an easy way to move this issue straight to their git, is there?

**Comment by P3rf3ctXZer0** [comment]
Copy the top bar and explain this issue. The other approach is you could simply click edit and copy and paste all the text in a new issue.
