### ISSUE TITLE
Magma Blocks Impede Building

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#456]
#### Issue Description:
Magma blocks summon Heatran with a right-click.

#### What happens:
- Magma Blocks will summon Heatran with a right-click, but this prevents placement of blocks when right-clicked.

#### What you expected to happen:
- Blocks should place since it is not the correct item to summon it.
- Requiring a shift-right-click to summon Heatran may also help.

#### Steps to reproduce:

1. Right-click Magma blocks with another block
2. Blocks refuse to place.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.7.9`
- `Minecraft: v1.15.2`
- `Forge: v31.2.19`

**Comment by Thutmose** [comment]
fixed in 2.8.2
