### ISSUE TITLE
No Internet Crash

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#458]
#### Issue Description:
- The game crashes on load without internet.

#### What happens:
- If the player is disconnected from the internet, the game will crash on load.
- [Crash Report](https://gist.github.com/WenXin20/2494094cc5017802b80b15ca2a0c68e1)

#### What you expected to happen:
- No crashes, even without internet.

#### Steps to reproduce:

1. Disconnect from the internet
2. Load the game
3. Crash
...

____
#### Affected Versions:

- `Pokecube AIO: v2.7.9`
- `Minecraft: v1.15.2`
- `Forge: v31.2.19`

**Comment by Thutmose** [comment]
Are you certain that is related to internet? that appears to be a corrupted model instead

**Comment by WenXin20** [comment]
Hmm, now that I think about it, I think I may have deleted the generated folder before I had noticed my internet disconnected, so it's possible that it was a corrupted model instead.
Not sure how it happened though.

**Comment by WenXin20** [comment]
Hasn't happened since, so I'll close this
