### ISSUE TITLE
missing tints using /pokemake

### ISSUE THREAD

**Issue by TeamEeveeG** [Pokecube-Development/Pokecube-Issues-and-Wiki#46]
#### Issue Description:
using "/pokemake <pokemob> r:<value> g:<value> b:<value>" or "/pcedit" does not change tints, even if "/pcedit" is used to modify Alpha.

#### What happens:
Absolutely nothing.

#### What you expected to happen:
To see my pokemob tinted black as explained in https://pokecube.fandom.com/wiki/Spawning_Pokemon

#### Steps to reproduce:
Option 1: Pokemake:
1. Use "/pokemake" in a command block using the "r:<number> g:<number> b:<number>" modifier on top of any other modifiers.
2. You will get a pokemob showing all the modifiers BUT the tint.

Option 2: Pcedit
1. Use the "/pcedit" command on a pokemob to enter the NBT GUI.
2. Try changing the tint under "ForgeCaps-->Genetics-->V-->1st-->V -->Expressed"
3. You can also change Gene1 and Gene2 if you hope your pokemobs will bass that coloration down or change other with things like "FallFlying," "invunrability," "Shiny," etc.
4. As with the Pokemake method, all your changes show EXEPT the tint.

____
#### Affected Versions (Last time, I only showed a few mods, this time, in case of incompatibility, I'm listing them all with a resourcepack at the end, though I'm not going to list libraries.)

- Pokecube AIO: 1.10.7
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Damage Indicators: 1.0
- Albedo (may be the cause of a different glitch, which is why I'm including it despite it being a library): 0.1.3
- JEI: 4.15.0.268
- Quark (1 possible cause, other is further below): r1.5-146
- Baubles: 1.5.2
- BOP: 7.0.1.2419
- Thaumcraft: 6.1.BETA26
- Botania: r1.10-361
- Creatures Love Beacons (soon to be removed from my list): 1.12.2-1.0.1
- CTM: MC1.12.2-0.3.3.22
- CustomNPCs: 1.12
- Dungeons2: 1.7.0
- JER (Just Enough Resources): 1.8.5.27
- Thaumic Augmentation: 1.12.2-1.0.3
- Thaumcraft Inventory Scanning: 2.0.10
- ThaumicJEI: 1.12.2-1.5.6-24 (1.2.1)
- Tresure2: 1.3.0
- Varied Commodities: 1.0
- WorldEdit: 6.1.10-SNAPSHOT;3978-1e3af45
- Xaero's Minimap (full version): 1.16.5
- Pokecube Unit (other potential problem, resourcepack): 7.4

____
#### Screenshots (I used method 2):
![Minecraft 1 12 2 4_21_2019 8_11_03 PM](https://user-images.githubusercontent.com/49796211/56478404-ac3a5a00-6474-11e9-86e4-1ac3d446301f.png)
![Minecraft 1 12 2 4_21_2019 8_12_43 PM](https://user-images.githubusercontent.com/49796211/56478405-b4929500-6474-11e9-98a6-199ea891dd70.png)

**Comment by TeamEeveeG** [comment]
I thought it may be an incompatibility issue, I'm happy it isn't.
Also, did you see a mention to a "missing particles" bug/incompatibility?

**Comment by Thutmose** [comment]
the colouring issue is a bug in thutcore, it will be fixed in the next update.

**Comment by TeamEeveeG** [comment]
Thanks. I'm guessing you noticed it was a bug instead of an incompatibility issue when you (likely) recreated it with just Pokécube AIO.

**Comment by TeamEeveeG** [comment]
Thanks
