### ISSUE TITLE
Pokemons's cries and moves sounds volume doesn't scale with distance

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#475]
#### Issue Description:
Some updates ago sounds emitted from pokemons stopped scaling with distance. Both cries and moves sounds are affected.

#### What happens:
Being at 1 block to a pokemon make no difference than being at 15, but the sounds doesn't play further than 16 block, if the volume was set to 1.

#### What you expected to happen:
The further i am, the quieter the sounds become

#### Steps to reproduce:

1.Make a line of block 
2.Place a pokemon at one extremity
3.Listen to his cry when up close, and when you stand further
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.8.3
- Minecraft: 1.15.2
- Forge: 31.2.31

**Comment by Thutmose** [comment]
It seems the problem is that the files were 2 channel, it needs to be single channel sounds for minecraft to attenuate them.

I will get these existing ones converted over and updated to fix it
