### ISSUE TITLE
Moves sounds doesn't take pitch into account

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#476]
#### Issue Description:
I noticed that the moves's sounds doesn't take the pitch into account.

#### What happens:
Moves sounds only plays the default pitch (1.0)

#### What you expected to happen:
Sounds use the right pitch in moves_anims.json

#### Steps to reproduce:

1.Open moves_anims.json
2.Check constrict's pitch (2.0)
3.When played in game it sound as it was 1.0
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.8.3
- Minecraft: 1.15.2
- Forge: 31.2.31

**Comment by CorentG** [comment]
The volume, soundSource and soundTarget also doesn't work (it only use soundTarget). And the "l" (lenght) argument also isn't working (ex:l2), but i don't know if i should open separate issues for those

**Comment by Thutmose** [comment]
I can look into this, that section of the code hasn't been fully tested since the 1.14 rewrite (sounds in general went a bit funny)

**Comment by Thutmose** [comment]
I have this fixed for the next 1.16.4 version of the mod!
