### ISSUE TITLE
Wormholes spawn in and destroys blocks

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#478]
#### Issue Description:
- Wormholes that spawn will destroy blocks.

#### What happens:
- If a wormhole spawns near a structure, it will destroy those blocks

#### What you expected to happen:
- The wormhole shouldn't spawn where it will destroy blocks

#### Steps to reproduce:

1. Find a structure or build a house
2. Wait for the wormhole to spawn
...
![2020-07-16_16 09 26](https://user-images.githubusercontent.com/12000593/87730138-935e4880-c78c-11ea-802e-f1625b91e9d9.png)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- `Pokecube AIO: v2.8.3`
- `Minecraft: v1.15.2`
- `Forge: v31.2.31`

**Comment by Thutmose** [comment]
closing this issue since wormholes were removed
