### ISSUE TITLE
Eevee eats 2 stacks of berries in one go.

### ISSUE THREAD

**Issue by qpepp** [Pokecube-Development/Pokecube-Issues-and-Wiki#490]
#### Issue Description:
I put 64 berries in my eevees inventory (which they liked) Grepa berry to be exact, and it ate it all in one go.

#### Steps to reproduce:

1. Put the berries into the eevees inventory.
2. Give it a second.
3.Berries gone.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:2.8.3
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
this is fixed in the 1.16.4 version
