### ISSUE TITLE
Trainers wont battle 

### ISSUE THREAD

**Issue by DaniDoom** [Pokecube-Development/Pokecube-Issues-and-Wiki#493]
Issue Description:
Trainers wont fight
What happens:
Whenever i approach a trainer instead of fighting they just say pokecube.trainer.agress_allowed 

What you expected to happen:
The trainer to throw its pokemon out to battle

Steps to reproduce:
1.Walk up to a trainer 
2.Right Click them

Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by nuncaseiescolher** [comment]
I'm having the exact same issue
