### ISSUE TITLE
Improvements to the new WeatherEffects enum

### ISSUE THREAD

**Issue by Thutmose** [Pokecube-Development/Pokecube-Issues-and-Wiki#499]
# This is for discussing improvements/adjustments to the weather effect stuff adjusted in https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/pull/498

The pull request replaced the long[] with a better way of organizing the effects, keyed by an enum, the enum is here:

https://github.com/Pawlost/Pokecube-Issues-and-Wiki/blob/83daa230efaa375675e84813d2a8da8cec075cc8/src/main/java/pokecube/core/moves/PokemobTerrainEffects.java#L38-L41

I suggest splitting this enum into multiples based on the general type of effect.

SAND, RAIN, HAIL, SUN are Weathers
MIST is special, though maybe can count as Weather?
MUD, WATER are terrain effects for affecting attack power
GRASS, ELECTRIC, MISTY, PSYCHIC are terrain types (PSYCHIC not in there currently)
SPIKES, ROCKS, POISON, POISON2, WEBS are entry effects, only triggering when entering the terrain

Maybe split into at least 3 enums, for:

Weather - SAND, RAIN, HAIL, SUN, MIST
Terrain - MUD, WATER, GRASS, ELECTRIC, MISTY, PSYCHIC
Entry - SPIKES, ROCKS, POISON, POISON2, WEBS

**Comment by Pawlost** [comment]
This is going to be hard because json parses int and it expects one enum in order. I going to go open another issue for changing json parser so it can parse enums and make the variable for terrain effects more sensible.
