### ISSUE TITLE
Can't use Trainer editor

### ISSUE THREAD

**Issue by shogunn6** [Pokecube-Development/Pokecube-Issues-and-Wiki#505]
Whenever I right-click on the ground the GUI pops up but the trainer names are grayed out and I cannot spawn any trainers, and if I try to edit an existing trainer or villager the game just freezes until I press escape.

I'm guessing I'm supposed to be able to spawn trainers with the GUI but, as previously stated, it either doesn't work or doesn't even show up.

there aren't really any steps to reproduce it, you just right click with the trainer editor and it either doesn't work or appear.

What I've tried::

~ reinstalling Minecraft
~ reinstalling java (I should note that I have tried both java 8 and AdoptOpenJDK 15 with no difference)
~ running Minecraft with only Pokecube AIO installed
~ reinstalling forge
~ tried on multiple maps
____

- Pokecube AIO 1.15.2 - 2.8.5
- Optifine - 1.15.2 (shader pack: SEUS-Renewed v1.0.1) 
- Minecraft: 1.15.2
- Forge: 31.2.45
- Ultimate Car Mod 2.0.6
- MrCrayfish's Furniture Mod 7.0.0 pre16
- FTB GUI Library 1.0.0.14
- FTB Quests 2.0.2.250
- Item Filters 2.2.0.15
- Moving Elevators 1.2.16
- Obfuscate 0.4.3
- MrCrayfish's Vehicle Mod 0.43.5

**Comment by Thutmose** [comment]
this is fixed in the recent 1.16.4 version
