### ISSUE TITLE
Documentation on config files

### ISSUE THREAD

**Issue by AsixJin** [Pokecube-Development/Pokecube-Issues-and-Wiki#507]
**Is your feature request related to a problem? Please describe.**
I'd like to know how to change the settings, but the config in-game tells you to edit the config files directly, but I have no idea what half of the settings do.

**Describe the solution you'd like**
A complete documentation on what every settings in the various config files does and the options available.

**Describe alternatives you've considered**
Finishing the in-game config or disabling the button.

**Comment by Thutmose** [comment]
almost all of the config options should now have comments describing what they do
