### ISSUE TITLE
Incorrect Plural Spelling of "Leave"

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#520]
#### Issue Description:
New leaf blocks have an incorrect plural spelling.

#### What happens:
New leaf blocks have an incorrect plural spelling.

#### What you expected to happen:
The blocks should be named "Dyna Leaves" instead of "Dyna Leave", etc.

#### Steps to reproduce:
1. Search for the new leaf blocks
2. Compare spelling to the other leaf blocks.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.9.0`
- `Minecraft: v1.15.2`
- `Forge: v31.2.45`

**Comment by Thutmose** [comment]
this is fixed for next update
