### ISSUE TITLE
Gene Splicer & Pokécenter Placement

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#525]
#### Issue Description:
- The Gene Splicer has a misaligned hitbox.

#### What happens:
- The Gene Splicer has a slightly misaligned hitbox when facing any direction except east.
- The Pokécenter also doesn't face the player when placed.

#### What you expected to happen:
- The Gene Splicer's hitbox should be aligned correctly.
- The Pokécenter should face the player when placed.

#### Steps to reproduce:
1. Place a Gene Splicer and the Pokécenter
...

____
#### Affected Versions:

- `Pokecube AIO: v2.9.0`
- `Minecraft: v1.15.2`
- `Forge: v31.2.45`

**Comment by Thutmose** [comment]
the "front" of the pokecenter is the part with the taller face: 
![image](https://user-images.githubusercontent.com/2363472/100409531-198f7300-303a-11eb-916f-3c0dc2a421e3.png)

The splicer thingy however is dealt with nowd

**Comment by WenXin20** [comment]
Ah, I see. Thanks
