### ISSUE TITLE
Pokécube Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#527]
#### Issue Description:
- Server Crash

#### What happens:
- My server crashed as soon as I threw a Pokécube containing a Chickorita.
- [Crash Report](https://gist.github.com/WenXin20/3592ce20e91a2e76faf37a86b306ebe0)

#### What you expected to happen:
- No crashes

#### Steps to reproduce:
1. Throw a Pokécube.
...

____
#### Affected Versions:

- `Pokecube AIO: v2.9.0`
- `Minecraft: v1.15.2`
- `Forge: v31.2.45`

**Comment by Thutmose** [comment]
this is fixed for 2.9.1
