### ISSUE TITLE
pokedex forms crashing

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#528]
Issue Description:
[crash-2020-11-26_18.08.36-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/5605265/crash-2020-11-26_18.08.36-client.txt)

#### What happens:
when using the button to change the forms of pokemon in the pokedex results in a crash

#### What you expected to happen:
to swap between forms without crashing

#### Steps to reproduce:

1.go into the pokedex 
2.look at diffrent forms
3.crash

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.9.0
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
can you confirm if this still occurs in 1.16.4-3.2.0?
