### ISSUE TITLE
Fainting using Pokeplayer causes youto be stuck dying

### ISSUE THREAD

**Issue by TeamEeveeG** [Pokecube-Development/Pokecube-Issues-and-Wiki#53]
#### Issue Description:
If you're using Pokeplayer and faint for any reason (100% chance to occur from death by Poison) then the next time you use that pokemob on the Pokeplayer Transformer, you are stuck in the death animation.

#### What happens:
This is a new reason I can't enjoy survival mode, if I faint, the death animation becomes super annoying, particularly because you may be invincible, but you can't attack. This gets worse in the fact that neither the Pokecenter block nor Nurse Joy can do anything about it

#### What you expected to happen:
I expected to be in the animation until I get healed to show you that the pokemob you're using is unusable. But even when I heal, it doesn't fix the problem.

#### Steps to reproduce:
(fastest method)
1. Locate a Woodland Mansion with pokemobs that are a much higher level than the mob you're testing the glitch on.
2. Make sure you're in Pokeplayer's "Mystery Dungeon Mode" (the name I like to call "being under the effects caused by the Pokeplayer Transformer block")
3. Attack Golbats in Creative Mode (they can poison you, guaranteeing the glitch to work, also always happens in Creative Mode)
4. Faint, transform back into your avatar, heal the pokemob then again into the chosen pokemob
5. Congrats! you're Pokeplayer form is dead!

____
#### Affected Versions

(while I have other mods, I tried it with *just* Pokecube AIO, and it still happened)

Minecraft: 1.12.2
Forge: 14.23.52836
Pokecube AIO: 1.10.8

#### Screenshot (step 5, and super upset about it):
![Minecraft 1 12 2 4_27_2019 7_41_21 PM](https://user-images.githubusercontent.com/49796211/56856800-30cf2180-6928-11e9-94dd-a2c2014ee1dc.png)

**Comment by TeamEeveeG** [comment]
Honestly, I don't have a clue why I kept it to myself for so long. I noticed it Jan 25, 2019, the same day I started using this mod.

**Comment by TeamEeveeG** [comment]
Honestly, this is little more than an annoyance (probably the reason it's low priority).

**Comment by Thutmose** [comment]
The main reason why it is low priority, is that I mostly deal with getting not-pokeplayer-bugs dealt with first, hopefully so someone else will offer to work on development for pokeplayer

**Comment by Thutmose** [comment]
Also, pokeplayer is pretty much only available for messing around with, during normal play, players won't experience it, so I work on the other bugs first (like the crashes from the trainer editor)
