### ISSUE TITLE
Teleport locations not showing up

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#530]
#### Issue Description:
when looking in the pokewatch at teleport locations no show up

#### What happens:
going into the pokewatch and looking at teleport locations shows nothing even making new ones still shows nothing

#### What you expected to happen:
to be able to edit and delete my current teleport locations 

#### Steps to reproduce:

1.set a new teleport location
2.go to teleport location in pokewatch
3.no locations

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 2.9.0
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
can you confirm if this still occurs in 1.16.4-3.2.0?
