### ISSUE TITLE
Wild pokémobs breeding and Rillaboom screen bug

### ISSUE THREAD

**Issue by StitchSparda** [Pokecube-Development/Pokecube-Issues-and-Wiki#544]
1) Wild pokémobs can't breed as well as they could, when two pokémobs start that love phase and hearts comes from them heads they enter into fight damaging each other but not killing. Although when two pokemóbs starts the "love phase" and have another one pokémob of the same species near, they starts to fight until one is left.

2) The second its most of my case, I don't know if anymore is having this problem but when I release my Rillaboom its starts to bug on the screen, when I open the inventory or a chest it pass through the chest. Let me show:

3) When two or more pokémobs from trainer's party are released they want to fight with themselves and ocasionally kill one or more of trainer's party pokémobs.

4) Sometimes when a trainer tell the pokémob to attack a wild pokémob the bar from wild pokémob glitch, it appears and hide a lot of times. Because of the fact that occurs, sometimes trainer's pokémob doesn't attack.

![2020-12-05_23 33 29](https://user-images.githubusercontent.com/63176338/101270192-86e78600-3755-11eb-93e8-7157b04b20bd.png)
![2020-12-05_23 33 29_2](https://user-images.githubusercontent.com/63176338/101270194-8ea72a80-3755-11eb-871c-78a94ca75d52.png)
![2020-12-05_23 33 13](https://user-images.githubusercontent.com/63176338/101270222-d1690280-3755-11eb-8f54-c09237aa834c.png)
![2020-12-05_23 33 13_2](https://user-images.githubusercontent.com/63176338/101270224-d3cb5c80-3755-11eb-9e73-50d845661c12.png)
![2020-12-05_23 33 57](https://user-images.githubusercontent.com/63176338/101270252-0e34f980-3756-11eb-8943-0f69224fe1f6.png)

- Pokecube AIO: 3.0.1
- Minecraft: 1.16.4
- Forge: 35.1.0
- Jei: 7.6.0.58
- Xaero's Minimap: 20.28.1

**Comment by Thutmose** [comment]
1 and 3 might actually be "indended features"

2 is fixed for next update

I think 4 might also be somewhat fixed by the fix for 2
