### ISSUE TITLE
Crash w/ Farlanders & Rediscovered

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#555]
#### Issue Description:
- If the mods The Farlanders or Rediscovered is installed, the game will crash.
- Previously reported to [here](https://gitlab.com/modding-legacy/the-farlanders/-/issues/27), but was told to report it here instead.

#### What happens:
- The game crashes if a Farlander or a Pigman mob spawns in from either Farlanders or Rediscovered.
- [Farlanders Crash Report](https://gist.github.com/WenXin20/fea8c7179bc702ce531d43f06a9a7d76)
- [Rediscovered Crash Report](https://gist.github.com/WenXin20/b0e62c16cea244eef0c64eba9226fbe7)

#### What you expected to happen:
- No crashes

#### Steps to reproduce:
1. Spawn in a Farlander or modded Pigman
2. Crash
...

____
#### Affected Versions: 
- [`Farlanders: v1.3.5`](https://www.curseforge.com/minecraft/mc-mods/farlanders)
- [`Rediscovered: v1.3.4`](https://www.curseforge.com/minecraft/mc-mods/rediscovered)
- `Pokecube AIO: v3.1.1`
- `Minecraft: v1.16.4`
- `Forge: v35.1.13`

**Comment by Thutmose** [comment]
Hmm, I will need to make sure to check where those sensors are being applied
