### ISSUE TITLE
White path below pokemobs (yes, again)

### ISSUE THREAD

**Issue by Yagozito** [Pokecube-Development/Pokecube-Issues-and-Wiki#556]
After sometime playing, the same problem as before is back, idk why, and it don't even crashed

![image](https://user-images.githubusercontent.com/75701586/102279154-b5115680-3f09-11eb-89f7-56b5f025984a.png)

Don't got much to say, because that's it .-.

Game version: 1.15.2

Mods: 

- Forge 31.2.45
- TLSkinCape 1.6
- Xaero's Minimap 20.28.2
- Thut core 99.2.10.1
- Thut crafts 2.10.1
- Thut wearables 2.10.1
- Thut bling 2.10.1
- Pokecube core 2.10.1
- Pokecube mobs 2.10.1
- Pokecube revival 2.10.1
- Pokecube legends 2.10.1
- Traveller's Backpack 4.0.8
- Just enough items 6.0.2.12

**Comment by Thutmose** [comment]
hmm interesting, it is occurring without optifine this time? can you confirm if it happens when a specific mod is added/removed?
