### ISSUE TITLE
1.16.4: Resourceful Bees causing Pokecube's trainers to all become "Merchant John"

### ISSUE THREAD

**Issue by AlluringEmerald** [Pokecube-Development/Pokecube-Issues-and-Wiki#557]
**Issue Description:**
- Having the mod "Resourceful Bees" installed causes all trainers from Pokecube to spawn as "Merchant John".

**What Happens:**
- After generating a new world with Resourceful Bees installed, it causes all trainers to appear as "Merchant John".
- This includes village trainers, tower trainers, gym leaders, and random trainers in the world.

**What you expect to happen:**
- For all trainers to have randomly generated names, titles, and skins with Resourceful Bees installed.

**Steps to reproduce:**
- Generate a new world with both mods installed.
- Load into a world.
- All trainers are Merchant John.

**Affected Versions:**
pokecube-aio-1.16.4-3.1.1
resourcefulbees-1.16.3-0.5.5b
Forge 35.1.13

**Comment by Thutmose** [comment]
these mods seem to work fine for me: 
![image](https://user-images.githubusercontent.com/2363472/102540093-89fb4400-407c-11eb-8c42-2c0e77cab637.png)

are you sure you don't ahve some other mods affecting it?

**Comment by AlluringEmerald** [comment]
> these mods seem to work fine for me:
> ![image](https://user-images.githubusercontent.com/2363472/102540093-89fb4400-407c-11eb-8c42-2c0e77cab637.png)
> 
> are you sure you don't ahve some other mods affecting it?

That's strange. In my modpack removing Resourceful Bees fixes the issue, and adding it back causes the issue once more.
