### ISSUE TITLE
1.16 bugs ive seen so far

### ISSUE THREAD

**Issue by TheUnknownAccount** [Pokecube-Development/Pokecube-Issues-and-Wiki#562]
1st bug: in the new version of pokecube(1.16.4-3.1.1) there is a bug when riding a pokemon if you mega evolve or revert it back to normal form it kicks you off your pokemon making you fall to your death

2nd bug: if you have a pokemon that is bigger then normal, then it glitches out, for example normal size: 1 if you get a size: 2 pokemon, if you open its inventory and then close its inventory it goes back to being size: 1, but if you call it back and send it out again it goes back to size: 2

for bug 1: i was expecting it to where you stay on your pokemon(like how it used to be, this was an issue before in an earlier version when t got updated to i believe 1.12 or 1.15 i forgot which, but was patched, but seems the bug has made its way back in the 1.16 version)

for bug 2: well i expected itto not bug out and for it to stay the size its supposed to be at(or what ever size you get)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube aio 1.15.2-2.2.75
- Minecraft: 1.16.4
- Forge: 35.0.15

**Comment by Thutmose** [comment]
bug 2 should be fixed for the next update.

I will look into bug 1, something must have changed on minecraft's side related to that, as the code hasn't changed recently
