### ISSUE TITLE
Warp pad not breaking

### ISSUE THREAD

**Issue by durpalicous** [Pokecube-Development/Pokecube-Issues-and-Wiki#573]
#### Issue Description:
The warp pads are not breaking.

#### What happens:
I try to break them with my diamond pickaxe and it breaks and then reappears

#### What you expected to happen:
I expected it to drop the block so I could move it elsewhere

#### Steps to reproduce:

1. place warp pad
2. try to break it with anything

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.16.4-3.4.0
- Minecraft: 1.16.4
- Forge: 35.1.12

**Comment by Thutmose** [comment]
the warppads are breaking/dropping fine for me, are you sure something else isn't "protecting" the area you are trying to take it from?

**Comment by durpalicous** [comment]
its ok now, i went into creative to remove them and i dont plan on using them in my world currently. thank you for checking it out.
