### ISSUE TITLE
Alolan Raichu model reverts to Pikachu model while sitting on player's shoulder

### ISSUE THREAD

**Issue by RukiaFeet** [Pokecube-Development/Pokecube-Issues-and-Wiki#574]
#### Issue Description:
Alolan Raichu model reverts to Pikachu model while sitting on player's shoulder

#### What happens:
When you right click Alolan raichu to make him sit on your shoulder, his model changes and looks like Pikachu until he gets off of your shoulder

#### Steps to reproduce:

1. Right click Alolan Raichu with a stick

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.2.0.
- Minecraft: 1.16.4
- Forge: 35.1.13

**Comment by Thutmose** [comment]
had you done something else first? I get the alolan raichu: 
![image](https://user-images.githubusercontent.com/2363472/103017097-1c826400-4511-11eb-8206-02001c260f3b.png)

**Comment by RukiaFeet** [comment]
It was right after i evolved him, so maybe it was an issue with that

**Comment by Thutmose** [comment]
this should be fixed with the new shoulder code as of next update
