### ISSUE TITLE
cant spawn landorus

### ISSUE THREAD

**Issue by TheVampireBrzz** [Pokecube-Development/Pokecube-Issues-and-Wiki#576]
im trying to catch a landorus and keep showing this message
![2020-12-24_17 24 53](https://user-images.githubusercontent.com/50282526/103106673-2b067380-4616-11eb-9ef6-3b42ae56f500.png)

**Comment by Thutmose** [comment]
if you open your watch to the local spawns page, and scroll all the way to the bottom, does it show in the list?

**Comment by TheVampireBrzz** [comment]
i changed the minecraft folder then it worked
