### ISSUE TITLE
Issues with mobs needing specific sided worlds on initialization for checking for pokemob.

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#578]
#### Issue Description:
- Server Crash

#### What happens:
- The server crashes while loading with the Rats mod installed. 
- This did not happen with the previous version.
- Edit: [Crash Reprot](https://gist.github.com/WenXin20/191c40f5997939f5f78d4d5e790dfdc9)

#### What you expected to happen:
- No crashes

#### Steps to reproduce:

1. Load mod on server
2. Crash
...

____
#### Affected Versions:

- [`Rats v7.0.1`](https://www.curseforge.com/minecraft/mc-mods/rats)
- `Pokecube AIO: v3.4.3`
- `Minecraft: v1.16.4`
- `Forge: v35.1.13`

**Comment by Thutmose** [comment]
and this only happens with rats? that is very odd, this is the same kind of crash as before...

**Comment by WenXin20** [comment]
I don't know if its only Rats, its just the mod that appeared in the crash log.

Wait, I posted the wrong crash log. Here's the correct one:
https://gist.github.com/WenXin20/191c40f5997939f5f78d4d5e790dfdc9

**Comment by Thutmose** [comment]
see if 3.4.4 fixes it?

**Comment by WenXin20** [comment]
Yes, it looks to have fixed it.

**Comment by Thutmose** [comment]
Re-opening this as the fix for it causes some other issues it seems

**Comment by Thutmose** [comment]
specifically, minecraft bees need that `isRemote` flag `false`, whereas this rat needs it `true`...

**Comment by WenXin20** [comment]
Huh, interesting

**Comment by Thutmose** [comment]
it doesn't actually crash with the bees, but doesn't allow them to be turned into pokemobs as a result

**Comment by Thutmose** [comment]
there is a different way that might work for the needed check, I will see if I can get it working.

**Comment by Thutmose** [comment]
is this fully fixed now? if so the issue can be closed

**Comment by WenXin20** [comment]
Oh, yeah. It is fixed.
