### ISSUE TITLE
Pokemob's name still obfuscated after capture

### ISSUE THREAD

**Issue by TheVampireBrzz** [Pokecube-Development/Pokecube-Issues-and-Wiki#580]
I used pokemake to spawn giratina then cautgh it 
when change form his name come back but if revert it it shows this strange characters
it happens with other pokemons too

![2020-12-26_13 44 11](https://user-images.githubusercontent.com/50282526/103155805-aafd1c80-4781-11eb-8da2-7f7fb45650ba.png)

**Comment by Thutmose** [comment]
does sending out and recalling it fix it?

**Comment by TheVampireBrzz** [comment]
no

**Comment by Thutmose** [comment]
can you check if this occurs in [3.5.1](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files/3152757)?

**Comment by TheVampireBrzz** [comment]
no its fixed
