### ISSUE TITLE
Flight interrupted by pokemob targeting without agress on.

### ISSUE THREAD

**Issue by loleriz** [Pokecube-Development/Pokecube-Issues-and-Wiki#582]
#### Issue Description:
Flight is practically halted when flying on a pokemob, even without agress on. It still tries to target hostile mobs (especially vanilla ones)

#### What happens:
The pokemob will gain a target and the movement will start to get really jittery and slow down to almost no flight at all.

#### What you expected to happen:
No targets will be acquired when agress is turned off so that any kind of fast movement with a pokemob isn't interrupted.

#### Steps to reproduce:

1. Gain a flying pokemob
2. Turn off agress
3. Fly around and wait for a hostile mob to appear (survival mode works best for this)
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.5.0
- Minecraft: 1.16.4
- Forge: 35.1.13

Here is my mods list

![explorer_5euxFZBvMk](https://user-images.githubusercontent.com/2032606/103184077-ccdaca00-487b-11eb-9191-8913545fa78a.png)
![explorer_oz0bEFt9KJ](https://user-images.githubusercontent.com/2032606/103184078-cea48d80-487b-11eb-91cd-48632400cbe0.png)

**Comment by Thutmose** [comment]
can you test if this bug still occurs in this version?:

https://drive.google.com/file/d/1oZTUlCnIiqog2cunXpsiSDAQcuW2mDza/view?usp=sharing

**Comment by loleriz** [comment]
This fixed it 👍 Turning off agress now doesnt target anything, which is exactly what this needed. Thanks!

However, upon further investigation, it's not all flying pokemobs. I recently gained a Buzzmole and that one is able to leave agress on while flying without stuttering. Gliscor is the one I've been having the stuttering troubles with when targeting mobs. Not sure if you'd want to look into this or not, but regardless it works well with it off. Thanks again :)
