### ISSUE TITLE
Guarding pokemob targets itself

### ISSUE THREAD

**Issue by loleriz** [Pokecube-Development/Pokecube-Issues-and-Wiki#583]
#### Issue Description:
When you set a pokemob to guard, it will target itself for a split second every few seconds

#### Steps to reproduce:

1. Catch a pokemob
2. Give it food, then set it to guard.
3. Walk around with it. You will see the self target pop up every few seconds.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.5.0
- Minecraft: 1.16.4
- Forge: 35.1.22

here is an example
![javaw_GEzwm4bnQ2](https://user-images.githubusercontent.com/2032606/103257196-da648280-4955-11eb-872d-bd96fc2613a7.png)

**Comment by Thutmose** [comment]
can you check if this occurs in [3.5.1](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files/3152757)?

**Comment by loleriz** [comment]
looks to be fixed in this one!
