### ISSUE TITLE
Pokemobs missing alt icons

### ISSUE THREAD

**Issue by loleriz** [Pokecube-Development/Pokecube-Issues-and-Wiki#584]
#### Issue Description:
When you have a pokemob of a type below in your inventory and hold alt with your inventory open (or search for it in the JEI mod interface), it has a purple and black checkerboard to show that it's missing their icon.

Here are the ones that are missing:

1. Doduo
	- doduom.png
2. Gyarados
	- gyaradosm.png
3. Both Eevees
	- eeveem.png
	- eevee_gigantamaxm.png
4. Wobbuffet
	- wobbuffetf.png
5. Shinx
	- shinxf.png
6. Combee
	- combeem.png
7. Hippopotas
	- hippopotasf.png
8. Hippowdon
	- hippowdonm.png
9. Unfezant
	- unfezantm.png

Here is what happens
![javaw_Jb6FrXNMsk](https://user-images.githubusercontent.com/2032606/103258126-8c517e00-4959-11eb-937a-97d56b6fd475.png)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.5.1
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
ya, I need to improve the icon system, I will get that done shortly.

there are presently >2500 icon files, I need a few more than that to account for genders, I will see about a new system for tracking them, and get them re-exported

**Comment by Thutmose** [comment]
can you check if this occurs in [3.5.1](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files/3152757)?

**Comment by loleriz** [comment]
looks to be fixed!
