### ISSUE TITLE
spawns

### ISSUE THREAD

**Issue by TheUnknownAccount** [Pokecube-Development/Pokecube-Issues-and-Wiki#585]
Issue Description:
when exploring/going away from spawn, pokemon do not increase in level UNLESS you go in a specific, meaning exploring/base building is extremely limited due to high levels only spawn in a specific direction/area

 What you expected to happen:

it should not matter what direction you go in, pokemon levels should always increase, depending on how far away from spawn you are, and instead of it being in 1 specific direction, it should radiate outwards from spawn, in all directions, so then you are not limited to going in 1 direction

- Pokecube AIO: 3.5.0
- Minecraft: 1.16.4
- Forge: 35.0.15

**Comment by Thutmose** [comment]
yes, this is how the spawning works.

If you want differently, the `dimensionSpawnLevels` in pokecube-common.toml can be set to whatever level distributions you want.

**Comment by TheUnknownAccount** [comment]
how would i do that? like change the settings so, it does how i discribed? like where it radiates outwards from spawn? so then levels increase in all directions?

**Comment by TheUnknownAccount** [comment]
i think i found the config for it? idk, the way its worded is confusing to me, if you could help explain it more?

# These determine what lvl pokemobs spawn based on location. If central is true, then the origin for the function is 0,0, otherwise it is world spawn. if radial is true, then the function takes the variable r, which is horizontal distance from the origin. Otherwise it takes x and y, which are the horizontal coordinates with respect to the origin.
	dimensionSpawnLevels = ["{\"dim\":\"the_nether\",\"func\":\"abs((25)*(sin(x*8*10^-3)^3 + sin(y*8*10^-3)^3))\",\"radial\":false,\"central\":false}", "{\"dim\":\"overworld\",\"func\":\"abs((25)*(sin(x*10^-3)^3 + sin(y*10^-3)^3))\",\"radial\":false,\"central\":false}", "{\"dim\":\"the_end\",\"func\":\"1+r/200\",\"radial\":true,\"central\":true}"]

**Comment by Thutmose** [comment]
which part do you find confusing about the description, I can try to explain that part more in depth.

the config requires basic understanding of algebra for the radial functions, and a basic understanding of vectors for the one that takes x and y

More advanced understanding of the above allows this config to produce pretty much whatever level distribution you want

**Comment by TheUnknownAccount** [comment]
well, idk much algebra, or any of those any other things(like radial funcations) so like i guess, more or less, just more in depth of how the functions work? and what affects what, like i found out that if i change the ""{\"dim\":\"the_end\",\"func\":\"1+r/200\",\"radial\":true,\"central\":true}" and changed it to ""{\"dim\":\"the_end\",\"func\":\"10+r/200\",\"radial\":true,\"central\":true}"


the pokemon will spawn at level 10 at world spawn, but the level increase(like when trvaeling away from spawn) is not affected, like you still gotta travel an extream distance just for a small increase in level(like i traveled a FAR distance, and the levels went from 10 to 15)

**Comment by Thutmose** [comment]
"how the functions work" is they input the coordinate, either radial (r) or cartesian (x, y) into the function, and whatever the result is, is what it spawns the lvl of the mobs as

**Comment by TheUnknownAccount** [comment]
so how would i make it so pokemon levels increase faster, in shorter distance? because i have to travel an extream distance, just to slightly increase, so would i have to lower what its divided by? like in the function its divided by 200, would lowering that, make pokemon levels increase faster in shorter distance?

**Comment by Thutmose** [comment]
I suggest reading up on some basic algebra, it should explain things, and will be very helpful for dealing with many of the config options in the mod

**Comment by TheUnknownAccount** [comment]
well, idk if ill be able to learn how to, because i do have a learning disability, and makes it extreamly hard for me to learn stuff on my own, but thank you, and could you possibly dm me, explaining how it works in depth. like not every config, but just this one config, and how the  function works for spawning? like how the first number in the function affects the level they spawn at, at the world spawn(0,0)
