### ISSUE TITLE
Crash when ToroHealth is installed

### ISSUE THREAD

**Issue by AlluringEmerald** [Pokecube-Development/Pokecube-Issues-and-Wiki#587]
#### Issue Description:
When playing with Pokecube and ToroHealth a crash is caused whenever picking up a pokemob egg.

#### What happens:
After letting pokemobs breed, or placing an egg down yourself, after you attempt to pick up the egg the game crashes. This only happens when ToroHealth is installed.

#### What you expected to happen:
For there not to be crash when picking up an egg when ToroHealth is installed.

#### Steps to reproduce:

1. Breed pokemon or place an egg on the ground.
2. Pick up the egg.
3. Game crashes.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.16.4-3.5.1
- torohealth-1.16.4-forge-4
- Minecraft: 1.16.4
- Forge: 31.1.28

[crash-2020-12-31_05.36.58-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/5757159/crash-2020-12-31_05.36.58-client.txt)

**Comment by Thutmose** [comment]
this should be fixed now, can you confirm?
