### ISSUE TITLE
Resize vanilla pokemobs in health gui

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#588]
**Is your feature request related to a problem? Please describe.**
- Bigger mobs are cut off in the health gui by the screen edge.

**Describe the solution you'd like**
- Resizing the mob icon would fix it.

**Comment by Thutmose** [comment]
see if this is fixed here? https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/1.16.4-3.6.1
