### ISSUE TITLE
Repositioning Health Bars 

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#589]
#### What happens:
- Repositioning the mob health gui does not reposition the mob preview.
- The health gui positioning also does not take into account the pokemob moves, so they are cut off by the screen edge.

#### What you expected to happen:
- The mob preview should move
- The health gui could move up when moves are added.

#### Steps to reproduce:

1. Pull out a pokemob
2. Reposition gui
3. Observe
...

![2021-01-01_19 54 34](https://user-images.githubusercontent.com/12000593/103449299-ea3cd900-4c6b-11eb-8f21-82a4a26abf4b.png)

____
#### Affected Versions:

- `Pokécube AIO: v3.6.0.b`
- `Minecraft: v1.16.4`
- `Forge: v35.1.28`

**Comment by Thutmose** [comment]
on the moves thing, if you move it down to the bottom edge, you should set `guiDown` to false

For the mob's rendering, I do need to fix that, I also need to make the gui respect the configs for `guiSize`, etc, which are currently not functional.

**Comment by WenXin20** [comment]
Ah, thanks. I didn't realize `guiDown` was an option.

**Comment by WenXin20** [comment]
On the topic of gui's, the pokemob rendering hides the text in the textbox.
![2021-01-02_00 37 58](https://user-images.githubusercontent.com/12000593/103452296-5f6fd480-4c93-11eb-8986-771414dffd9d.png)

**Comment by Thutmose** [comment]
the fix for #588 should also fix that one, as it will affect all gui rendering, to make them fit in the correct boxes

**Comment by WenXin20** [comment]
Oh, true

**Comment by Thutmose** [comment]
scale and position now both respond correctly: 
![image](https://user-images.githubusercontent.com/2363472/103464228-17d36200-4d00-11eb-898c-8c2d16050b97.png)

**Comment by Thutmose** [comment]
see if this is fixed here? https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/releases/tag/1.16.4-3.6.1
