### ISSUE TITLE
Unable to edit NPC's moveset

### ISSUE THREAD

**Issue by Roltas** [Pokecube-Development/Pokecube-Issues-and-Wiki#595]
Issue Description:
The Trainer Editor won't let you edit the moveset of any Pokémon from a NPC Trainer

What happens:

Whenever you try to edit the moveset of a Pokémon from a NPC's team, it won't let you add, delete or change any of the moves. Species, abilities, IVs and EVs and enything else is fine and the changes do apply, the moveset is the only thing you're unable to change.

What you expected to happen:

Being able to fully customize NPC teams exactly as you could back when the Trainer Editor was an item in previous versions.

Steps to reproduce:

1. Use the Trainer Editor on a NPC/Spawn a new Trainer
2. Add Pokémon to its team or pick already existing ones
3. Try to delete, add or change its moveset and apply the changes.
____
Affected Versions: 

- Pokecube AIO: 3.6.1
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by Thutmose** [comment]
I will look into this, current workaround:

right click them with pokedex
take out the pokemob
teach it the moves you want
right click with pokedex again
put the pokemob back in
