### ISSUE TITLE
Missing Lorelei skin

### ISSUE THREAD

**Issue by Roltas** [Pokecube-Development/Pokecube-Issues-and-Wiki#597]
Issue Description:
Elite Four Lorelei is missing her skin and is displayed as default female instead. So far, the other NPC seem to be fine.

#### What happens:
![2021-01-09_18 50 13](https://user-images.githubusercontent.com/76397737/104105198-d49f6300-52ac-11eb-9b0a-b36a08d33ac7.png)
![2021-01-09_18 49 17](https://user-images.githubusercontent.com/76397737/104105194-d23d0900-52ac-11eb-8cd6-6d92beb32d2b.png)
____
Affected Versions:

- Pokecube AIO: 3.7.0
- Minecraft: 1.16.4
- Forge: 35.1.36

**Comment by Thutmose** [comment]
can you start up the world with that npc, then send the logs it generates for that session? they should indicate what texture it was looking for before it went to default
