### ISSUE TITLE
Datapack Legendary spawn don't work without config adjustment

### ISSUE THREAD

**Issue by Underllock** [Pokecube-Development/Pokecube-Issues-and-Wiki#601]
When making a datapack to add spawns from some legendary pokemons, I found that they are not generated, even with the chance of spawn appearing on Pokewatch. They do not spawn even by changing the information contained in [general] in pokecube_legends-common.toml.
There must be some other legendary protection that prevents spawn altered by datapacks, and it would be great if you could remove that limitation. Thank you so much for this mod.

Pokecube AIO: 3.7.0
Minecraft: 1.16.4
Forja: 35.1.13

![unknown](https://user-images.githubusercontent.com/69169750/104380600-03fedb80-550a-11eb-8592-88ddeafa0150.png)

**Comment by Thutmose** [comment]
try setting `minLegendLevel` to `0` in `pokecube-common.toml`?
