### ISSUE TITLE
Configurable Replacement List

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#605]
**Is your feature request related to a problem? Please describe.**
- Using a datapack to gen berry trees can sometimes cut into terrain.

**Describe the solution you'd like**
- A configurable replacement list to configure which blocks are replaced, including block tags.

**Describe alternatives you've considered**
- None as of now.

**Comment by Thutmose** [comment]
I suspect this is no longer an issue with the new worldgen? re-open as bug report if it ends up still occuring
