### ISSUE TITLE
Some regional variants have the wrong abilities

### ISSUE THREAD

**Issue by salomelon** [Pokecube-Development/Pokecube-Issues-and-Wiki#613]
#### What happens: Alolan vulpix has Flash fire and Drought as its abilities instead of Snow cloak and Snow warning, while Alolan sandshrew has Sand veil and Sand rush instead of Snow cloak and Slush rush. Screenshots below
![2021-01-25_23 26 44](https://user-images.githubusercontent.com/77856356/105793324-acc82480-5f67-11eb-8d2b-4437f8b57db7.png)
![2021-01-25_23 26 52](https://user-images.githubusercontent.com/77856356/105793330-ae91e800-5f67-11eb-89f8-082860ab6b42.png)

#### Steps to reproduce:

1. Catch/breed one of the pokémobs mentioned here.
2. Check their ability using your pokéwatch.

____
#### Affected Versions

- Pokecube AIO: 3.7.0
- Minecraft: 1.16.4
- Forge: 31.1.4
 
Extra mods:
- Optifine 1.16.4 HD U G6
- CreativeCore v2.0.10
- ItemPhysic v1.4.14
- InventoryHotswap 1.2
- FindMe 2.1.0.0
- Appleskin 1.0.14
- Offlineskins v1
- Xaero's world map 1.11.9
- Xaero's minimap 21.1.0
- Mousetweaks 2.13
- Just Enough Items 7.6.1.65

**Comment by Thutmose** [comment]
This may be fixed in 3.8.0, can you confirm and check?
