### ISSUE TITLE
Pokémobs sometimes only have a single move

### ISSUE THREAD

**Issue by salomelon** [Pokecube-Development/Pokecube-Issues-and-Wiki#614]
#### Steps to reproduce:

1.Catch/breed a random pokémob
2.Check its moveset
3.Repeat if it has more than one move

____
#### Affected Versions

-Affected Versions
-Pokecube AIO: 3.7.0
-Minecraft: 1.16.4
-Forge: 31.1.4

Extra mods:

-Optifine 1.16.4 HD U G6
-CreativeCore v2.0.10
-ItemPhysic v1.4.14
-InventoryHotswap 1.2
-FindMe 2.1.0.0
-Appleskin 1.0.14
-Offlineskins v1
-Xaero's world map 1.11.9
-Xaero's minimap 21.1.0
-Mousetweaks 2.13
-Just Enough Items 7.6.1.65

**Comment by Thutmose** [comment]
I don't see this as being a problem, some pokemobs only start with 1 move...
