### ISSUE TITLE
Galarian Zapdos

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#624]
#### Issue Description:
Galarian Zapdos flying

#### What happens:
Bug on code make G Zapdos can fly

#### What you expected to happen:
G Zapdos only can run like a chocobo 

#### Steps to reproduce:

1.Mount on a G Zapdos
2.start Flying

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
isn't a "Bug on code", is more of a "not listed as a not-flying flying type"

by default anything that is "flying type" is marked as able to fly, unless blacklisted.

I can see about adding it to the blacklist

**Comment by Thutmose** [comment]
fixed in 3.8.1 ^
