### ISSUE TITLE
Pokémobs don't gather

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#625]
#### Issue Description:
Pokémobs on farms(potato, carrot, wheat, etc...) don't gather anymore

#### What happens:
The Pokémobs on farm stop collect the crops and store the items

#### What you expected to happen:
Pokémobs farm normally collecting the crops and store this things

#### Steps to reproduce:

1. Put your pokemob on a farm and enable the gather and store, and put then on stay
2.The pokémobs collect the itens on ground but don't collect the crops
![2021-02-07_20 18 21](https://user-images.githubusercontent.com/52356643/107161297-8f895200-697a-11eb-8170-1643d4bf9981.png)
![2021-02-07_20 18 24](https://user-images.githubusercontent.com/52356643/107161298-90ba7f00-697a-11eb-876e-a42aa5c878c5.png)
![2021-02-07_20 18 28](https://user-images.githubusercontent.com/52356643/107161300-91531580-697a-11eb-9df5-20368faedd93.png)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:
- Minecraft: 1.15.2
- Forge: 31.1.18

**Comment by Thutmose** [comment]
try it without a combee, the bee might be more interested in polinating the crops than picking them

**Comment by deathxf** [comment]
I already test this, but no one pokemon collect the crops, i use teddiursa but still no collect the crops 
![2021-02-07_21 07 36](https://user-images.githubusercontent.com/52356643/107162184-45a36a80-6980-11eb-839a-98b70739772e.png)
![2021-02-07_21 07 20](https://user-images.githubusercontent.com/52356643/107162187-4805c480-6980-11eb-9495-0a0f41b4c1fd.png)
![2021-02-07_21 07 28](https://user-images.githubusercontent.com/52356643/107162189-489e5b00-6980-11eb-914d-4982879af781.png)
![2021-02-07_21 07 31](https://user-images.githubusercontent.com/52356643/107162190-4936f180-6980-11eb-8a4a-ea96631ae1f7.png)
![2021-02-07_21 07 34](https://user-images.githubusercontent.com/52356643/107162192-49cf8800-6980-11eb-9f2f-d9315cedc4c5.png)

**Comment by deathxf** [comment]
ST of combees
![2021-02-07_21 13 21](https://user-images.githubusercontent.com/52356643/107162292-dd08bd80-6980-11eb-9714-c25c918564e9.png)
