### ISSUE TITLE
Oricorio does not give EXP to Pokemobs when defeated

### ISSUE THREAD

**Issue by ursatomic** [Pokecube-Development/Pokecube-Issues-and-Wiki#631]
#### Issue Description:
Defeating a wild Oricorio does not award your Pokemon with any EXP.

*I found this issue while testing my modpack, but made a new profile with only Pokecube installed and replicated the bug.

#### What happens:
Once you defeat an Oricorio (any form), EXP is not granted to the Pokemon that killed it.

#### What you expected to happen:
Oricorio should award EXP like any other Pokemon.

#### Steps to reproduce:

1.Check EXP of tamed Pokemob
2.Defeat Oricorio with that tamed Pokemob
3.Check EXP of tamed Pokemob again; it does not go up

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.16.4-3.8.0
- Minecraft: 1.16.1
- Forge: 36.0.15

**Comment by Thutmose** [comment]
ahh, right, I think the auto-updater didn't apply the exp yield to them properly, I will look into this
