### ISSUE TITLE
Pokemobs Not Gaining Moves Appropriately

### ISSUE THREAD

**Issue by ursatomic** [Pokecube-Development/Pokecube-Issues-and-Wiki#633]
#### Issue Description:
I noticed while testing my modpack that my pokemobs didn't seem to be learning moves at all, and a lot of the time I'd wind up with pokemobs that only know tackle or scratch which made fights frustrating and encountering ghost pokemobs impossible.

I tested this again on another profile with only Pokecube installed and ran into the same issues.

How I tested:
I started by spawning and capturing level 5 Chimchar, Snivy, Totodile, Grookey, and Charmander.
I set exp scale factor to 20 for this test.
I spawned a bunch of Magikarp and sent out the pokemobs one at a time to go wild on them all.

Results:
Chimchar only knew Tackle until evolved into Monferno; then he learned Mach Punch (After evolve animation)
Monferno gained Close Combat after evolving into Infernape (after evolve animation)
Snivy evolved to Servine then Serperior without learning any moves; only knows Tackle at lvl 38
Totodile evolved to Croconaw then Feraligatr without learning any moves; only knows Tackle at lvl 31
Charmander evolved to Charmeleon without learning any moves
Charmeleon evolved to Charizard and learned Wing Attack (After evolve animation)
Grookey learned Taunt and Branch Poke and Razor Leaf by leveling.
Grookey evolved to Thwackey at 16, and at some point evolved to Rillaboom.
Rillaboom gained Double Hit at some point, according to the Pokewatch when you look up his moves.
I tested Grookey twice- Oddly enough one Rillaboom learned Double Hit, the other learned Screech.
At 55, my second Rillaboom has the moves Scratch, Taunt, Branch Poke, Razor Leaf, and can learn Double Hit.
At 41, my first Rillaboom has the moves Scratch, Taunt, Branch Poke, Razor Leaf, and can learn Screech.6

#### What happens:
Pokemob don't seem to always be learning moves as they level up, but sometimes they do, and sometimes when they evolve.

#### What you expected to happen:
Pokemobs should be learning moves like water gun, ember, etc, earlier on.

#### Steps to reproduce:

1.Level up Pokemobs through combat (it is unclear which mobs or moves this issue effects)

____

- Pokecube AIO: 1.16.4-3.8.0
- Minecraft: 1.16.5
- Forge: 36.0.15

**Comment by Thutmose** [comment]
try updating to 3.9.1+

**Comment by ursatomic** [comment]
That seems to have worked! Pokemobs are getting their abilities again. Thanks!
