### ISSUE TITLE
Crash: Cyclic causes a NullPointerException while trying to capture an NPC on the client side

### ISSUE THREAD

**Issue by hairlessOrphan** [Pokecube-Development/Pokecube-Issues-and-Wiki#636]
#### Issue Description:
Using any mob pickup tools from other mods on a non-monster NPC causes a NullPointerException thrown from pokecube while serializing NBT.

#### What happens:
Using a tool that picks up NPC's (ex: Monster Ball from Cyclic, Mob Imprisonment Tool from Industrial Foregoing) on non-monster NPC's (possibly any NPC that could be considered a trainer?) causes a crash. This happens on any NPC's (villagers, MineColonies colonists, wandering traders, etc...)

#### What you expected to happen:
The tool to pick up the NPC, no crash.

#### Steps to reproduce:
1. Make a Monster Ball from Cyclic
2. Throw it at an NPC (target empty space, hold RMB to charge the throw, point at NPC, release RMB)
3. Observe crash

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
- Pokecube AIO: 3.9.1
- Minecraft: 1.16.4
- Forge: 35.1.37

[crash-2021-02-11_02.25.34-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/5963586/crash-2021-02-11_02.25.34-client.txt)

**Comment by Thutmose** [comment]
There may be further issues occuring, that mod should probably do checks on its side for if whatever it is doing will work.

I can however fix what is causing this particular crash, but I cannot confirm if the fix will work for all cases

**Comment by Thutmose** [comment]
Specifically, Cyclic shouldn't be trying to serialize this to NBT on the client side, it should be doing it server side
