### ISSUE TITLE
The pokecube_common.toml file is missing some config parameter

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#637]
#### Issue Description:
I've noticed that some config are not saving, and doesn't get saved after quitting the game. The problem is that pokecube_common doesn't have them. I've counted 239 parameter listed with /pokesettings and only 168 in the file (using ctrl+f and searching for " = "). Also the parameter change properly, it just doesn't save. Example of missing parameter inlcude : attackCooldown, scaleFactor, flySpeedFactor, groundSpeedFactor and surfSpeedFactor.

#### What happens:
Some config parameter are missing from pokecube_common.toml and doesn't save.

#### What you expected to happen:
The config parameter are saved properly after quitting the game.

#### Steps to reproduce:

1.Use /pokesettings attackCooldown 30
2.Quit the game and lauch it again
3.attackCooldown is now set to the default 20
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:3.9.1
- Minecraft: 1.16.5
- Forge: 36.0.15

**Comment by CorentG** [comment]
I may have misunderstood something. Are config parameter saved per world now? I have set attackCooldown to 12 on one world and it saved after quitting, but creating a new world put the default 20. If that behavior is normal, close this issue. Doesn't explain why aiDisableDistance carry on every world though.

**Comment by Thutmose** [comment]
some configs are saved in pokecube-server.toml, which is per world, I think it gets copied there from the one not in the world though when you make a new one

Some of the other configs are in pokecube-client.toml

**Comment by CorentG** [comment]
Ah, that correct. I didnt knew that change was made, thanks !

**Comment by CorentG** [comment]
I closed that issue too hastly. Even after changing the pokecube-server.toml from the config file, the new worlds doesn't copy it. It's still the default one. attackCooldown for example is still set to default when creating a new world. But the other configs works fine.

**Comment by Thutmose** [comment]
hmm, I can look into where you need to put the configs for them to transfer over, I have seen some modpacks use a  "default-configs" folder, but I am not sure if that is added by some mod

**Comment by Thutmose** [comment]
seems it is the `defaultconfigs` folder, try putting the modified -server.toml files in there, see if those apply to your newly made worlds?

**Comment by CorentG** [comment]
I didn't knew this folder existed, putting the file in here does indeed apply to newly generated world, thanks
