### ISSUE TITLE
Question about the starting Professor

### ISSUE THREAD

**Issue by Davidwhatsit** [Pokecube-Development/Pokecube-Issues-and-Wiki#642]
I decided to reconstruct Prof. Oaks Lab, and I used the location linker to send the starting professor to hang out there instead of the pokemon center.

All was well for a couple minecraft days in creative mode, but then the Professor stops showing up.

Is there a way to respawn or summon him back? 

Thanks! 
David

- Pokecube AIO
- Minecraft: 1.16.5/4
- Forge: 0.167.2.4
Vanilla Tweaks

**Comment by Davidwhatsit** [comment]
To clarify, I cannot find the professor anywhere now.

**Comment by Thutmose** [comment]
Someone mentioned an issue with the professor going missing earlier, they claimed it despawned, but it shouldnt... I will look into what is happening.

To get him back, you can use the trainer spawning/editing gui. In the control screen, find "Trainer Editor", and then set a hotkey for that. Then stand where you want the professor to be, and press the hotkey. there should then be some buttons you can use to change the type of the npc, press those until it says "professor", and then press "spawn npc". That should spawn in a new professor.

If you then look at the professor and click the hotkey again, it should bring up a page for editing him, click on the AI button, then click Invulnerable, that should mark him as unable to be killed

**Comment by Thutmose** [comment]
Further inspection, I think it might have died after being attacked by something? They tend to wander off to go to sleep at night, and zombies like to attack them. I suspect, if they are not flagged as invulnerable, then they will be killed by them.

I did also make a change recently to prevent your players from killing them via snag cubes.

I suggest respawning him, then using the button here: https://pokecube.readthedocs.io/en/latest/trainers/trainer_editor.html#editing-ai to make him invulnerable, that should prevent this from happening again. That page also has instructions on how to spawn him in

**Comment by Davidwhatsit** [comment]
Interesting! I gave him a bedroom so not sure why he left the "lab" at all, but hey! That is great to know, and thank you so much for looking into this and letting me in on how to respawn these guys and use the trainer editor. This is legit my favorite mod of any game ever now. 

Take care,
David
