### ISSUE TITLE
Only pokemobs that are cow/goats/sheep should be milkable 

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#643]
**Is your feature request related to a problem? Please describe.**
It's nitpicky , but I really don't like that EVERY mammals pokemons are milkable, and I think it should not be that way. First of all, it doesn't feel right to milk a rat, a cat, a dog etc. And, from a gameplay perspective, milk is mostly useless, cakes aren't useful and removing potions effects is very niche, and as such it's abondance isn't justified. The removal of that feature for pokemons that aren't based of traditionally milkable animals will have no effect whatsoever on how the mod is played. I know that I can just not use this feature, but the fact that it's even there is bothering me. And even then, 3 to 4 milkable pokemon will still be way more than enough to get milk (i mean, look at the minecraft cow). It would also be more intuitive.
 
**Describe the solution you'd like**
Make milkable only those pokemons : 
-Miltank (obviously)
-Gogoat
-Dubwool

**Describe alternatives you've considered**
I'm pretty sure that it's already possible to customized who give milk, but that doesn't interest me, as i would like the base mod to not have this.

**Additional context**

**Comment by Thutmose** [comment]
make a datapack for that if you want

**Comment by Thutmose** [comment]
specifically, make one which overrides the `pokemobs_interacts.json`, here:  
https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/1.16/src/main/resources/data/pokecube_mobs/database/pokemobs/pokemobs_interacts.json

and remove the milking entries that you don't want

**Comment by CorentG** [comment]
I already knew it was possible, and just would've liked if the base mod didn't have that. But it's a silly/nitpicky request so i don't care that much.
