### ISSUE TITLE
Hoopa's Hyperspace Hole isn't working

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#645]
#### Issue Description:
Hoopa can't create portals

#### What happens:
When you use Hyperspace Hole, it doesn't create a mirage spot

#### What you expected to happen:
When you use Hyperspace Hole with Hoopa, it should create a Mirage Spot, as it used to do

#### Steps to reproduce:

1.Send Hoopa
2.Use Hyperspace Hole 
3.Nothing Happens
...

____
#### Affected Versions

- Pokecube AIO:3.9.1
- Minecraft: 1.16.4
- Forge: 31.1.18

**Comment by Thutmose** [comment]
it works in my testing setup, maybe the server configs are currently disabling it? or are there repels near where you tried?

**Comment by Thutmose** [comment]
this was due to the world reset, and the mob was waiting on cooldown, fixed by manually removing the nbt tag for the reuse delay
