### ISSUE TITLE
Pokemobs should have Horse AI on ride

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#646]
**Describe the solution you'd like**
Pokemobs ride on land are pretty broken: They are slow, can't jump or you'll lose speed, if you can fly, you will never ride on land, cause its useless to say the least.

**Describe alternatives you've considered**
As Thut are adding vanilla AI's to mobs such like BEEAI to Combees, I think you should add Horse'ai to pokemons on ride, this way, they may be consistent on walk, they can charge the jump, so it would work as horses do and should fix the jumping problem in rides.

**Additional context**
Any pokemon you use will have the exact same speed and the same problems, it may be fixed with speed randomizer just as horses have.

**Comment by Thutmose** [comment]
Ya, I had this planned, not got around to it yet, having the issue here will probably make me more likely to get it done soon though :D
