### ISSUE TITLE
Get lava buckets with camerupt 

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#659]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but I think it would be cool and useful if you could use a bucket in a camerupt to get a lava bucket. He literally have a volcano in his backs.

**Describe the solution you'd like**
Get a lava bucket in camerupt just like you can get a milk bucket in miltank.

**Describe alternatives you've considered**
Camerupt is basically a cow too, so I thought that you could right click with a bucket to get lava and shift right click to get milk.

**Comment by Thutmose** [comment]
this should be already the case, does it not work?

**Comment by Thutmose** [comment]
It currently is set to require a female one though, I will change this one to not caring about gender

**Comment by SasoriS5** [comment]
Death's camerupt is female and he still isn't able to get a lava bucket or
a milk bucket

Em sáb, 27 de fev de 2021 17:19, Thutmose <notifications@github.com>
escreveu:

**Comment by Thutmose** [comment]
Hmm, I will look into this further then, it should have been giving lava, unless mega evolved
