### ISSUE TITLE
[Crash] java.lang.NullPointerException during during the load_registries

### ISSUE THREAD

**Issue by Christof519** [Pokecube-Development/Pokecube-Issues-and-Wiki#660]
#### Issue Description:
Loading Minecraft and letting Pokecube load its registries causes a crash.

#### What happens:
Crash on startup

#### What you expected to happen:
To be able to run Minecraft

#### Steps to reproduce:
1. Start Minecraft
2. Wait for it to finish loading (Pokecube loads its registries when the progress bar is/almost is full)
3. When Minecraft gives you the error, look at the crash report it generates
____
#### Affected Versions:
crash-2021-02-27_15.42.21-fml.txt lines 130-193
Forge Version 36.0.43

#### Crash report + Pokecube's log (in case the log is needed for the full picture of things)
https://gist.github.com/TeamEeveeG/189ec2bd9e8e169cdabf069597f1486e

**Comment by Thutmose** [comment]
are you sure you don't have something corrupted in the unit datapack?

**Comment by Christof519** [comment]
It isn't. I know it isn't because Unit isn't even loaded currently. I was going to load it, but I can't even make it to the title screen, much less the resourcepack selection... unless something happened when I deleted the old one... but I don't know how I'm exactly supposed to reset the registry because the registry reset process was changed somewhere between 1.12.2 and 1.15.2.

**Comment by Thutmose** [comment]
it is clearly listed in the second log you placed there, you need to remove the zip file entirely from where you have it to not load it in

**Comment by Thutmose** [comment]
![image](https://user-images.githubusercontent.com/2363472/109399538-69b7f300-7911-11eb-9c30-36e0cfa2e95c.png)

**Comment by Christof519** [comment]
I suggest adding the user error tag after I say this and close it. This is the result of a bug with Minecraft in general and how it handles resourcepacks. Honestly, I should have seen it coming as it was essentially the bane of my existence back in 1.12, where Minecraft fails to recognize that a pack updated and instead thinks that nothing changed to it, tries to load it, and couldn't find anything because the pack is updated... hence the crash.

**Comment by Thutmose** [comment]
this is actually on pokecube's side, rather than minecraft, pokecube has to load in datapacks like unit before minecraft has loaded in the systems for ordering resource/datapacks
