### ISSUE TITLE
Dying and catching a pokemon

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#68]
#### Issue Description:
Dying and while still in the death screen you will not get the pokemon when you respond

#### Steps to reproduce:

1.get many pokemon to attack you while trying to catch one
2. die while having a pokemon in a ball 
3.have it catch and respawn to find it gone 
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.11.1
- Minecraft: 1.12.2

**Comment by Thutmose** [comment]
This seems to actually be caused by capture completion on the exact tick of death

This might be fixed for the next release, but it isn't an easy one to test.
