### ISSUE TITLE
Battle Bug

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#684]
#### Issue Description:
Battles are bugged at the moment and is pretty annoying.

#### What happens:
 Your pokemon rarely attacks another pokemons, even when you tell them to, sometimes they attack and sometimes they just don't.

#### What you expected to happen:
 Tell my pokemon to attack and he does it.

#### Steps to reproduce:

1.Send your pokemon
2.Tell them to attack a trainer or a wild pokemon
3.They might just don't attack
...

____
#### Affected Versions

- Pokecube AIO:3.11.2
- Minecraft: 1.16.5
- Forge: 31.1.18

**Comment by Thutmose** [comment]
this is probably a result of AI throttling changes, which ideally shouldn't affect combat AI, but maybe it is somewhere...

I will look into this
