### ISSUE TITLE
Saplings don't grow naturally

### ISSUE THREAD

**Issue by WenXin20** [Pokecube-Development/Pokecube-Issues-and-Wiki#687]
#### Issue Description:
- Saplings do not grow

#### What happens:
- Legends saplings do not grow naturally.

#### What you expected to happen:
- For a tree to replace the sapling.

#### Steps to reproduce:

1. Plant sapling
2. Set the random tick speed >300
...

____
#### Affected Versions:

- `Pokecube AIO: v3.11.3`
- `Minecraft: v1.16.5`
- `Forge: v36.0.43`

**Comment by Thutmose** [comment]
hmm, that didn't seem to fix it, I think the properties also need fixing, will check that
