### ISSUE TITLE
model rendering bug on alt

### ISSUE THREAD

**Issue by gliched1** [Pokecube-Development/Pokecube-Issues-and-Wiki#689]
#### Issue Description:
after a while of playing, pressing alt to render mons in balls does not work properly-ive finally tracked down at least a reason for it

#### What happens:
after a mon is sent out and dies-such as from a lv20 raticate using cut and dying instantly on a dark oak tree-pressing alt to check whats in the ball shows the model of the ball in an earlier slot in your inv rather then its own, or if none, becomes a glitched out texture

#### What you expected to happen:
pressing alt to show the mon in the ball

#### Steps to reproduce:

1. send out a mon to die
2. wait for it to return to its ball
3. press alt, showing an incorrect model
4. moving the ball around in your inv will change the model rendered, healing it will not fix the issue
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.16.5-3.11.1
- Minecraft: 1.16.5
- Forge: .16.5-36.0.46

**Comment by gliched1** [comment]
having a mon out for long enough also seems to trigger the behavior, unknown what could be triggering it there-not just riding at least, not sure exactly how long either
edit: any amount of damage actually seems to be the trigger, irregardless of if it kills

**Comment by Thutmose** [comment]
on my end: 

I send out rat, 
have it cut tree, 
dies from cutting tree, 
returns to inventory (different or same slot)
press alt, see rat in cube

**Comment by gliched1** [comment]
[✔️] AppleSkin-mc1.16.2-forge-1.0.14
  [✔️] architectury-1.3.81-forge
  [✔️] cloth-config-forge-4.1.3
  [✔️] Ding-1.16.3-1.2.0
  [✔️] ferritecore-2.0.3-forge
  [✔️] Hwyla-forge-1.10.11-B78_1.16.2
  [✔️] InventoryHud_1.16.x.forge-3.1.4
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] jei-1.16.4-7.6.0.58
  [✔️] JEIEnchantmentInfo-1.16.4-1.2.1
  [✔️] jeiintegration_1.16.4-6.1.1.11
  [✔️] jei-professions-1.0.0-1.16.4
  [✔️] journeymap-1.16.5-5.7.1b2
  [✔️] JustEnoughResources-1.16.3-0.12.0.100
  [✔️] light-overlay-5.6.1
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] no-potion-offset-1.0.2
  [✔️] overloadedarmorbar-5.1.0
  [✔️] pokecube-aio-1.16.5-3.11.1
  [✔️] randompatches-2.4.4-forge
  [✔️] ShulkerTooltip-1.9.6
  [✔️] SimpleDiscordRichPresence-1.16.4-1.3.5
  [✔️] thutessentials-1.16.4-4.1.4
  [✔️] thuttech-1.16.4-9.1.2
  [✔️] toughnessbar-6.1

full mod list as requested

**Comment by Thutmose** [comment]
Ok, So I can definitely replicate this now, however only in the compiled build, not in development mode, so this one might take a bit longer to fix...

**Comment by Thutmose** [comment]
Can you get this to occur with a minimal number of mods, ideally not optifine?

If we can find a single other mod that results in the issue (besides ones like optifine), then I might be able to get it working in development environment.

**Comment by gliched1** [comment]
frustratingly, the issue is being a bit elusive..just when i think i track it down to one, it slips and isn't there again-it seems to be only triggering with, in this case, toughness bar in conjunction with something else other then pokecube. i can keep looking and testing, but it seems unlikely at best to be narrowed down to a single mod

**Comment by gliched1** [comment]
minimal load that seems to cause the bug (may [likely are] be other combinations):
overloadedarmorbar-5.1.0
journeymap-1.16.5-5.7.1b2
and ofc
pokecube-aio-1.16.5-3.11.1

**Comment by Thutmose** [comment]
I suspect this does not occur anymore, but if you do see it happen, please either request this be re-opened, or make a new issue for it, ideally with screenshots oft he issue
