### ISSUE TITLE
Battle log appearing in the chat box

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#695]
#### Issue Description:
Moves used in combat by Pokemobs are showing in the chat log. This occurs even with a clean install, running no other mods.

#### What happens:
https://i.imgur.com/RVwxSb3.jpeg

#### Steps to reproduce:

1. Launch a new world
2. Punch a Pokemon or wait for them to aggro
3.
... Profit

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.11.4
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by Thutmose** [comment]
can you include some startup logs for the clean install?

it should make some logs in the logs folder:

pokecube.log
thutcore.log
latest.log

**Comment by MarioSMB** [comment]
Sure, here they are:

[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6192801/latest.log)  
[pokecube.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6192803/pokecube.log)  
[thutcore.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6192804/thutcore.log)

**Comment by Thutmose** [comment]
oh, is this when you don't have a pokemob out?

it might end up in chat if you don't have your own pokemob out, as the pokemob handles forwarding the message to the other display info, can you check if that fixes it?

**Comment by MarioSMB** [comment]
Unfortunately, that doesn't seem to be the case: https://i.imgur.com/nFA4b11.jpeg
