### ISSUE TITLE
Option to disable battle log text box

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#696]
**Is your feature request related to a problem? Please describe.**
Utilising screen space in an an unintrusive way is a big part of keeping the experience intuitive to players, who may be overwhelmed by too much happening at once (not to mention obscuring one's vision). The current means of conveying attacks and Pokemob appearances is leaning more on the intrusive side.

**Describe the solution you'd like**
An option to disable the battle log, so that it optionally only displays vital information (trainer challenges) or at the user's choice does not show anything at all.

**Describe alternatives you've considered**
Moves could potentially be shown above the Pokemob's head briefly, adding to the real-time nature of combat in the mod.

**Additional context**
The Pokemon games provide a battle log where it is necessary, as battles are turn-based and players have influence over what occurs in the fight. This is not so much the case in Pokecube, which is more of a beat 'em up starring Pokemon, so this information becomes somewhat redundant.

**Comment by Thutmose** [comment]
you can already disable the battle log, just move it offscreen via `messagePos` in `pokecube-client.toml`
