### ISSUE TITLE
Alternative visual behaviour for the Dig move

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#697]
**Is your feature request related to a problem? Please describe.**
If I'm not mistaken, the current Dig move effect is to simply break blocks below the Pokemob, which is unfortunately very griefer-like. It is true that mob griefing can be disabled, however in most cases the behaviour of such moves is not so intrusive, an alternative for this specific move would be preferable.

**Describe the solution you'd like**
Instead of breaking the block, it would be a unique and cool visual to have the Pokemob burrow into the block and hide in it for a second or two before popping out, somewhat similar to how silverfish behave (and indeed, similar visually to how the Pokemon behave in the core games).  
This would convey the invulnerability of the Pokemob (being hidden inside the ground) in a way that doesn't destroy the terrain.

**Describe alternatives you've considered**

**Additional context**

**Comment by Thutmose** [comment]
dig only removes blocks when used out of combat, not when used in combat.

The block breaking outside of combat is meant for allowing the player to use it to dig holes

**Comment by MarioSMB** [comment]
Pokemobs are randomly digging holes around the world on their own which can leave it looking like an eyesore after a while, but it sounds like Dig isn't the cause of it, so I'll close this issue.

**Comment by Thutmose** [comment]
That would be the nest digging, there should be some configs to disable those, the ones related to "nest"
