### ISSUE TITLE
Option to not spawn Pokemobs close to villages or campfires

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#698]
**Is your feature request related to a problem? Please describe.**
Bases are overrun! There are Pokemobs everywhere from the moment you load the game, fighting eachother and attacking you. This is very overwhelming initially, and hinders base building creativity until one can acquire certain items to prevent it.

**Describe the solution you'd like**
An option to have the Pokemobs not spawn close to village boundaries (or at least, not within a radius of the village bell) and campfires. Villages would effectively act as "towns" to the Pokemobs. Any that are supposed to spawn within those boundaries would of course still do so, similar to how tameable cats can spawn in villages.

**Describe alternatives you've considered**

**Additional context**
In the Pokemon games, the player is relatively safe from attacks when visiting a town, with very few exceptions.

**Comment by Thutmose** [comment]
if you make a datapack where nothing is allowed to spawn in the "village" subbiome, then no mobs will spawn around villages

**Comment by Thutmose** [comment]
Alternately, place repels under your camp fire, or in the villages/towns
