### ISSUE TITLE
Allow Spawning Ratio to Vanilla Ratio Control Bonus Request - Misc Mods control too!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#7]
**Is your feature request related to a problem? Please describe.**

I would like to be able to manage the ratios between Hostile Mobs - Animals and Pokecube Spawn Ratios - As of right now Pokecube Spawn Ratio is overpowering everything else.

**Describe the solution you'd like**
Spawn ratio config. 1 = 100  {} .01 = 1
Allow configuration via commands.

**Describe alternatives you've considered**
Not sure of any.

**Additional context**

**Comment by Thutmose** [comment]
Have you tried increasing the value for spawn rate, and setting the pokemobs to despawn?

Nothing I can conveniently do will "fix" the vanilla spawning, as those mobs follow a more strict cap than pokemobs do.  If you lower the rate that they spawn via configs, and then make them despawn as well, you will be able to get vanilla mobs spawning more commonly.

**Comment by P3rf3ctXZer0** [comment]
Okay.
