### ISSUE TITLE
Data-sync Mixup (possibly error on my part)

### ISSUE THREAD

**Issue by TeamEeveeG** [Pokecube-Development/Pokecube-Issues-and-Wiki#70]
#### Issue Description:
(this may also be because of outdated Forge) the recent data sync crashes Minecraft

#### What happens:
Minecraft crashes when using Pokecube and then continues to do so whenever Minecraft opens.

#### What you expected to happen:
nothing out of the ordinary

#### Steps to reproduce:

1. just play Minecraft with the latest version of Pokecube ((1.12.2) 1.12.3 if this report is being viewed later)

____
#### Affected Versions:

- see crash report (lines 119-166)

### Crash Report (no clue why it shows the report twice):
https://gist.github.com/TeamEeveeG/d0d08c12ae2b52ab22439a4baa054bbf

**Comment by TeamEeveeG** [comment]
Again, this may be my fault I can no longer get Minecraft past the loader, but if I am to fix my error, Minecraft must be stabilized.

**Comment by Thutmose** [comment]
this should be fixed in AIO 1.13.0+
