### ISSUE TITLE
Villager skins for trainers

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#700]
**Is your feature request related to a problem? Please describe.**
Fitting in with the Minecraft theme, it seems odd to have a bunch of human NPCs running around. That role should generally be delegated to players.

**Describe the solution you'd like**
There are wandering traders, villagers with various professions, even illagers... How about trainer villagers!  
There are so many possibilities here, making it difficult to cover them all in a single issue, here's just a few:  
- The badge on the villager could indicate the difficulty of the trainer
- Illager trainers could represent the evil teams (Plasma, Rocket etc)
- Pokecentres would effectively be a job block for nurse villagers
- Professors would be villagers dressed in lab coats (maybe with a job block? Would allow creating one's own village)
- Defeated trainer villagers could throw the reward items towards the player, similar to how regular villagers throw items at the Hero of the Village
- Red would of course be a villager with the iconic red cap
- Trainer villagers could be interacted with by right-clicking to initiate a battle, and if they were beaten recently would simply shake their heads

**Describe alternatives you've considered**

**Additional context**
Understandably, this is a big and possibly controversial change, though I think it would massively improve the vanilla integration and experience with this mod.  
Element Animation created a hilarious spoof that showcases exactly how this could look: https://www.youtube.com/watch?v=-EOpEDmxTDM

**Comment by Thutmose** [comment]
This can relatively easily be done with an add-on mod.

I can see about expanding the npc renderer to allow specifying a custom renderer , which an add-on can use to replace the rendering with a villager like one

**Comment by Thutmose** [comment]
when the npcs were first added, they were villager-like models, but due to the multitude of complaints, they were changed over to player models. The commit mentioned there allows an addon to now replace the renderer for each NPC as they feel like, so you can make an addion that adds a villager renderer for them, then give them that renderer whenever they are added to the world

**Comment by MarioSMB** [comment]
Thank you for the insight, I have since removed this mod so the issue can safely be closed.
