### ISSUE TITLE
Allow setting a minimum size for Pokemobs

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#701]
**Is your feature request related to a problem? Please describe.**
Having spent a full minute trying to punch a Diglett, it's safe to say their sizes (while accurately represented) are a little too small, making it difficult to identify and fight them, and especially difficult to try and capture them.

**Describe the solution you'd like**
It would be nice to have an option in the configuration files to set the minimum size a Pokemob can be, and possibly increase that by default so the smallest a regular Pokemob can be is the size of a vanilla bat.

**Describe alternatives you've considered**
Maybe they could be represented a little less accurately to allow a better gameplay experience in Minecraft, which does not handle tiny mobs very well.

**Additional context**

**Comment by Thutmose** [comment]
have you ever tried hitting a small animal? it doesn't go very well.

I can add configuration options for the existing smallest size limit though, as there already is such a thing in the code, I can see about adding that value to the config files

**Comment by MarioSMB** [comment]
Good game design calls for exceptions to be made in reality - the size would not be a problem if the means of interacting with them was more intuitive (something the main series games like Let's Go addressed), but that is not the case here, so the gameplay experience with smaller Pokemon is quite poor.  
Regardless, I'm glad to see the issue has been somewhat addressed and hope it will benefit future users of the mod. New releases were made so I'm going to assume this is safe to close.
