### ISSUE TITLE
Reduce default Pokemob spawn rates

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#702]
**Is your feature request related to a problem? Please describe.**
By default, the current spawn rate for Pokemobs seems strangely high; the density of mobs is so high infact that attacking one mob generally means being swamped by 6 or 7 others. The sounds from all of these mobs is also near constant.  
While this is an existing configurable option, my suggestion here applies to the default settings.

**Describe the solution you'd like**
Have the default configuration set to maybe a quarter or fifth of the current spawn rate, encouraging some travelling around and not overwhelming players in battles or encounters.

**Describe alternatives you've considered**

**Additional context**
A big part of Pokemon is exploration, going out into the wild and finding the Pokemon that suits you most. Some of this magic is lost by having the Pokemobs spawn so frequently everywhere.

**Comment by Thutmose** [comment]
just lower them via config options
