### ISSUE TITLE
Alternative means of retrieving owned Pokemobs

### ISSUE THREAD

**Issue by MarioSMB** [Pokecube-Development/Pokecube-Issues-and-Wiki#703]
**Is your feature request related to a problem? Please describe.**
Currently an extra keybind is needed (R) which retrieves (all?) Pokemobs, causing them to return to the inventory or PC as a Pokecube item. This keybind is widely used among mods and tends to serve a lot of purposes, and may be considered redundant with this suggestion.

**Describe the solution you'd like**
Instead of needing to press a keybind to retrieve the Pokemob, an empty Pokecube item could remain in the player's inventory, which is bound to the Pokemob. Right-clicking anywhere with this item would return the Pokemob to it, thereby resolving the need for a separate keybind and allowing players to choose exactly which Pokemob is retrieved in an intuitive manner.  
Additionally, dropping the pokecube item or storing it in a chest or PC could automatically retrieve the Pokemob.  
As a side benefit, this would also reflect how Pokemon are retrieved in the Anime.

**Describe alternatives you've considered**

**Additional context**

**Comment by Thutmose** [comment]
You can re-bind the keybind if needed.

R only recalls the selected pokemob, not all of them

**Comment by Travis9x** [comment]
I bind "Attack" to the "Forward" mouse button (button 4), and "Recall" to the "Back" mouse button (button 5).  Left & Right arrow keys cycle between active/out Pokémon, so you can choose who you are giving orders to.  Many inexpensive mice have these extra buttons, so you don't need a fancy gaming setup to make it easy to control your Pokémon.
In any case, like Thut mentioned, you can always remap the controls to other keys, to resolve conflicts with other mods.

**Comment by MarioSMB** [comment]
I see the label requesting the OP to make an addon has been aded here, and since I have removed this mod, that likely will not happen. Understandably this change has been met with resistance, and while I do still believe the pokeball should remain in the player's inventory, there is no case here anymore, so I'm going to close the issue.
