### ISSUE TITLE
new watch crash?

### ISSUE THREAD

**Issue by gliched1** [Pokecube-Development/Pokecube-Issues-and-Wiki#704]
#### Issue Description:
crash to desktop when clicking a button on watch while looking at, in this case, gastly

#### What happens:
game crashes

#### What you expected to happen:
not that

#### Steps to reproduce:

1. look at gastly with watch
2. push button
3. desktop wallpaper 
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

crashlog:
[crash-2021-03-24_14.18.27-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6199673/crash-2021-03-24_14.18.27-client.txt)

**Comment by Thutmose** [comment]
try updating your version of pokecube, see if it works on a more recent one? you are using 3.11.1, the most recent is currently 3.11.4
