### ISSUE TITLE
Legendary summon timers not resetting.

### ISSUE THREAD

**Issue by Praymettin** [Pokecube-Development/Pokecube-Issues-and-Wiki#705]
#### Issue Description:
Legendary summon timers, like Kyogre doesn't reset after the required time as they should.

#### What happens:
After my last summon of Kyogre(which suffocated at the top of the dome by itself) it says "you already summoned Kyogre" when I right click the summoner with the orb. I retried hours, days even weeks(real time) after I first got the message but to no avail.

#### What you expected to happen:
It should have resetted half an hour after Kyogre was summoned, died and not caught.

#### Steps to reproduce:

1.Find the appropriate summoner for Kyogre(or any specific legendary summoners)
2.Summon the pokemob, let it die by itself( in the dome)
3.Try to summon it after the required waiting time to get the message.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.16.4-3.9.1
- Minecraft: 1.16.5
- Forge: 36.0.46
- jei-1.16.4-7.6.1.71
- JustEnoughResources-1.16.4-0.12.0.107
- ferritecore-2.0.3-forge
- journeymap-1.16.5-5.7.1
- randompatches-2.4.4-forge
- shutupexperimentalsettings-1.0.3
- thutessentials-1.16.4-4.1.4
- thuttech-1.16.4-9.1.2

**Comment by Thutmose** [comment]
generally only include "Fix" in the title for a pull request that actually fixes it, the text here only describes the problem, it doesn't include any fixes for it

**Comment by Thutmose** [comment]
this should be fixed, re-open the issue if it occurs again (or make a new issue)
