### ISSUE TITLE
scalefactor in the pokecube-server.toml not working

### ISSUE THREAD

**Issue by Lakitu1** [Pokecube-Development/Pokecube-Issues-and-Wiki#706]
#### Issue Description:
The setting 'scalefactor' in the pokecube-server.toml file in the config folder does not have any effects on Pokémobs ingame.

#### What happens:
No change to Pokémob size

#### What you expected to happen:
Pokémobs to be four times as big, as configured in the file.

#### Steps to reproduce:

1. Change 'scalefactor' in pokecube-server.toml from 1 to 4.
2. Create a new world.
3. Watch Pokémobs spawn.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.11.3
- Minecraft: 1.16.5
- Forge: 36.0.54

**Comment by Thutmose** [comment]
did you move the pokecube-server.toml into the "defaultcofigs" folder before making a new world?
