### ISSUE TITLE
Ridden flying pokemobs turn up and down with the mouse, where it shouldn't

### ISSUE THREAD

**Issue by CorentG** [Pokecube-Development/Pokecube-Issues-and-Wiki#711]
#### Issue Description:
I assume that this is a bug since it wasn't on any changelogs and make flying worse, but ridden pokemobs can now be turned up and down with the mouse, where it used to only turn them left or right, and then use the ctrl and space button to go up and down(those button still works). This change first appeared in version 3.10.1 (when the mod became incompatible with 1.16.4). It's not present in 3.9.5.

#### What happens:
Ridden pokemobs can turn up and down with the mouse, which they souldn't

#### What you expected to happen:
The mouse only make them turn left or right

#### Steps to reproduce:

1.Make a flying pokemob
2.put a saddle
3.look up/down while using the forward button and he goes up/down
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:3.11.4
- Minecraft: 1.16.5
- Forge: 36.0.46

**Comment by Thutmose** [comment]
this is a result of some of the re-arranging to flight code, I can see about maybe adding in some config options to get back the old behaviour though

**Comment by CorentG** [comment]
that would be great, the older flying was more fun imo

**Comment by Thutmose** [comment]
the next update, the `riddenMobsTurnWithLook` will allow you to disable the new behaviour

**Comment by CorentG** [comment]
Thanks !
