### ISSUE TITLE
Crash in inventory with Productive Bees

### ISSUE THREAD

**Issue by Elec0** [Pokecube-Development/Pokecube-Issues-and-Wiki#718]
#### Issue Description:
Client crashes when searching 'Bee' in JEI with Pokecube and Productive Bees installed.

[crash-2021-04-12_16.25.41-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6299836/crash-2021-04-12_16.25.41-client.txt)

It looks like productive bees is trying to do some custom rendering or something with the bees pokecube adds. If we could have an option or something to disable the beehive_inhabitors, or change the contents, that'd be lovely.

#### What happens:
Client crashes unexpectedly .

java.lang.ClassCastException: pokecube.core.entity.pokemobs.GenericPokemob cannot be cast to net.minecraft.entity.passive.BeeEntity
	at cy.jdkdigital.productivebees.integrations.jei.ingredients.BeeIngredient.getCachedEntity(BeeIngredient.java:43) ~[productivebees:1.16.5-0.6.9.8] {re:classloading}

#### What you expected to happen:
No crash

#### Steps to reproduce:

1. Have Pokecube, Productive Bees, and JEI installed
2. Search 'Bee'
3. Observe crash

____
#### Affected Versions:

- Pokecube AIO: 1.16.5-3.11.4
- Productive Bees: 1.16.5-0.6.9.8
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by Thutmose** [comment]
This looks like it might be on their end? any idea why they are trying to cast a pokemob to an EntityBee?

**Comment by Thutmose** [comment]
the `beehive_inhabitors` is an arbitrary entity tag, you can override it with a datapack, it should be able to be any entity in there, as it is an entity type tag, if productive bees is crashing as a result, then they need to fix it on their end

**Comment by Elec0** [comment]
You're right, it's on their end, I'll go ahead and close this.
https://github.com/JDKDigital/productive-bees/issues/183
