### ISSUE TITLE
Unable to change pokemon attacks on a lan server.

### ISSUE THREAD

**Issue by DamondSword2247** [Pokecube-Development/Pokecube-Issues-and-Wiki#72]
#### Issue Description:
When you die after obtaining a pokemon you cant choose its attacks.

#### What happens:
You can't choose a pokemon attack.

#### What you expected to happen:
I'm still able to use my pokemon attacks after I die.

#### Steps to reproduce:

1. Get pokemon.
2. Open your world to Lan and have a friend join.
3. Both you and your friend die
4. Now one of you can't choose pokemon attacks.

____
- Pokecube AIO:1.12.2-1.13.3.jar
- Minecraft: 1.12.2
- Forge: 14.23.5.2836

**Comment by Thutmose** [comment]
I found some bugs in the new sync code that might be related to this, hopefully the next update will fix it, I will post here when it is out so you can test it

**Comment by Thutmose** [comment]
This should be fixed here: https://minecraft.curseforge.com/projects/pokecube-aoi/files/2714681

Please let me know if it is, close the issue if it is fixed.
