### ISSUE TITLE
Pokecube mob's onInitialSpawn is not worldgen safe and will crash

### ISSUE THREAD

**Issue by TelepathicGrunt** [Pokecube-Development/Pokecube-Issues-and-Wiki#721]
There's an issue with the pokemon entitytype's onInitialSpawn method. In it, it attempts to cast to world multiple times which means that when a pokemon tries to spawn during worldgen, worldgenregion tries to be casted to World or ServerWorld and crashes. So pokemon cannot spawn as part of chunk generation or by structure generation. People wont be able to add pokemon to worldgen structure's nbt files to spawn them in certain structures as part of customizing. This should be casted to ISeedReader instead to make pokemon worldgen safe.
![image](https://user-images.githubusercontent.com/40846040/114890826-5be30200-9dd9-11eb-8c78-03146000ebf4.png)

These lines in SpawnCheck's constructor is what will crash. onInitialSpawn should be made safe for worldgen which is why this is an issue. There might be more hidden casting that I haven't seen found. But a quick way to test this is to spawn your mobs using a forge event to spawn during the SpawnReason.CHUNK_GENERATION phase. 
```
this.chunk = ITerrainProvider.getChunk(((World)world).getDimensionKey(), new ChunkPos(location.getPos()));
World w = (ServerWorld)world;
double time = (double)((ServerWorld)world).getDayTime() / 24000.0D;
```

**Comment by Thutmose** [comment]
Pokemobs don't normally spawn during worldgen, they spawn afterwards so that there is time to check things like subbiomes, etc, hence those world casts. I can see about ensuring that they are only cast when there is actually a world, but note that this means some things might not be applied to the newly spawned mobs, such as:

Level
Evolution Rules
etc

**Comment by Thutmose** [comment]
Ok, so I made it so that if the passed in IWorld is not a World, then it will just not do any further processing, this processing was mostly for setting level/evolving/etc, so the mobs will spawn in at lvl 1, but that is probably fine.
