### ISSUE TITLE
World Crashes on Creation (Ticking Entity)

### ISSUE THREAD

**Issue by Ferisia** [Pokecube-Development/Pokecube-Issues-and-Wiki#723]
#### Issue Description:
The World crashes because of a Pokecube ticking entity.

#### What happens:
Upon creating a world the game crashes.

#### What you expected to happen:
The world to run normally.

#### Steps to reproduce:

1. Create a world
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
- Pokecube AIO: 1.16.5-3.11.4
- Minecraft: 1.16.5
- Forge: 36.1.4

Crash Report : https://pastebin.com/et25qUkK

**Comment by Thutmose** [comment]
this is already fixed for the next update :D

**Comment by Thutmose** [comment]
the crash in this case is caused by an interaction between epic fight and pokecube, the problem is on pokecube's side, I have it fixed for next update of pokecube

**Comment by Ferisia** [comment]
Ah, thank you so much for the quick response! I love your mod and wish nothing but the best for it's continued development!
