### ISSUE TITLE
Ditto crashing the server

### ISSUE THREAD

**Issue by nekorayray** [Pokecube-Development/Pokecube-Issues-and-Wiki#732]
#### What happens:
Anytime someone attacks or uses a ditto it crashes the server, and then the attacking pokemob is also deleted when the server restarts.

#### What you expected to happen:
The ditto to use transform and not crash the server.

#### Steps to reproduce:

1. Run the newest version of pokecube
2. attack a ditto
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.16.5-3.12.0.a.jar
- Minecraft: 1.16.5
- Forge: 36.1.4
-  " i would put a list of all the mods i have but there are quite a bit and unless there are specific mods that cause this issue when running together with pokecube i doubt that would be the problem.
- 
[crash-2021-05-05_04.32.41-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/6429080/crash-2021-05-05_04.32.41-server.txt)

**Comment by Thutmose** [comment]
are you sure that is related specifically to transform? the main concern in that crash report is the low ram on the server

**Comment by Thutmose** [comment]
this doesn't seem to be the case anymore, or at least I have not seen it happen, so closing this issue, re-open it if you have a more updated crash report please
