### ISSUE TITLE
incompatibility citadel

### ISSUE THREAD

**Issue by Draverio** [Pokecube-Development/Pokecube-Issues-and-Wiki#744]
Minecraft warn that the datapacks didnt load correctly and cant connect to the world

 Steps to reproduce:

1.put both mods together
2.try to create a new world or to load a old one
...

____
version

- Pokecube AIO: pokecube-aio-1.16.4-3.9.5
- Minecraft: 1.16.4
- Forge: 35.1.37
- Citadel: citadel-1.6.0

**Comment by Thutmose** [comment]
see if this still occurs in 1.18.2, if so, re-make the issue with the logs on startup there please
