### ISSUE TITLE
Conflict with crystal recipes

### ISSUE THREAD

**Issue by SasoriS5** [Pokecube-Development/Pokecube-Issues-and-Wiki#746]
#### Issue Description:
 The recipe for crafting crystal shards using crystal blocks is the same recipe used to craft a crystal button, so it is impossible to craft crystal shards.
![image](https://user-images.githubusercontent.com/65261765/120909921-a7cf5c00-c650-11eb-9d74-82ba5a4b13d6.png)

#### What happens:
 When you try to craft 9 crystal shards using a crystal block, you can only craft a crystal button.

#### What you expected to happen:

Be able to craft crystal shards using a crystal block and probably craft a crystal button using one crystal shard

#### Steps to reproduce:

1.Get a crystal block
2.Put it in a crafting table
3.You can only craft crystal buttons
...

____
####Affected Versions

-Pokecube AIO:3.11.2
-Minecraft: 1.16.5
-Forge: 31.1.18

**Comment by WenXin20** [comment]
Huh, guess we never caught this. In the meantime, there should also be a stonecutter recipe for those, or you could try using the Polymorph mod.

**Comment by Thutmose** [comment]
changed button recipe to this:
![image](https://user-images.githubusercontent.com/2363472/189235575-7a16937f-4c77-48b7-bc77-1b281706b0a1.png)
