### ISSUE TITLE
[1.16.5-3.11.5] Fossil Stone, Ruby Ore, and Sapphire Ore ConfiguredFeatures are not registered

### ISSUE THREAD

**Issue by TelepathicGrunt** [Pokecube-Development/Pokecube-Issues-and-Wiki#747]
Hello! I was running Blame with Pokecube and it found that the Fossil Stone, Ruby Ore, and Sapphire Ore configuredfeatrues weren't registered. This can cause issues where sometimes, unregistered configuredfeatures can nuke registered ones from biomes which causes mod compat issues. 

I have an example of how I register my ConfiguredFeatures that you can look at! You just need to register them any time before BiomeLoadingEvent fires. Once that event fires, it is too late to register the configuredfeature. I like to do my registering in FMLCommonSetupEvent's enqueueWork
https://github.com/TelepathicGrunt/RepurposedStructures/blob/d38d5c96cbdd5cbc38dc1e5399e3ade6e4d826b6/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredFeatures.java#L238

The blame report from the log:
```
-----------------------------------------------------------------------
****************** Blame Report 1.16.5-3.2.2-forge ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

pokecube:fossilstone
pokecube_legends:ruby_ore
pokecube_legends:sapphire_ore

-----------------------------------------------------------------------
```
Full report with the unregistered configuredfeature jsons: https://paste.ee/p/7rllA

I hope this helps!

**Comment by Thutmose** [comment]
Thanks, I will look into this, have been rather busy with other things for the last month or two, so just getting around to it :D

**Comment by Thutmose** [comment]
Ahh,  I see I had this applied for my configured structure features already, but forgot to also do it for the configured features
