### ISSUE TITLE
[1.16.5-3.11.5] Pokecube attempts to find a non-existent nbt file when picking an empty element in villages

### ISSUE THREAD

**Issue by TelepathicGrunt** [Pokecube-Development/Pokecube-Issues-and-Wiki#748]
Got another issue that Blame has found. When entering a Pokecube village, Blame reports that an attempt was made to try and spawn a `"minecraft:empty"` nbt file which doesn't exist. This is actually a common mistake I seen with other developers too but it is an easy fix. The way vanilla specifies empty elements in their structure pool files is they use a special pool entry called `"element_type": "minecraft:empty_pool_element"` instead of doing `"minecraft:empty"` like you would for processors or fallback pool. This way, vanilla never attempts to resolve `"minecraft:empty"` to an nbt file and instead, understands to skip attempting to place a pick when that special element is picked.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/d38d5c96cbdd5cbc38dc1e5399e3ade6e4d826b6/src/main/resources/data/repurposed_structures/worldgen/template_pool/village/birch/houses.json#L329-L334

Hopefully this helps!

```
[08:10:56] [Worker-Main-19/ERROR] [co.te.bl.Blame/]: 
****************** Blame Report 1.16.5-3.2.2-forge ******************

 Failed to load structure nbt file from:  minecraft:empty
 The path represented by this is:  data/minecraft/structures/empty.nbt
 The calling Template Pool is: pokecube:village/plains/houses
 Most common cause is that there is a typo in this path to the nbt file.
 Please let the mod author know about this so they can double check to make sure the path is correct.
 A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.
 ```

**Comment by Thutmose** [comment]
so it test the fix for this ones, I should install blame, then go spawn in a village and see if I get this message?

**Comment by TelepathicGrunt** [comment]
Yeah. I would teleport to three villages and check the latest.log file. if no blame report shows up, then it is good!
