### ISSUE TITLE
Inconsistency on breeding related tags

### ISSUE THREAD

**Issue by etrotta** [Pokecube-Development/Pokecube-Issues-and-Wiki#752]
#### Issue Description:
1) Fomantis is spelled Formantis in the [leaf species tag](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/c8cb235a095d206d842681874f01f3fcdc4d9901/src/main/resources/data/pokecube/tags/pokemob_egg_groups/leaf.json#L10)
2) Melmetal is not treated as a legendary and is able to breed, but is not included in any Species tags

#### What happens:
Both are still able to breed because of other checks, but the code is still inconsistent when compared to all other pokemobs

#### What you expected to happen:
1) Fomantis to be correctly written as Fomantis
(Proof of the correct spelling: [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Fomantis_(Pok%C3%A9mon)), [Pokemobs Pokedex](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/c8cb235a095d206d842681874f01f3fcdc4d9901/src/main/resources/data/pokecube_mobs/database/pokemobs/pokemobs_pokedex.json#L41051))
2) Melmetal to be included in some species tag, such as [Steel (Meltan's)](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/c8cb235a095d206d842681874f01f3fcdc4d9901/src/main/resources/data/pokecube/tags/pokemob_egg_groups/steel.json) or [Magnet (Magnemite line)](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/c8cb235a095d206d842681874f01f3fcdc4d9901/src/main/resources/data/pokecube/tags/pokemob_egg_groups/magnet.json)

#### Steps to reproduce:

1) Check the [file](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/blob/c8cb235a095d206d842681874f01f3fcdc4d9901/src/main/resources/data/pokecube/tags/pokemob_egg_groups/leaf.json#L10)
2) Melmetal is nowhere to be found in the groups

#### Affected Versions

- Pokecube AIO: 3.31.5 / 3.32.0
- Minecraft: 1.16.5

**Comment by Thutmose** [comment]
this appears to be fixed in newer versions
