### ISSUE TITLE
Add config to change cooldown of moves

### ISSUE THREAD

**Issue by Cwunkie** [Pokecube-Development/Pokecube-Issues-and-Wiki#755]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when a porygon spams recover and I cant kill it

**Describe the solution you'd like**
A config to change the cooldown of either individual moves or for self healing or protecting moves

**Describe alternatives you've considered**
allowing a Pokémon to use "struggle" if it only can use its heal move

**Additional context**
N/A

**Comment by Thutmose** [comment]
Hmm, I will need to decide on how best to implement this, ideally it would be via a custom cooldown scaling per move, or maybe per type of move, though will take some thinking as to what would be the best way to make it configurable

**Comment by Thutmose** [comment]
datapacks can now specifiy cooldown per move, with the `cooldown_scale` option, which takes a floating point number, where `1.0` is the default, and it scales based on that
