### ISSUE TITLE
MC 1.12.2 / PC 3.36.0 / Stunky line does not learn Venoshock

### ISSUE THREAD

**Issue by Travis9x** [Pokecube-Development/Pokecube-Issues-and-Wiki#757]
#### Issue Description:
As of Generation VIII, the Stunky evolutionary line is supposed to learn the move Venoshock at lvl 21 (Skuntank also still learns it at this same level).  But in the Pokécube mod, the Stunky line does not learn Venoshock at any level.

#### What happens:
The Stunky evolutionary line cannot learn Venoshock by leveling.

#### What you expected to happen:
Stunky and/or Skuntank should learn Venoshock at lvl 21.

#### Steps to reproduce:
1.  Capture a Stunky or a Skuntank, prior to lvl 21
2.  Train it until it levels to 21 or higher.
3.  Check the available moves that it can or should learn
4.  Check TMs that could be made with Stunky/Skuntank in a PC box
5.  Notice that Venoshock is nowhere to be found

____
#### Affected Versions:
- Pokecube AIO:  1.18.2  (part of Pokécube Pack 3.36.0)
- Minecraft:  1.12.2
- Forge:  14.23.5.2855

**Comment by Thutmose** [comment]
you should be able to adjust this via the datapack like configs in 1.12.2.

Movesets get updated occasionally, but 1.12.2 is no longer supported anyway
