### ISSUE TITLE
Unable to set Ruins mod structures to sub-biomes other than ruins

### ISSUE THREAD

**Issue by st753m** [Pokecube-Development/Pokecube-Issues-and-Wiki#78]
#### Issue Description:

I am running both Pokecube and AtomicStryker's Ruins Mod.  Ruins is set to create a number of new custom structures gotten from online, including boats, houses, giant tree stumps, and other things that shouldn't use the normal ruins set.  My plan was to change them to register as more suitable sub-biomes.  

I tried adding the names of the ruins to both the  S:structureSubiomes list in pokecube.cfg and pokecube_adventures.cfg, in the same setup that the existing items in those lists have.  My test example:
        GillyShipCaravel:industrial
        GillyShipCargo:testsubbiome

They continue to register as ruins and not industrial and testsubbiome.  I looked in both the F3 view and with the pokewatch.  

#### What you expected to happen:

I expected the ruin called GillyShipCaravel to have industrial sub-biome pokemon, and GillyShipCargo to get the pokemon I marked testsubbiome (100% chance of paras).  Instead, they got the usual "ruins" sub-biome set (unown, mimikyu, etc).  

#### Steps to reproduce:

1. Have Ruins, and a custom structure 
2. Add the structure's name to the configs, with a sub-biome other than ruins set
3. Enter Minecraft, spawn the structure with /testruin (structurename)
4. Look at which sub-biome is listed in F3, and which pokemon appear in the watch.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube-aio-1.12.2-1.13.1
- Minecraft: 1.12.2
- Forge: 14.23.5.2836
- Ruins 1.12.2

**Comment by Thutmose** [comment]
this fix should be out in AIO 1.15.1+, though curseforge is being rather slow at approving the updates, not sure when it will actually be released.
