### ISSUE TITLE
Inventory not displaying after level up

### ISSUE THREAD

**Issue by DigiGlitch** [Pokecube-Development/Pokecube-Issues-and-Wiki#80]
#### Issue Description:
leveling while a pokemob causes the player inventory to not display until clicked.
- The issue only occurs when connected to a server.

#### What happens:
the items disappear in your inventory, they have not been deleted but requires the player to click/pickup one of the items to update the player inventory.

#### What you expected to happen:
When leveling the player inventory updates to display your items properly.

#### Steps to reproduce:

1. turn to a pokeplayer
2. level up while having items in your inventory

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.

- Pokecube AIO: 1.15.5
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by Thutmose** [comment]
this might be fixed, i can't replicate it in my development environment, lets see if it is fixed in 1.15.9

**Comment by TeamEeveeG** [comment]
This used to happen to me, but the items are deleted completely. Bit annoying with NBT items...

I don't know if it is still persistent in 1.15.9 as I haven't used Pokeplayer features in about 3 weeks.

If it does persist however, consider storing important items in Ender Bags/Chests… just in case they actually do get deleted and aren't just hidden (you're lucky).
