### ISSUE TITLE
Mod Conflict, Dragon Survival. Causes server-side crash when the Ender Dragon spawns.

### ISSUE THREAD

**Issue by Wilevar** [Pokecube-Development/Pokecube-Issues-and-Wiki#804]
#### Issue Description:
Unfortunately there's a server-only conflict with Dragon Survival, causing a Ticking World Crash when entering The End, shortly after the ender dragon delivers her first statement.

Through mod removal testing I've confirmed that it's a conflict with Dragon Survival. Remove either this mod or Dragon Survival fixes the crash. I've submited a report to Dragon Survival as well to let them know.

Crash Report:
https://pastebin.com/sv05aVPV

#### Steps to reproduce:
1. Install both mods.
2. Enter the End as a dragon from Dragon Survival.

_____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.12.1
- Minecraft: 1.16.5
- Forge: 36.2.0

**Comment by Thutmose** [comment]
This seems to be something generically wrong with a mob spawn entry, pokecube doesn't add any of those, so most likely not directly related to pokecube.

That being said, the report also doesn't have anything that directly implicates Dragon Survival either

**Comment by Wilevar** [comment]
Troubleshot this with Thutmose over discord and discovered that the crash has to do with a config option for Pokecube that deactivates vanilla monsters and how Dragon Survival reacts to that with the ender dragon. [Link to the other github issue here.](https://github.com/DragonSurvivalTeam/DragonSurvival/issues/58)

**Comment by Thutmose** [comment]
Closing this issue as it appears to be on their side, as mentioned recently on that other issue
