### ISSUE TITLE
Undead Pokemobs

### ISSUE THREAD

**Issue by crtoonmastr** [Pokecube-Development/Pokecube-Issues-and-Wiki#805]
#### Issue Description:
Pokemobs sometimes fail to die correctly

#### What happens:
The Pokemob drops a corpse but is still standing on the field (in addition to the corpse). The mob can regen health, be recalled, etc. as normal, but you can't start any battles with it. You can instruct it to attack a mon (a message will appear confirming this action), but the mons will not fight. Healing your mob will return it to normal.

#### What you expected to happen:
The mob standing on the field is replaced with the corpse and returns to the Pokecube in your pocket with 0 HP 

#### Steps to reproduce:

There may be other ways to trigger this, but I can reproduce it reliably by fighting Wobbuffet with Destiny Bond.

1. Instruct your Pokemob to fight a Wobbuffet, get Destiny Bonded, and kill the Wobbuffet
2. Your Pokemob drops a corpse but stays on the field
3. Try interacting with the mob as usual, observe how it behaves

#### Screenshot:
![2021-09-25_01 07 42](https://user-images.githubusercontent.com/89475507/134759432-716e76b1-4be6-4b78-9cb2-522919541451.png)

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.13.0
- Minecraft: 1.16.5
- Forge: 36.2.0

See screenshot below for my full modlist
![image](https://user-images.githubusercontent.com/89475507/134759410-13151d30-de46-43b4-bf74-48d649ebfd90.png)

**Comment by Thutmose** [comment]
this doesn't currently happen in my dev environemnt, could be related to other fixes I have made however, so I will upload that to the server itself, let me know if this still occurs

**Comment by crtoonmastr** [comment]
~~Still happening for me on the server~~
Never mind, worked after server reboot!

**Comment by crtoonmastr** [comment]
More information: The undead mob cannot target an enemy mon for battle, but if you have it use a move at the ground near the enemy where the move could connect with it, it can still kill enemy mons.
