### ISSUE TITLE
Moves not recharging when loosing target

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#807]
#### Issue Description:
When catching or fighting trainers moves some times like to not recharge after the opponent  has gone out of targeting range or is in a cube or has died and there is a new opponent

#### What happens:
When catching or fighting trainers moves some times like to not recharge after the opponent  has gone out of targeting range or is in a cube or has died and there is a new opponent and causing your pokemob to sit there and do nothing.

#### What you expected to happen:
for moves to recharge even if there is no line of sight with target like say with catching

#### Steps to reproduce:

1.get a tanky pokemob 
2.have it learn a move like hypnosis
3.true to catch a mob with your mob using hypnosis and watch what to the move when the mob is in the ball or has fainted in case of trainer battles
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:3.13.0
- Minecraft: 1.16.5
- Forge: 31.1.18
![2021-09-27_20 34 10](https://user-images.githubusercontent.com/46906554/135003732-1031404c-13ff-463e-ba9c-7f9114d61803.png)

**Comment by Thutmose** [comment]
This may be fixed, somewhat hard to tell as it didn't happen on my end, I am uploading the fix to the server, so test it tomorrow or so (whenever server reboots) and let me know if it still occurs
