### ISSUE TITLE
texture 

### ISSUE THREAD

**Issue by vnct9** [Pokecube-Development/Pokecube-Issues-and-Wiki#811]
#### What happens:
When I change texture pack, the pokemon textures of the pokemon you have(including wild pokemon) disappear

#### What you expected to happen:
When I change texture, pokemon textures still there

#### Steps to reproduce:

1.switch texture pack
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.13.1
- Minecraft: 1.16.5
-Forge: recommended

**Comment by prjohns** [comment]
you should probably include the texture pack you are switching to, so I can test this, also, please include the latest.log file from when this happened

**Comment by vnct9** [comment]
technoblade's texture pack (war v2) to vanilla texture. I think every texture pack.

**Comment by Thutmose** [comment]
I think this has been fixed, but re-make the issue if you see it again please
