### ISSUE TITLE
Server console spams with structure errors after removing mod from game.

### ISSUE THREAD

**Issue by ghost** [Pokecube-Development/Pokecube-Issues-and-Wiki#823]
#### What happens:
The console is spammed with "[minecraft/ChunkSerializer]: Unknown structure start: pokecube:ruins_rigid" and similar messages. 

#### What you expected to happen:
No errors to appear.

#### Steps to reproduce:

1. Delete the mod on an existing world.
2. Check the console.

#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.16.5-3.13.1
- Minecraft: 1.16.5
- Forge: 1.16.5-36.2.8

**Comment by Thutmose** [comment]
this is a "vanilla feature" to let you know that the structures are no longer found, if it occurs after removing the mod, there isn't really much I can do about it...
