### ISSUE TITLE
1.71.1 Alpha: Large pokemon don't have hitboxes?

### ISSUE THREAD

**Issue by Xecotcovach** [Pokecube-Development/Pokecube-Issues-and-Wiki#826]
#### Issue Description:
I was lurking in the Discord channel and noticed someone was having this issue, but I haven't seen it made here yet: Large pokemon don't seem to have hitboxes. Smaller pokemon I can interact with without issues, but pokemon of a certain size I can't do anything to, creating instances of  "immortal pokemon" in wild and trainer battles. 
This is by no means complete but pokemon I have encountered I cannot interact with or attack, but can trigger battle and harm me and my pokemon when they "notice" me:
Anything Dynamaxed
Gyarados 
Tyrantrum (? Trainer battle encounter only, but both instances I've tried, my pokemon cannot do anything to it despite having "projectile" attacks targeting it)
Silvally (Type: Null is fine -- when it evolves, I can't ride or open its menu to feed it anymore)
Mantine 

#### What happens:
I can't initiate battle with wild Gyarados, Dynamax raid pokemon cannot be hit. I can trigger aggro, but my pokemon cannot hit them while they can me.
Silvally cannot be interacted with, but the one I have does "notice" me and tracks me when out of its ball. I go through it,, trying to find its hitbox trigger to feed it. Silvally will attack things when its ball is thrown at targets but I can't ride it anymore where I could when it was a Type: Null.

#### What you expected to happen:
Expected interactivity as with smaller pokemon. Ability to attack and faint dynamax raidmons.  Ability to faint affected trainer mons. Ability to feed my affected mons and ride them.

#### Steps to reproduce:

1. Spawn a Silvally/Gyarados (Two mons that have I've been reliably unable to interact with)
2. Attempt to initiate combat, hit, feed, capture, anything.
...

____
#### Affected Versions (Do *not* use "latest"): 

- Pokecube AIO:
- Minecraft: 1.17.1
- Forge: 37.0.103

Mods: I have a long list of mods, but I am not sure if it would apply with other people having similar issues, but if it's needed, I can provide. 

Thank you for your time and effort!

**Comment by Thutmose** [comment]
See if one of the recent forge updates fixes this? it seems there was a problem on forge's side with multi-part mobs

**Comment by Xecotcovach** [comment]
Updated Forge and checked: everything is corporeal so far! Thanks -- that seemed to do the trick.
