### ISSUE TITLE
1.17.1 LAN Mode / Another people can't join the LAN server.

### ISSUE THREAD

**Issue by ghost** [Pokecube-Development/Pokecube-Issues-and-Wiki#832]
#### What happens:
 Another people can't join the LAN server receiving a message named "Connection Lost: Disconnected".

#### What you expected to happen:
That someone could joing my LAN server.

#### Steps to reproduce:

1. Open a LAN Server with Pokecube Mod.
2. Try to let people join through Radmin VPN
3. Get the error.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.17.1 Release
- Minecraft: 1.17.1
- Forge: 1.17.1 - 37.0.126

Additional:

[message.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7623051/message.txt)
Logs of the error ^^^

**Comment by Thutmose** [comment]
Seems this is actually a forge issue

**Comment by Thutmose** [comment]
Forge has fixed this for the 1.18.1 versions of forge
