### ISSUE TITLE
(1.18.1) latest Pokecube AIO crashing in forge 39.0.7 

### ISSUE THREAD

**Issue by JustHmm** [Pokecube-Development/Pokecube-Issues-and-Wiki#838]
pokecube-aio-1.18.1-3.14.0.e  
Its working in forge 39.0.5 and 39.0.6 but crashing in 39.0.7☆ (with half filled star symbol, whatever it means...)

[crash-2021-12-21_10.08.10-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7750384/crash-2021-12-21_10.08.10-fml.txt)

**Comment by Thutmose** [comment]
yes, forge updated and broke everything, this will be fixed in the next alpha version of the mod, note that this means it won't work with any forge version below 39.0.7

**Comment by Thutmose** [comment]
fixed in pokecube-aio-1.18.1-3.14.0.f
