### ISSUE TITLE
Ticking entity 1.12.2 Forge 2838

### ISSUE THREAD

**Issue by captcookie** [Pokecube-Development/Pokecube-Issues-and-Wiki#84]
https://pastebin.com/rzHLzpPK 
https://pastebin.com/U86pffXJ

After briefly creating a new world on single player, I was running along and the world froze then crashed to the launcher.

#### Steps to reproduce:

I tried a second time to login. When I relaunch and login. It auto-crashes to the launcher.
When I removed all the mods except pokecube, there was not a crash. I thinks its a mod conflict. I will futher investigate.

Pokecube AIO 1.15.7
- Minecraft: 1.12.2
- Forge: 2838

**Comment by Thutmose** [comment]
this is fixed in 1.15.8
