### ISSUE TITLE
[1.18.1] Rendering crash with pokemob egg

### ISSUE THREAD

**Issue by Not-February** [Pokecube-Development/Pokecube-Issues-and-Wiki#842]
This was encountered on loading a world previously used in single player; the client crashed as soon as it loaded completely and this is happening consistently.

I'm not sure what triggered this since I've seen pokemob eggs in the world previously without issue. Maybe a specific kind of egg I hadn't encountered before is causing problems, or an existing egg got messed up? I'm pretty close to a yamper nest where I logged out, and they create eggs quite often.

https://gist.github.com/Febilian/c6acbc92f3e9983cf4115a1b3975ffdd

Forge ``39.0.10``, Pokecube AIO ``3.14.0.i``. I have some other mods installed but those are listed in the crash report.

**Comment by Thutmose** [comment]
See if this is fixed in 3.14.0.j?

**Comment by Not-February** [comment]
Unfortunately not. The crash log is different this time, though.

https://gist.github.com/Febilian/6cf9c49ed5cbf2f937f2b6f391b90364

**Comment by Thutmose** [comment]
interesting, I never had that occur in my testing, I was able to get the previous problem to happen
