### ISSUE TITLE
Can't attack or be attacked by Abomasnow

### ISSUE THREAD

**Issue by Chrisjohnson57387** [Pokecube-Development/Pokecube-Issues-and-Wiki#846]
#### Issue Description:
Can't attack or be attacked by Abomasnow 

#### What happens:
Can't attack or be attacked by Abomasnow and when I spawn one via command, they're instantly owned, unlike say mimikyu
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/8275597/148148754-9c8ff234-a998-4d07-9dc3-db31444625ee.png">

Update: the "caught" Abomasnow can be commanded to attack.

#### What you expected to happen:
Beat up an Abomasnow. Get beaten up by Abomasnow. Fall in love with Abomasnow.

#### Steps to reproduce:
Try to fight an Abomasnow.
____
#### Affected Versions (Do *not* use "latest"):

- Pokecube AIO: 3.14.0.j
- Minecraft: 1.18.1
- Forge: 39.0.9

**Full mod list**
- AdHooks-1.18.1-7.0.0.0-build.0041
- AdLods-1.18.1-5.0.0.0-build.0044
- advancednetherite-1.9.0-1.18
- alexsmobs-1.15.1
- AllTheCompatibility-1.18-(v.1.1.0)
- AllTheCompressed-1.0.1-1.18.1-39.0.8
- alltheores-1.7.5-1.18.1-39.0.0
- appleskin-forge-mc1.18-2.2.0
- appliedenergistics2-10.0.0-beta.3
- Aquaculture-1.18.1-2.3.2
- architectury-3.4.9
- areas_1.18.1-2.9
- ars_nouveau-1.18.1-2.0.2
- artifacts-1.18.1-4.0.2
- Assembly Line-1.18.1-0.3.2-0
- AttributeFix-Forge-1.18.1-13.0.3
- AutoRestart-1.18.1-2.0.0
- awesomedungeon-2.0.2
- Ballistix-1.18.1-0.3.5-1
- balm-2.4.0+0
- Blastcraft-1.18.1-0.2.2-0
- blockui-1.18-0.0.34-ALPHA
- carryon-1.18.1-1.17.0.5
- Chunky-1.2.164
- citadel-1.10.8-1.18
- Cleanse-1.18-7.0.0.0
- cloth-config-6.1.48-forge
- collective-1.18.1-3.8
- comforts-forge-1.18-5.0.0.1
- configured-1.5.1-1.18.1
- CosmeticArmorReworked-1.18.1-v1
- create-mc1.18.1_v0.4b
- CreativeCore_v2.4.1_mc1.18.1
- Cucumber-1.18.1-5.0.2
- curios-forge-1.18.1-5.0.4.2
- CustomStartingGear-1.18.1-2.0.3.1-universal
- dimdungeons-1.13.1-forge-1.18.1
- DoggyTalents-1.18.1-2.4.0
- domum_ornamentum-1.18-1.0.31-ALPHA-universal
- dpanvil-1.18.1-3.2.0
- DungeonCrawl-1.18.1-2.3.6
- dynview-1.18-2.3
- EasyMagic-v3.2.1-1.18.1-Forge
- Electrodynamics-1.18.1-0.5.4-0
- elementalcraft-1.18.1-4.1.6
- enhancedcelestials-2.0.9-1.18
- EnhancedVisuals_v1.4.3_mc1.18.1
- excavation-1.18-1.7
- expandability-5.0.0-forge
- expandedstorage-7.3.6+1.18
- ExplorersCompass-1.18.1-1.1.2-forge
- flywheel-forge-1.18-0.5.0a
- ForgeEndertech-1.18.1-8.0.0.0-build.0040
- geckolib-1.18-forge-3.0.3
- Gobber2-Forge-1.18.1-2.6.10
- goblintraders-1.7.0-1.18.1
- guardvillagers-1.18.1.4.0
- Guide-API-VP-1.18.1-2.2.3-beta.1
- HarderFarther-1.18.1-18.39.0.6
- ImmersiveEngineering-1.18.1-7.1.0-145
- ironfurnaces-1.18.1-3.1.3
- Jade-1.18-4.1.0
- kubejs-create-1801.2.0-build.14
- kubejs-forge-1801.4.0-build.263
- kubejs-immersive-engineering-1801.2.0-build.16
- LibraryFerret-Forge-1.18.1-1.0.2
- LibX-1.18.1-3.1.0
- limitedchunks-1.18-2.1
- mahoutsukai-1.18.1-v1.33.7
- malum-1.18.1-1.1.3
- MCDoom-1.18.1-4.0.1
- mcw-bridges-2.0.1-mc1.18.1
- mcw-doors-1.0.5-mc1.18.1
- mcw-fences-1.0.2-mc1.18.1
- mcw-lights-1.0.2-mc1.18.1
- mcw-paintings-1.0.2-mc1.18.1
- mcw-trapdoors-1.0.4-mc1.18.1
- mcw-windows-2.0.2-mc1.18.1
- minecolonies-1.18.1-1.0.278-RELEASE
- MobileBeacons1.18.1(FORGE)v1.0.0
- MoreVanillaLib-1.18.1-3.0.3
- MouseTweaks-forge-mc1.18-2.21
- multi-piston-1.18-1.2.2-ALPHA
- MysticalAgriculture-1.18.1-5.0.1
- MysticalCustomization-1.18.1-3.0.0
- NaturesCompass-1.18.1-1.9.4-forge
- ninjaphenix-container-library-1.2.10+1.18
- Nuclear Science-1.18.1-0.4.2-0
- occultism-1.18.1-1.24.0
- out_of_sight-1.18.1-1.0.1
- Patchouli-1.18.1-63
- pokecube-aio-1.18.1-3.14.0.j
- polymorph-forge-1.18.1-0.35
- PuzzlesLib-v3.1.3-1.18.1-Forge
- randomvillagenames_1.18.1-1.5
- repurposed_structures_forge-4.1.0+1.18.1
- respawningshulkers_1.18.1-1.7
- rhino-forge-1800.1.7-build.92
- RootsClassic-1.18-1.1.16
- RoughlyEnoughItems-7.1.357
- RoughlyEnoughItems-jei-internals-workaround-7.1.357
- RuneCraft-1.18-(v.3.3.1)
- scannable-1.18.1-forge-1.7.6+da03abb
- setworldspawnpoint_1.18.1-1.9
- sophisticatedbackpacks-1.18.1-3.15.0.494
- SpawnBalanceUtility-1.18.1-1.39.0.11
- spellsword-1-18-1
- structurize-1.18.1-1.0.319-BETA
- swingthroughgrass-1.18.1-1.8.0
- Terralith_v2.0.9_Fabric+Forge
- The_Graveyard_1.1_(FORGE)_for_1.18.1
- tombstone-7.3.2-1.18
- valhelsia_core-1.18.1-0.3.0
- valhelsia_structures-1.18.1-0.1.0
- VampiresNeedUmbrellas-1.18.1-1.0
- Vampirism-1.18.1-1.8.0-alpha+20210102-1316
- VanillaExcavators-1.18.1-4.0.0
- VanillaHammers-1.18.1-4.0.0
- villagebellrecipe_1.18.1-1.4
- villagernames_1.18.1-3.5
- villagertools-1.18-1.0.2
- VTweaks-1.18-3.5.4
- waystones-forge-1.18.1-9.0.1
- weirdmobs-1-18-1
- Xaeros_Minimap_21.23.0_Forge_1.18
- XaerosWorldMap_1.19.0_Forge_1.18

**Comment by Thutmose** [comment]
This looks suspiciously like what was fixed in this commit: <https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/commit/edf629a3e9ed1d7526309f4e44cfc21d291f03c0>, Hopefully it was, if so, this issue can be closed after the next update
