### ISSUE TITLE
New worldgen chunks without NPCs

### ISSUE THREAD

**Issue by Kyaamen** [Pokecube-Development/Pokecube-Issues-and-Wiki#849]
#### Issue Description:
When generating brand new chunks in the world (including ultraspace), NPCs are not spawning in villages or structures. NPCs which had been previously spawned in villages still remain. Affects all NPC types from wandering trainers to stationary ones like N.

#### What happens:
Moving to new chunks, visiting villages or structures that have NPCs do not have them, when pokemobs spawn just fine.

#### What you expected to happen:
NPCs to spawn when I found cool new structures and villages

#### Steps to reproduce:

1. Move to brand new chunks in the world
2. Find places that NPCs/villagers spawn
3. No spawns
...

____
#### Affected Versions: 
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
journeymap-1.16.5-5.7.3.jar
jei-1.16.5-7.7.1.139.jar

- Pokecube AIO: 1.16.5-3.14.0.jar
- Minecraft: 1.16.5
- Forge: 36.2.20

**Comment by Thutmose** [comment]
this should be fixed in 1.16.5-3.14.1, can you confirm and close the issue if it is?
