### ISSUE TITLE
Add a Filter on Pokemobs inventory 

### ISSUE THREAD

**Issue by deathxf** [Pokecube-Development/Pokecube-Issues-and-Wiki#850]
Putting a filter in the pokemons inventory could help a lot when building farm systems, and it could open up the possibility of creating an item distributor system.

The filter system can be something simple, putting a small inventory where you can put a sample of the items you want pokemon to take or ignore, as an example I think of the Sophisticated Backpacks mod, the pickup upgrade where it gives us this small inventory on a tab to sample the items we want or don't want to get.
![download](https://user-images.githubusercontent.com/52356643/148711234-5acfa4af-fdf5-462f-813f-18e8849b2dba.jpg)

**Comment by Thutmose** [comment]
My current implementation of this is as follows:

Make a written book, where the first page has a line that says: `Item Filters:`, followed by lines with either item ids, block ids or tags.

Place this book in the held item slot (books will be added to the list of held items), and then the pokemob will only collect items or blocks that match any of the ids or tags listed.

Example book for pokecube berries:
![image](https://user-images.githubusercontent.com/2363472/148862424-8060cbdb-e6f5-4097-96ba-f55b1fabb926.png)

Example book for only null berries (items and blocks):
![image](https://user-images.githubusercontent.com/2363472/148862453-57c7ee91-7759-4afd-a577-939c82aff006.png)

Presently it does not differentiate items vs tags, it will check if what you put was a tag first, then check if it is an item, it doesn't use the # before the tag name currently.

The books will be used as such: 
![image](https://user-images.githubusercontent.com/2363472/148862536-e167da3c-59ee-443c-afd9-e8aadaab8ef3.png)

**Comment by Thutmose** [comment]
closing this since it has been added, if you want to discus any changes, etc to it, make a discussion inthe discussions section: https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/discussions
