### ISSUE TITLE
[1.18.1] Crash with Biomes O Plenty / TerraBlender

### ISSUE THREAD

**Issue by tovvl** [Pokecube-Development/Pokecube-Issues-and-Wiki#851]
#### Issue Description:
Games crashes either upon generating a new world with Biomes O' Plenty + Terrablender installed or after moving around a bit in the world. There are also no wild pokemon spawns.

#### Steps to reproduce:

1. Create a new world with Pokecube AIO, Biomes O' Plenty, and TerraBlender installed.
2. Attempt to move around in world.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.18.1-3.14.1.jar
- BiomesOPlenty-1.18.1-15.0.0.94-universal.jar
- TerraBlender-forge-1.18.1-1.1.0.31.jar
- Minecraft: 1.18.1
- Forge: 39.0.10

[crash-2022-01-09_20.10.50-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7836812/crash-2022-01-09_20.10.50-server.txt)

**Comment by Thutmose** [comment]
Seems Terrablender makes it crash when you try to check some aspects of terrain in the area, can you also make a crash report on their issue tracker, and then link it to this one?

**Comment by tovvl** [comment]
https://github.com/Glitchfiend/TerraBlender/issues/1
