### ISSUE TITLE
Uncertain Shuckle-related crash

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#854]
I was fighting a group of three low-level (1-5) Shuckle underground myself with a sword to weaken and catch one, but twice in a row a crash has happened that appears to have the same output and seems to be related to a Shuckle, though I don't understand the crash report nor have I been able to tell what specific action is causing it, as it doesn't appear to be immediately after a message of a move or after I hit one.
I'd guess it's an Ability or Move not working correctly causing the crash, but since they are wild Shuckle I don't know what specifically it would be.

What happens:
Crash

What you expected to happen:
Getting a chance to put a weakened Shuckle in an ultra ball

Steps to reproduce: Unknown, I will back up the current state of my world so that if anything from my files would be useful I can send it along.

____
Affected Versions: 
- Pokecube AIO: 3.14.1
- Minecraft: 1.18.1
- Forge: 1.18.1-39.0.9

I have quite a few other mods but the crash report seems to indicate it's a Shuckle-related issue. The full list of mods is in the crash report:
https://pastebin.com/93WhZMKL

**Comment by Thutmose** [comment]
rather than shuckle related, it seems to be terrain move related, probably sticky web or similar used by the shuckle? I will look into fixes
