### ISSUE TITLE
KO'd Pokemon cannot be revived with Revives

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#855]
Issue Description:
A Pokemob in its cube with 0 HP cannot be revived with the Revive item.

What happens:
Placing the revive and the Pokecube in a crafting grid does not show a result to the recipe 

What you expected to happen:
The resulting recipe would be the Pokemob but with half health.

Steps to reproduce:
1. Have a Pokecube with a Pokemob with 0 HP
2. Place it in a crafting grid with a Revive.

Image showing this in inventory crafting grid: https://cdn.discordapp.com/attachments/764654756706254852/930807369485680681/unknown.png
Image showing it in crafting table grid: https://cdn.discordapp.com/attachments/764654756706254852/930807140703170610/unknown.png

The examples are two different fainted Ralts.

____
Affected Versions: Replace with a list of all mods you have in.

- Pokecube AIO: 1.18.1-3.14.1
- Minecraft: 1.18.1
- Forge: 39.0.9

Additional Mods:
-Farmers Delight 1.0.1
-InventorySorter 19.0.0
-More Villagers 3.1.0
-beenfo
-Just Enough Items 9.2.1.69
-Bamboo Everything 1.2.2-build.9
-Flywheel 0.5.1
-Curios 5.0.2.4
-Create v0.4c
-Xaeros_Minimap 21.22.6
-Collective 1.18.1-3.8
-Xaeros World Map 1.18.9
-Comforts 5.0.0.1
-NaturesCompass- 1.9.4
-SereneSeasons 6.0.0.10
-Sophisticated Backpacks 3.12.1.433
-Simple Planes 4.6.3
-Copper Equipment1.18-1.0
-Appleskin 2.2.0
-Chisels & Bits 1.2.73
-Create Crafts & Additions 20220111b

**Comment by Bloodaxe95** [comment]
I'm having this issue as well. I'm also on 1.18.1, Pokécube 3.14.1.
