### ISSUE TITLE
shiny charm dosent work on pokemons

### ISSUE THREAD

**Issue by quakeman00** [Pokecube-Development/Pokecube-Issues-and-Wiki#856]
when using a shiny charm on a pokemon, nothing happens

the pokemon turns shiny

1. aquire a shiny charm
2. use it on a pokemon (i was trying to color a ralts in my case)
3. notice the pokemon dosent changes color

pokecube-aio-1.18.1-3.14.1

- Pokecube AIO:
- Minecraft: 1.18.1
- Forge: 39.0.9

**Comment by Thutmose** [comment]
Try holding shift while using it?
