### ISSUE TITLE
Pokemons Not Loading Properly

### ISSUE THREAD

**Issue by minecraftpokemonthing** [Pokecube-Development/Pokecube-Issues-and-Wiki#858]
#### What happens:
When I throw my Pokémon, it doesn't show the UI on the top left where you can select the moves. It does its own moves and it's as if it's not my Pokémon. It is very hard to pick it up also.

#### What you expected to happen:
I expected it to be like normal where you throw your Pokémon, and you can change the move and pick it up with ease.

#### Steps to reproduce:

1. Throw the Pokémon down
2. Go far away
3. Go back and the UI won't appear

- Pokecube AIO:
- Minecraft: 1.10.2
- Forge: 31.1.18

https://user-images.githubusercontent.com/97645706/149250624-cc24ba5a-1efd-4328-a630-85d5ea519fb2.mp4

**Comment by Thutmose** [comment]
can you try updating to one of the builds for MC 1.16.5 or 1.18.1, and see if it works correctly on those versions?

**Comment by minecraftpokemonthing** [comment]
> 

How do i do that?

**Comment by minecraftpokemonthing** [comment]
> can you try updating to one of the builds for MC 1.16.5 or 1.18.1, and see if it works correctly on those versions?

I have updated the issue, you can now see a video of the magikarp not having the ui
