### ISSUE TITLE
Pokemobs cannot harm Vampirism entities

### ISSUE THREAD

**Issue by Chrisjohnson57387** [Pokecube-Development/Pokecube-Issues-and-Wiki#860]
#### Issue Description:
Pokemobs cannot harm the hunters or vampires from Vampirism

#### What happens:
If you command a pokemon to attack a hunter or a vampire, they just literally do no damage. Your pokemon can be hurt by them though.

#### What you expected to happen:
Death to the hunters!

#### Steps to reproduce:

1. send out pokemon or throw your ball at vampirism mob.
2. Command to attack vampirism mob

- Attacks like ember can create a fire that can hurt the mob a bit, but the pokemon's attack does not affect the vampirism mobs.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.18.1-3.14.2.jar (this has been an issue as long as I've used both in 1.18)
- Minecraft: 1.18.1
- Forge: 39.0.9
- Vampirism-1.18.1-1.8.0-alpha+20210102-1316.jar

**Comment by Thutmose** [comment]
Try disabling the config that protects NPCs from pokemob damage? It is `pokemobsHarmNPCs` in pokecube_adventures-common.toml, I suspect the hunters are NPCs, and thus are protected. Note that disabling this will also let trainers be harmed by pokemobs.

Alternately disable `npcsAreTrainer` in pokecube_adventures-common.toml, that may also fix it (but will prevent npcs from being able to have pokemobs)

**Comment by Chrisjohnson57387** [comment]
Though pokemobsHarmNPCs works, npcsAreTrainer, the cross fire that some npcs are dealing with is rough. So I'm going to leave it disabled. If you ever add a "fuck up these npcs at all times" whitelist, I'll be stoked.
