### ISSUE TITLE
Ball swap feature

### ISSUE THREAD

**Issue by quakeman00** [Pokecube-Development/Pokecube-Issues-and-Wiki#861]
could there be a way to switch the ball a pokemon is in (machine or keybind or function or item, or clicking on a pokemon outside its ball with another ball)

catch a water pokemon with net ball
use "feature" to move the pokemon to a great ball or heavy ball because it looks better

this is purely for cosmetic reasons but sometimes you just dont have the type of ball you want to stuff a rare / legendary pokemon in when you come across them

**Comment by Thutmose** [comment]
try trading the pokemob with the empty cube, it will transfer it over, but you won't recover the old cube

**Comment by Thutmose** [comment]
the trading table feature seems to work fine on my end, so closing this issue
