### ISSUE TITLE
shellos bug?

### ISSUE THREAD

**Issue by Vadewolf** [Pokecube-Development/Pokecube-Issues-and-Wiki#863]
#### Issue Description:
trying to get pink and blue shellos (got tuns of blue but no pink from breeding)

#### What happens:

tried to breed pink shellos but got only blue

#### What you expected to happen:

to get pink shellos out of 15+ breedings

#### Steps to reproduce:

1.breed pink + pink shellos or pink + ditto
2.get egg wait out timer
3.only gives blue shellos
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:1.18.1-3.14.2
- Minecraft: 1.18.1
- Forge: 39.0.7

**Comment by Thutmose** [comment]
seems breeding things defined by custom models/textures rather than entries was not yet implemented, I am looking into ways to get around to this.

**Comment by Thutmose** [comment]
can confirm that breeding shellos works now after the changes in january
