### ISSUE TITLE
Gigantamax doesn't work.

### ISSUE THREAD

**Issue by LdrTylerhiiro** [Pokecube-Development/Pokecube-Issues-and-Wiki#864]
#### Issue Description:
Gigantamax does not work. I tried to gigantamax my Machamp and succeeded, but he instantly reverted back to normal and became smaller than normal. This also happened with my friend's Garbodor. Dynamaxed Pokémobs work normally. Tested in Super Flat world type.

#### What happens:

Gigantamax does not work properly.

#### What you expected to happen:

Expected to gigantamax to work properly and not shrink my Pokémob upon reversal.

#### Steps to reproduce:

1.Use gigant shard on Pokémob capable of gigantamaxing.
2.Gigantamax said Pokémob.
3.Wait for the gigantamax to end.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 1.16.5-3.14.1
- Minecraft: 1.16.5
- Forge: 36.2.20

https://user-images.githubusercontent.com/97923703/149853768-1f52f5b6-cc0d-47e4-a0ad-2a555a7f25fb.mp4

**Comment by Phixaen** [comment]
Having the same problem with Cinderace, it doesn't get smaller afterwards but it does revert back immediately.

Pokecube 1.18.1-3.15.0
Minecraft 1.18.1
Forge 39.0.59

**Comment by Thutmose** [comment]
this appears to be fixed when I fixed some other issues a few versions ago
