### ISSUE TITLE
My datapack doesn't work

### ISSUE THREAD

**Issue by EvaLinn** [Pokecube-Development/Pokecube-Issues-and-Wiki#872]
Hello! I did my best to make a datapack for reducing the spawn of pokemobs but it doesn't work anyway. My version of Minecraft is 1.17.1
[pokecube_spawn.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7920603/pokecube_spawn.zip)
.
![image](https://user-images.githubusercontent.com/83809307/150681451-ae984865-9839-47ae-8499-dd67a9e0edb9.png)

**Comment by Thutmose** [comment]
oh, that particular data system that I sent for the template was for 1.18.1 rather than 1.17, 1.17 used a different data format for the spawns
