### ISSUE TITLE
Crash - 1.18.1 - Possible Animation Engine Issue

### ISSUE THREAD

**Issue by Delta4Phoenix** [Pokecube-Development/Pokecube-Issues-and-Wiki#877]
#### Issue Description:
Crash shortly after entering a world. Apparently something in Ralt's animation breaks it.

#### What happens:
The game crashed.

#### What you expected to happen:
The game to not crash.

#### Steps to reproduce:

1. Create World on 1.18.1 with AIO
2. Spawn in a Jungle
3. Crash

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

In the crashlog.
[crash-2022-01-24_23.28.35-client.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7929297/crash-2022-01-24_23.28.35-client.txt)

**Comment by Thutmose** [comment]
Can you see if you can do anything to make this occur repeatedly? I have had some other people post similar looking crash reports in discord, though none of them actually made a github issue, but I have yet to replicate this crash.

The "simple" fix would be to add a try-catch block or a null-check in a particular part of the animation code, but I would rather not do that, as the animation should never be null in that location anyway, and is never null in any cases where I have tested it.

**Comment by Delta4Phoenix** [comment]
Sadly I did not manage to figure out how to replicate it consistently.... I did get another unrelated crash that I can't really read though..
[crash-2022-01-25_18.33.54-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/7938660/crash-2022-01-25_18.33.54-server.txt)
.

**Comment by Thutmose** [comment]
that second crash is a forge version missmatch, either downgrade forge, or update pokecube

**Comment by Darkfiend009** [comment]
I did some more testing and it doesn't appear to happen because of anything a player is doing or interacting with related to the Pokemon. Unfortunately, because it's not something a player is doing, it makes it next to impossible to replicate with any consistency.

**Comment by Thutmose** [comment]
I suspect this might be fixed with some changes I made to the rendering system for the next release, so I will mark as fixed, if it does re-occur after 3.17.8, make a new issue with the new crash reports.
