### ISSUE TITLE
expand Morpeko

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#883]
#### Issue Description:
Morpeko is growing every time it is withdrawn and sent back out.

#### What happens:
Every time I recall and send out my Morpeko, it grows by 1.

#### What you expected to happen:
Morpeko to stay the same size.

#### Steps to reproduce:

1. Have Morpeko (in my case, caught in Hangry mode)
2. Recall it (may be notable that it switch to Full Belly mode before?)
3. Send it back out.

Alternatively, it does look like just leaving it out and switching from Hangry to Full Belly mode increases its size as well.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.14.2
- Minecraft: 1.18.1
- Forge: 39.0.19

![2022-01-25_02 33 11](https://user-images.githubusercontent.com/90342326/150941729-0edf544e-8c84-42f4-90ca-65bd195674fc.png)

**Comment by Thutmose** [comment]
has this happened with anything other than morpeko? and is it only when it changes form?

**Comment by xigzagoon** [comment]
Morpeko is the only one I have seen it occur with. Recalling and sending it back out when it was in Full Belly Mode also made it grow by 1, without it having to switch forms.

**Comment by Thutmose** [comment]
I think this is fixed, but re-open or make a new issue if you see it occur again
