### ISSUE TITLE
Missing textures in Hideouts

### ISSUE THREAD

**Issue by fieryxx7** [Pokecube-Development/Pokecube-Issues-and-Wiki#888]
#### Issue Description:
The pokecube models that appear in Rocket, Magma, and Aqua hideouts do not show the proper model, instead defaulting to MissingNo.

#### What happens:
Pokedoll models incorrectly displayed

#### What you expected to happen:
I expect the models to show properly, such as the Groudon and Kyorge pokedolls.

#### Steps to reproduce:

1. Find a hideout
2. Find a pokedoll
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.18.1-3.15.0
- Minecraft: 1.18.1
- Forge: 1.18.1-forge-39.0.59

**Comment by Thutmose** [comment]
this should be fixed now in 3.17.x
