### ISSUE TITLE
Datapack doesn't work 1.18.1

### ISSUE THREAD

**Issue by EvaLinn** [Pokecube-Development/Pokecube-Issues-and-Wiki#892]
Datapack for spawning of pokemobs solo, not in groups doesn't work

![image](https://user-images.githubusercontent.com/83809307/152567562-4fcead53-bce5-44e8-b830-b2870ea7edb4.png)

- Pokecube AIO:
- Minecraft: 1.18.1
- Forge: 39.0.59
[Spawn Datapack.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/8004738/Spawn.Datapack.zip)

**Comment by EvaLinn** [comment]
![image](https://user-images.githubusercontent.com/83809307/152568083-51279d30-e953-4959-a4a2-e5d4c49c2171.png)

**Comment by Thutmose** [comment]
[smaller_spawn_groups.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/8006907/smaller_spawn_groups.zip)
this datapack here works just fine for me in the dev environemnt, can you check on your end? if it works there as well, then it is probably an issue with the zip format you used to make it, or maybe something corrupted in a json file?
