### ISSUE TITLE
Crash with Forge 39.0.66

### ISSUE THREAD

**Issue by Darkfiend009** [Pokecube-Development/Pokecube-Issues-and-Wiki#894]
Mod fails to load on the recent Forge version 39.0.66. Appears to be Pokecube Legends.

Crash Report: https://pastebin.com/gWjFuxH3

Seems to be an issue with the changes that Forge regarding trees. This is from the Forge changelog for 39.0.66:

" - 39.0.66 Fix FoliagePlacerType and TreeDecoratorType registry (#8394)"

**Comment by Thutmose** [comment]
yep, forge also has an announcement in their discord that 39.0.66 will break mods that do worldgen stuff, this is fixed for next update
