### ISSUE TITLE
Green->Blue on pokemob info stats

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#896]
In the official Pokemon games, when viewing a Pokemon's stats, the stat raised by the Nature is indicated with red and the stat lowered is indicated with blue.
In Pokecube, the stat raised is still indicated by red, but the stat lowered is indicated by green. 
I think this designation is confusing, because red/green is usually used to mean bad/good or stop/go respectively. If someone wasn't already aware of what stats a nature raised and lowered, they will likely see those colors and think it's the opposite of what it really is.
My suggestion is to change it to match the official games, where the stat lowered by nature would be blue instead.

**Comment by Thutmose** [comment]
This mod uses the original standard. The colours in the official games were swapped in a recent generation

**Comment by Thutmose** [comment]
though, I think it was more of a green-blue, so I guess now it is more apparently blue?

**Comment by xigzagoon** [comment]
would it be possible to add the up arrow next to the increased stat and down arrow next to the decreased one, like in Legends Arceus? In that case, the specific colors would be less important because there'd be another visual marker to clarify.

It also looks like it was blue (or dark teal) as early as HG/SS from gen 4, and the increased stat was actually brown and just looks red against the blue background so that's neat to me :) 
But I wouldn't be surprised if it was something they switched back and forth between, with some games in between HG/SS and the latest ones more clearly using red and green. Though I think the arrows would be the best solution, I also think red/blue is a bit clearer than red/green
![HGSS_status_screen](https://user-images.githubusercontent.com/90342326/152839544-c7b771f2-0b93-4b97-9100-bb5fabdb375e.png)
.

**Comment by Thutmose** [comment]
I went with keeping the colours, but adding arrows as well:
![image](https://user-images.githubusercontent.com/2363472/188335939-b5cd0b77-c25e-4cab-9506-d9c6b7ed2ca8.png)
