### ISSUE TITLE
"Merchant" villagers constantly raise prices

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#897]
#### Issue Description:
Unlike other villager professions, villagers with the "Merchant" profession added by Pokecube that uses the Trading Machine as the workstation constantly raise their prices and only occasionally drop them slightly and temporarily from player villager reputation.

#### What happens:
A Merchant villager that hasn't been interacted with raises their prices constantly and does not drop them back to normal.

#### What you expected to happen:
Merchant villager prices fluctuate with the same mechanics as vanilla villager prices, raising temporarily when they run out of stock or with poor player villager reputation and lowering temporarily with good villager reputation.

#### Steps to reproduce:

1. Have an unemployed Villager interact with an unclaimed Trading Machine, gaining the Merchant profession.
2. Wait. Do not interact with them or any other trading villagers while waiting, so player villager reputation stays neutral.
3. Check the Merchant Villager's trade offers.

____
#### Affected Versions: 

- Pokecube AIO: 1.18.1-3.15.0
- Minecraft: 118.1
- Forge: 1.18.1-39.0.59

**Comment by Thutmose** [comment]
I think this is fixed in 3.17.6, either comment here or make a new issue if it re-occurs
