### ISSUE TITLE
Teleportation Crash - Coherent Villages and Pokecube

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Pokecube-Development/Pokecube-Issues-and-Wiki#9]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

https://1drv.ms/u/s!Au5FVVZYo8FygRp349QHXx1sCdA2

#### What happens:
Created a Dimension and TPD to it. The Game Crashed with Duplicate Ids Table
https://gist.github.com/P3rf3ctXZer0/02d90129ed481e05bbce09d6133f7318

#### What you expected to happen:
Being able to make a dimension.

#### Steps to reproduce:

1. Load game
2. Play Game
3. Make Dimension with /simpledimensions create
4. Create new dimension
5. use command /tpd 30000
6. Crash

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in, if using AIO, list that instead.
- Pokecube AIO: u-pokecube-aio-1.12.2-1.6.22-r.jar
- Minecraft: 1.12.2
- Forge: 1.12.2 - 14.23.4.2765

**Comment by P3rf3ctXZer0** [comment]
https://github.com/TheExceptionist/Coherent-Villages/issues/22

**Comment by Thutmose** [comment]
Disable NPCs being trainers for now, that will temporarily prevent this crash from occuring

**Comment by P3rf3ctXZer0** [comment]
I will see what I can do. Probably tomorrow. Usually if Minecraft devs don't work sameday I test every 24 hours. I will do what I can bro :D

**Comment by P3rf3ctXZer0** [comment]
Fixed in Latest Coherent Villages. Thanks for your time thut.

**Comment by P3rf3ctXZer0** [comment]
not fixed
