### ISSUE TITLE
NPC trainers never want to battle

### ISSUE THREAD

**Issue by xigzagoon** [Pokecube-Development/Pokecube-Issues-and-Wiki#900]
#### Issue Description:
Trainers always give the "[trainer] does not want to battle you right now." message and never battle with me.

#### What happens:
Trainers never start battles with me or anything else, but Villagers will occasionally battle each other. Right-clicking to try to start a battle always gives the message that they do not want to battle right now. I even tried reducing their range to check for trainer crowding and their cooldowns to almost none and the issue persists, so it isn't one of those. I have Pokemobs in my hotbar and have tried sending one out before trying to start a battle to see if they would see that I had a Pokemob that way, and the issue continued.

#### What you expected to happen:
Trainers that see me occasionally battle me, and right clicking a trainer would start a battle.

#### Steps to reproduce:

1. Start a new world (may be significant, as I restarted with the release and do not know if previous trainers would still battle in my old world)
2. Get a Pokemob and put it in your hotbar.
3. Right-click any trainer.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.15.0
- Minecraft: 1.18.1
- Forge: 39.0.59

**Comment by Thutmose** [comment]
are you wearing a belt? if so, try putting a pokemob in it, see if that fixes the trainer agro? I will see about making that also check player inventory when wearing one

**Comment by xigzagoon** [comment]
ah, I was indeed wearing a belt, but it was a belt added by a different mod meant to store tools. filled Pokecubes can go in it but I hadn't been using it for that. Removing it did seem to fix the issue!

**Comment by Thutmose** [comment]
this should be effectively fixerd now
