### ISSUE TITLE
What does it mean if "pokecube_legends did not load properly" ?

### ISSUE THREAD

**Issue by MrTailson** [Pokecube-Development/Pokecube-Issues-and-Wiki#903]
Simply by having the mod installed, I can't get to the main menu. I do not understand what is wrong nor how to replicate it with the only message at the start up being that something called "pokecube_legends" did not load properly. I don't know what it means when something does not load properly or how to fix it.

- Pokecube AIO: 1.18.1 - 3.15
- Minecraft: 1.18.1
- Forge: 39.0.75
[crash-2022-02-10_00.41.05-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/8038687/crash-2022-02-10_00.41.05-fml.txt)

**Comment by Thutmose** [comment]
This is a case of #894

**Comment by MrTailson** [comment]
My bad. Sorry. I did look through to see if this issue had already been established. I didn't recognize it.
