### ISSUE TITLE
Extended Pokedex Descriptions

### ISSUE THREAD

**Issue by DeliWtz** [Pokecube-Development/Pokecube-Issues-and-Wiki#904]
The pokedex loads extended Dex entries from a language file (filled out english one included below) so that translations/extra entries for custom mobs can be added.

Could be game accurate and only show descriptions for discovered mobs, giving incentive to check the Dex as well as more immersion.
Could have extended descriptions be limited to discovered mobs on the watch but always be available on the Dex (to give the Dex some usefulness or something)

[en_us.zip](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/8044770/en_us.zip)

**Comment by DeliWtz** [comment]
comment

**Comment by Thutmose** [comment]
When un-owned:
![image](https://user-images.githubusercontent.com/2363472/188292251-a1f91753-5980-4c3b-b20d-ce7f84c930e2.png)
![image](https://user-images.githubusercontent.com/2363472/188292269-6015a7c7-d2ef-4893-983a-9e2c513f356c.png)

When owned:
![image](https://user-images.githubusercontent.com/2363472/188292280-c7a5c7dc-c900-4042-9baa-b0fae1310873.png)
![image](https://user-images.githubusercontent.com/2363472/188292287-f43865ed-eb3f-417d-8c3b-0002587ff3ed.png)

This will be in 3.17.6
