### ISSUE TITLE
Tons of pokemon not spawning due to diffrent changes with biomes and others

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#907]
#### Issue Description:
Pokemon like deino say they spawn in meadows and other biomes but when going to said biomes it is not on the local spawnlist. Making a cave subiome in said biomes does not fix the problem. some pokemon like latios have wrong biome names so they cant spawn. zubat has inccorect spawn weight so no matter what it will always say 0.0% chance to spawn in the local spawn list.

#### What happens:
see top.

#### What you expected to happen:
for spawns to work normally and not loose the chance to catch pokemon in their natural biomes

#### Steps to reproduce:

1.Head to a meadows or biome that deino can spawn
2.look at local spawn
3.dieno is missing
1. look at latios's spawn location in the dex
2. notice the biome name is misspelt
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:3.15.0
- Minecraft: 1.18.1
- Forge: 39.0.59

**Comment by Thutmose** [comment]
Deino also needs to be in caves, did you try there as well? I suspect that part of this is just a case of #898 where the location description is incomplete.

Mis-spelt spawns however are a problem, can you get a list of them?

**Comment by monkeycrazie** [comment]
![2022-02-20_13 45 41](https://user-images.githubusercontent.com/46906554/154859072-fe2bff5d-63d8-4973-b986-7a49b10cffe4.png)
![2022-02-20_13 45 46](https://user-images.githubusercontent.com/46906554/154859076-7ec91780-0f37-46c3-b344-0936169bf725.png)
![2022-02-20_13 47 01](https://user-images.githubusercontent.com/46906554/154859085-5d0f487f-c4d5-41b8-aca1-70ba87e9a646.png)
![2022-02-20_13 47 47](https://user-images.githubusercontent.com/46906554/154859088-9fe97517-a111-484b-b48f-09bac5a01b0b.png)
![2022-02-20_13 47 51](https://user-images.githubusercontent.com/46906554/154859090-41fd5ee4-1757-4a21-8684-bf235c34bea0.png)
![2022-02-20_13 49 41](https://user-images.githubuserc
![2022-02-20_13 49 44](https://user-images.githubusercontent.com/46906554/154859095-7de01718-e00a-4730-af19-73c75a830d30.png)
ontent.com/46906554/154859094-dfa1a63d-c5ec-4b14-80ad-5db76577fa47.png)

**Comment by monkeycrazie** [comment]
![2022-02-20_13 49 41](https://user-images.githubusercontent.com/46906554/154859153-ae8a3d41-a5da-424b-9e8b-bf0473d10b7f.png)

**Comment by monkeycrazie** [comment]
![2022-02-20_13 54 03](https://user-images.githubusercontent.com/46906554/154859228-5f6191b6-fe5b-4527-94c5-f7667a2dcdc5.png)
one of the pokemon that should spawn on stony shores but is mis spelt

**Comment by monkeycrazie** [comment]
![2022-02-20_13 56 13](https://user-images.githubusercontent.com/46906554/154859314-128e2863-de2b-4847-a0bf-9005f7f7731e.png)
![2022-02-20_13 56 16](https://user-images.githubusercontent.com/46906554/154859318-16d55655-f3ff-4ba0-8c0b-297d3f4fc787.png)

**Comment by monkeycrazie** [comment]
![2022-02-20_13 58 07](https://user-images.githubusercontent.com/46906554/154859407-a3b1ee4e-a31c-4838-9a06-79ade3627e2f.png)
![2022-02-20_13 58 15](https://user-images.githubusercontent.com/46906554/154859412-b5356dad-e9b8-4c8d-b14d-b7b772db2de2.png)

**Comment by monkeycrazie** [comment]
![2022-02-20_13 58 57](https://user-images.githubusercontent.com/46906554/154859442-e21fde20-21f3-452f-be40-660decd78fe9.png)
![2022-02-20_13 59 02](https://user-images.githubusercontent.com/46906554/154859445-49993e5f-e68a-44ed-8c63-5bd9a9932b93.png)

**Comment by monkeycrazie** [comment]
![2022-02-20_14 00 25](https://user-images.githubusercontent.com/46906554/154859514-3687767f-2abd-4481-8d0e-2bf896b0a290.png)
![2022-02-20_14 00 35](https://user-images.githubusercontent.com/46906554/154859518-746680c2-5563-435e-8a25-3253068754b4.png)

**Comment by monkeycrazie** [comment]
also passive mobs still spawn in ultra space

**Comment by monkeycrazie** [comment]
![2022-02-20_14 01 38](https://user-images.githubusercontent.com/46906554/154859563-83355b1b-b9e5-454d-aff4-9cabdd6e557f.png)
![2022-02-20_14 01 46](https://user-images.githubusercontent.com/46906554/154859566-6a33da1e-60d8-4797-9a4b-7beb955c5b18.png)

**Comment by Thutmose** [comment]
this should be fixed after the cleanup i just did on the spawns lists

**Comment by Thutmose** [comment]
or I guess not, time to check things....
