### ISSUE TITLE
no clue

### ISSUE THREAD

**Issue by Vadewolf** [Pokecube-Development/Pokecube-Issues-and-Wiki#908]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

searching JEI for evos
#### What happens:

![2022-02-17_15 22 33](https://user-images.githubusercontent.com/18257282/154573371-987d4bc5-5523-44a6-bdda-b8c0b2cbc3af.png)
![2022-02-17_15 22 52](https://user-images.githubusercontent.com/18257282/154573379-0cbf2246-f9a1-41ee-8089-08dbe7b89cbb.png)
![2022-02-17_15 23 06](https://user-images.githubusercontent.com/18257282/154573387-0bd01295-9188-48aa-b3de-630af0e2412e.png)

#### What you expected to happen:

show the pokemon and evos
#### Steps to reproduce:

1.open JEI
2.@pokecube
3.everything but the actual mons shows
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO:3.16.0
- Minecraft: 1.18.1
- Forge: 39.0.79

**Comment by Thutmose** [comment]
Closing this issue as requested by the first line in it

**Comment by Vadewolf** [comment]
i 100% thought i did it right tho
