### ISSUE TITLE
Crash when loading any single-player world twice, with Thut Essentials

### ISSUE THREAD

**Issue by TimeSourceSheep** [Pokecube-Development/Pokecube-Issues-and-Wiki#910]
#### Steps to reproduce:
0. Have both Thut Essentials and Pokecube AIO installed
1. Create/load any singleplayer world
2. Exit singleplayer world
3. Create/load any(including previously loaded world, previously created world, and new world) singleplayer world
4. Minecraft crashes

Note: Modpack "Pokecube Pack" 6.1.0 is affected. This crash won't happen if one of Thut Essentials or Pokecube AIO is removed.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.16.1
- Thut Essentials: 4.4.1
- Minecraft: 1.18.1
- Forge: 39.0.79
Test Condition: Minecraft 1.18.1, with Forge 39.0.79 installed, with only 2 installed mods mentioned above

[crash-2022-02-18_15.10.50-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/8094593/crash-2022-02-18_15.10.50-server.txt)

**Comment by Thutmose** [comment]
odd, why is forge calling the register perms event twice in that case...

**Comment by Thutmose** [comment]
this should be fixed in modern versions
