### ISSUE TITLE
spawnDimBlacklist config not fully working

### ISSUE THREAD

**Issue by dairymoose** [Pokecube-Development/Pokecube-Issues-and-Wiki#913]
#### Issue Description:
After installing the mod onto a server that did not ever have it, and changing the spawnDimBlacklist config option (prior to the server ever being started) to include "minecraft:overworld", the villagers in my base still had pokemobs spawn around them and some got attacked + the named zombie in the base also died.  

The goal was to start the game with no spawns at all, add repel blocks in creative mode to all existing bases to secure them, then re-enable spawns.  Otherwise when starting, the iron golem farm on my server breaks when the named zombie mob dies immediately.

Similarly, setting mobDensityMultiplier to 0.0 on client + server also still had spawns near the villagers.

Possibly this config option is actually working as intended and a better idea might be a config option to disable all pokemobs entirely (which breaks the mod but could be good to fix issues).

#### What happens:
Pokemon still spawn in the overworld near villagers (in an iron golem farm setup).  This caused villagers to be attacked, the named zombie in the base (trapped in a boat) to die.

#### What you expected to happen:
For a fresh server that never had Pokecube installed, adding the blacklist item would keep that dimension free of ever having any pokemon spawn.

#### Steps to reproduce:

1.  Backup existing server 
2.  Install Pokecube AIO mod on server
2.  Run server
3.  Join server as a client
3.  Stop server
4.  Restore server from backup
5.  Modify newly created configs on server + client and change blacklist config option ->  spawnDimBlacklist = ["minecraft:overworld", "compactmachines:compact_world"]
6.  Run server
7.  Join server as client
8.  Observe that pokemobs still spawn into the overworld if you have villagers near your base (e.g., iron golem farm)
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: pokecube-aio-1.18.1-3.16.1.jar
- Minecraft: 1.18.1
- Forge: 39.0.75
alexsmobs-1.16.0.jar
Aquaculture-1.18.1-2.3.2.jar
architectury-3.4.9.jar
ars_nouveau-1.18.1-2.2.2.jar
artifacts-1.18.1-4.0.2.jar
AutoRegLib-1.7-52.jar
awesomedungeon-2.0.4.jar
balm-2.4.1+0.jar
betteranimalsplus-1.18.1-11.0.3-forge.jar
Beyond-Earth-1.18.1-6.0d.jar
BiomesOPlenty-1.18.1-15.0.0.105-universal.jar
blockui-1.18.1-0.0.43-ALPHA.jar
blue_skies-1.18.1-1.3.3.jar
BowInfinityFix-1.18.x-rv11.jar
Chameleon-1.12-4.1.3.jar
citadel-1.10.8-1.18.jar
cloth-config-6.1.50-forge.jar
configured-1.5.3-1.18.1.jar
create-mc1.18.1_v0.4c.jar
curios-forge-1.18.1-5.0.5.2.jar
CuriosQuarkOBP-1.18.1-1.1.0.jar
doggychunks-1.18.1-1.0.jar
DoggyTalents-1.18.1-2.4.2.jar
domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.jar
DungeonCrawl-1.18.1-2.3.7.jar
DungeonsArise-1.18.1-2.1.49d-beta.jar
DungeonsMod-1.18-1.4.60.jar
Dynmap-3.3-beta-4-forge-1.18.jar
EnigmaticLegacy-2.15.1.jar
expandability-5.0.0-forge.jar
FarmersDelight-1.18.1-1.0.3.jar
ferritecore-4.1.1-forge.jar
flywheel-forge-1.18-0.5.1.jar
forbidden_arcanus-1.18.1-2.0.2.jar
furniture-7.0.0-pre27-1.18.1.jar
geckolib-1.18-forge-3.0.11.jar
hexerei-0.1.14.jar
ImmersiveEngineering-1.18.1-7.1.0-145.jar
ironchest-1.18-13.0.7.jar
jei-1.18.1-9.2.3.84.jar
journeymap-1.18.1-5.8.0beta15.jar
JustEnoughResources-1.18.1-0.13.1.138.jar
kotlinforforge-3.1.0-obf.jar
LibraryFerret-Forge-1.18.1-1.0.3.jar
mahoutsukai-1.18.1-v1.34.0.jar
malum-1.18.1-1.1.3.jar
minecolonies-1.18.1-1.0.439-ALPHA.jar
mna-1.7.0.4.jar
modernlife-1.18.1-1.32.jar
multi-piston-1.18-1.2.2-ALPHA.jar
observable-1.2.3-forge.jar
occultism-1.18.1-1.26.5.jar
Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.8.jar
Patchouli-1.18.1-64.jar
pokecube-aio-1.18.1-3.16.1.jar
polymorph-forge-1.18.1-0.36.jar
Quark-3.0-334.jar
QuarkOddities-1.18.jar
refinedstorage-1.10.0.jar
relics-0.3.4.1.jar
selene-1.18-1.12.0.jar
StorageDrawers-1.18.1-10.1.1.jar
structure_gel-1.18.1-2.1.3.jar
structurize-1.18.1-1.0.346-ALPHA.jar
supplementaries-1.18.1-1.1.9.jar
TerraBlender-forge-1.18.1-1.1.0.73.jar
Terralith_v2.0.12_Fabric+Forge.jar
The_Graveyard_1.4_(FORGE)_for_1.18.1.jar
tinyredstone-1.18-3.1.1.jar
valhelsia_core-1.18.1-0.3.2.jar
waystones-forge-1.18.1-9.0.3.jar
wthit-forge-4.5.1.jar

**Comment by Thutmose** [comment]
Are you sure the issue is not caused by the villagers having pokemobs?

the config seems to work fine in my case. I suggest trying setting `npcsAreTrainers` to false in `pokecube_adventures-common.toml`, then see if that fixes the problem in your case
