### ISSUE TITLE
Custom Professions missing zombie texture

### ISSUE THREAD

**Issue by lunapanshiel** [Pokecube-Development/Pokecube-Issues-and-Wiki#914]
While constructing a server modpack, I noticed that there was a tendency for zombie villagers to spawn with the broken texture pattern from generated spawners and spawn eggs, on closer investigation using F3+i the information reported that they were all assigned the pokecube_adventures:healer profession which shouldn't be spawning as zombies as far as I'm aware.

Versions: 
pokecube-aio-1.18.1-3.16.1
Forge 39.0.79

Info dump from the zombie below:

`/summon minecraft:zombie_villager -4312.28 63.00 2117.51 {Brain: {memories: {}}, HurtByTimestamp: 147, ForgeData: {__i__: 32913998077L}, IsBaby: 0b, Attributes: [{Base: 0.08d, Name: "forge:entity_gravity"}, {Base: 0.23000000417232513d, Name: "minecraft:generic.movement_speed"}, {Base: 0.0d, Modifiers: [{Amount: 0.001854504717075845d, Operation: 0, UUID: [I; 602226262, -1569897741, -1187750676, 46075936], Name: "Random spawn bonus"}], Name: "minecraft:generic.knockback_resistance"}, {Base: 0.021585637847880413d, Name: "minecraft:zombie.spawn_reinforcements"}, {Base: 35.0d, Modifiers: [{Amount: 0.05824509154225101d, Operation: 1, UUID: [I; -749330824, -1593684679, -1389252755, 1812158498], Name: "Random spawn bonus"}], Name: "minecraft:generic.follow_range"}], Invulnerable: 0b, FallFlying: 0b, PortalCooldown: 0, AbsorptionAmount: 0.0f, InWaterTime: -1, FallDistance: 0.0f, CanUpdate: 1b, DeathTime: 0s, Xp: 0, ForgeCaps: {"structure_gel:gel_entity": {portal: "structure_gel:empty"}, "pokecube:affected": [], "pokecube:guardai": {state: 0, tasks: [{d: 2.0f, start: 0L, end: 0L}]}, "thut_wearables:wearables": {0: {type: 0b}, 1: {type: 1b}, 2: {type: 2b}, 3: {type: 3b}, 4: {type: 4b}, 5: {type: 5b}, 6: {type: 6b}, 7: {type: 7b}, 8: {type: 8b}}}, HandDropChances: [0.085f, 0.085f], PersistenceRequired: 0b, ConversionTime: -1, Motion: [0.0d, -0.0784000015258789d, 0.0d], Health: 19.06f, LeftHanded: 0b, Air: 300s, OnGround: 1b, Rotation: [6.574888f, 0.0f], HandItems: [{}, {}], ArmorDropChances: [0.085f, 0.085f, 0.085f, 0.085f], CanBreakDoors: 0b, Fire: -1s, ArmorItems: [{}, {}, {}, {}], CanPickUpLoot: 0b, VillagerData: {profession: "pokecube_adventures:healer", level: 1, type: "minecraft:plains"}, HurtTime: 0s, DrownedConversionTime: -1}`

![2022-02-25_09 13 30](https://user-images.githubusercontent.com/27765468/155729872-c339daca-2f5e-4e05-8a88-08f3387d3b30.png)

**Comment by Thutmose** [comment]
rather than broken, it is missing texture, we need a texture for that profession of zombie, also for trader and professor

**Comment by Thutmose** [comment]
this appears to be fixed in 3.17.6
