### ISSUE TITLE
rotom forms

### ISSUE THREAD

**Issue by ArkSEPlayer** [Pokecube-Development/Pokecube-Issues-and-Wiki#916]
the way we should be able to switch rotoms forms is by, using normal minecraft items/blocks as held items in the inventory, when you put a certain item in a rotoms held item slot, itll change to what ever form corresponds to the item you used, here is a list of items and forms, and if you remove the item from the rotoms held item slot, itll change back to its normal form:

leaf block(any leaf block): lawn mower form

water bucket: washing machine

lava bucket: microwave 

feather: fan 

ice block: refrigerator 

or if you decide to do it where you just click the pokemon with the item, then the item you could use for changing it back to its normal form could be redstone

**Comment by RedRex64** [comment]
Finally was able to reset my password so I can post this.
My idea:

furnace for oven, 
<any> hoe for lawnmower, 
cauldron for Washing machine, 
chest for refrigerator, 
sheers for fan,
then removing the held item will cause the Rotom to de-transform back to normal.
