### ISSUE TITLE
1.18.1 -> 1.18.2 Update?

### ISSUE THREAD

**Issue by Kitteh6660** [Pokecube-Development/Pokecube-Issues-and-Wiki#924]
Currently, the mod doesn't work on 1.18.2. Would it be possible to update it to 1.18.2? I doubt it will take a lot of efforts, just a few things to change.

1.18.2 fixes a lot of bugs too.

**Comment by JustHmm** [comment]
1.18.1 is sadly very outdated. Many good mods like Thermal Expantion, Mekanism are skips 1.18.1 and starts from 1.18.2 and some mods even not properly working in 1.18.1 as they claimed. For example there is only one version available for Flux Network mod (for 1.18.1) and it requires a very high JEI version that doesn't exist for 1.18.1. So you have to choose between JEI and Flux Network. (or maybe it won't even going to work when you remove the JEI, I choosed the JEI over FN ofcourse.) 

Luckly there are still nice mods that has a version for 1.18.1 like Tinkerer's Construct, Create, Immersive Engineering, Extreme Reactors, Ars Magicka, Refined Storage, ProjectE,  Corail Tombstone, FTB Chunk load/claim system with worldmap/minimap  (whatever the names are all of those files) etc.

Looks like Galacticraft and Advanced Rocketry did stuck in 1.12.2 but atleast we have Beyond Earth mod for 1.18.1 and 1.18.2 I'm gonna try and see how it will going to work along with PokeCube mod. 

This is why PokeCube is best pokemon mod ever made. It has flexibility with other mods and Its not turning MC into boring turn based cliche that you constantly wait boring texts and menus.

**Comment by Thutmose** [comment]
the update is in progress, it is quite a lot of things to fix, as 1.18.2 completely changed how several of the internal minecraft features that pokecube used worked. you can see progress via the 1.18.2 branch, currently it compiles, but we are still working on re-adding the worldgen structures.

**Comment by Thutmose** [comment]
this is now done, the releases today were for 1.18.2
