### ISSUE TITLE
Nests Spawn Mobs In Mass - Ignoring pokemobsMakeNests = false and Other Configs and Reform Themselves Instantly

### ISSUE THREAD

**Issue by Vuulfrin** [Pokecube-Development/Pokecube-Issues-and-Wiki#939]
Issue Description:
A player encounters a nest and investigates. As a player reaches the nest, mobs and eggs begin to spawn without limit. Mobs begin spawning faster than players can kill them and eggs begin appearing rapidly. Breaking the nest causes it to reform instantly and spawn another wave of mobs on top of what was already present. This will continue until the difficulty is set to peaceful and a player in creative mode destroys the nest, or the server becomes overloaded with too many mobs and crashes due to lag.

This issue has been observed with both plusle and durant nests. (May or may not be relevant) 

What happens:
Nests spawn mobs and eggs endlessly in large amounts and instantly reform when destroyed by a player in survival mode. Nests appear to ignore all configs, including pokemobsMakeNests.

What you expected to happen:
I expected mobs to stop making nests after pokemobsMakeNests was set to false.
I expected nests to spawn mobs and eggs in amounts I config them to.
I expected nests to be destructible by players in survival.

Steps to reproduce:

1. Induce the nesting behavior
2. Attempt to kill mobs, only to have them replaced by more mobs and eggs
3. Attempt to break nest, only for it to reform and for more mobs and eggs to be spawned

____
Affected Versions

- Pokecube AIO: 3.16.1
- Minecraft: 1.18.1
- Forge: 39.1.0

As instructed by Thutmose, I am including the startup logs for client and server

[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9176857/latest.log) (SERVER)

[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9176860/latest.log) (CLIENT)

The following crash report was generated during the first encounter with the issue. 

[crash-2022-07-22_19.18.50-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9176873/crash-2022-07-22_19.18.50-server.txt)

The "Guard Villagers" mod was present in the modpack at the time, but has since been removed. This probably isn't relevant.

**Comment by Thutmose** [comment]
Hmm, seems there is something wrong with the ant nests, do you have any other crash reports for the issue, or similar ones?

**Comment by Vuulfrin** [comment]
> Hmm, seems there is something wrong with the ant nests, do you have any other crash reports for the issue, or similar ones?

Adding this log here, it starts around 19:00
[2022-07-22-5.log.gz](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9194874/2022-07-22-5.log.gz)
.
