### ISSUE TITLE
Client Fails to Launch - Second Pokecube Alpha

### ISSUE THREAD

**Issue by Vuulfrin** [Pokecube-Development/Pokecube-Issues-and-Wiki#952]
#### Issue Description:
The client reports that 8 mods, all of which are different aspects of pokecube-aoi, failed to load correctly. 

The list of mods is given as:
Pokecube Mobs
Thut Crafts
Thut Wearables
Pokecube Core
Pokecube Legends
Thut Core
Thut Bling
Pokecube Revival

The stated error is: java.lang.noclassdeffounderror:
#### What happens:
Minecraft loads, but gives errors on startup, indicating that Pokecube has not loaded correctly. The client generates a crash report and must be closed.

#### What you expected to happen:
I expected Minecraft Pokecube to launch normally.

#### Steps to reproduce:

1. Create an Instance of Minecraft Pokecube
2. Attempt to Launch Client
3.
...

Notes: Although the client now fails to launch, the server appears to launch normally.
____
#### Affected Versions 

- Pokecube AIO: pokecube-aio-1.18.2-3.17.0.1
- Minecraft: 1.18.2
- Forge: 40.1.51
- 
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9256901/latest.log)

[crash-2022-08-04_01.24.55-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9256908/crash-2022-08-04_01.24.55-fml.txt)

**Comment by Thutmose** [comment]
update forge

**Comment by Vuulfrin** [comment]
Issue resolved upon updating forge
