### ISSUE TITLE
Scyther is unable to evolve into Kleavor

### ISSUE THREAD

**Issue by DragonKing12415** [Pokecube-Development/Pokecube-Issues-and-Wiki#953]
Issue Description:Scyther simply has no way to evolve into kleavor, nothing shows up on JEI or the pokewatch stating a method for evolution
Note: this bug happens in the entirety of pokecube

What happens: JEI and the pokewatch show no way of evolving scyther into kleavor, thus there is no set way for this evolution to occur
What you expected to happen: JEI and pokewatch showing a method of evolving scyther into kleavor (originally by giving him netherite scraps) and scyther being able to evolve into kleavor
Steps to reproduce:
1 open JEI
2 try and check the way to evolve scyther into kleavor
3 try to evolve scyther into kleavor

Affected Versions
Pokecube AIO: 3.16.1
Minecraft: 1.18.1
Forge: 39.1.2

**Comment by Thutmose** [comment]
this seems to be fixed in 3.17
