### ISSUE TITLE
Compatibility Issue - Pokecube Server Fails to Launch

### ISSUE THREAD

**Issue by Vuulfrin** [Pokecube-Development/Pokecube-Issues-and-Wiki#956]
#### Issue Description:
The server fails to start and references Pokecube. The crash log references a "CustomShapeFoliagePlacer" in its error message.  

The server launched when ONLY Pokecube was removed.
The server launched when ONLY Pokecube was installed.

The server failed to launch with the full modpack installed.

#### What happens:
The server quickly fails to start and references Pokecube in its logs. 

#### What you expected to happen:
I expected the server to launch.

#### Steps to reproduce:

1. Launch the modpack referenced in the crash report
2. Observe crash
3.
...

____
#### Affected Versions 

- Pokecube AIO: 1.18.2-3.17.0.2
- Minecraft: 1.18.2
- Forge: 40.1.69
- Full mod and version list in crash log
[crash-2022-08-07_23.17.29-fml.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9278440/crash-2022-08-07_23.17.29-fml.txt)

**Comment by Thutmose** [comment]
same as the previous one... oops
