### ISSUE TITLE
Crash when reloading any Save a second time

### ISSUE THREAD

**Issue by JohnsBack** [Pokecube-Development/Pokecube-Issues-and-Wiki#962]
#### Issue Description:
Crash when save is loading after just playing other world. (When Minecraft launches and loads a save the first time everything is fine. However, this is not the case for loading a different save or the same one after launcher already did once. If this makes sense.) Can explain further in Discord if needed. PM me. Thank you!!

Example: Playing survival world, want to test something in creative mode. So exit and try to load test world but game crashes.

#### What happens:
Crash

#### What you expected to happen:
Save reloads

#### Steps to reproduce:
1.Create a Save/play one.
2.Close/save world
3.Reload Save 
4. Crash happens at some point during loading.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.
Added Pokecube AIO to TNP Limitless 5 Ver 1.17.1
- Pokecube AIO:3.17.0.3
- Minecraft: 1.18.2
- Forge: 40.1.68

[crash-2022-08-10_21.01.58-server.txt](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9312982/crash-2022-08-10_21.01.58-server.txt)
[latest.log](https://github.com/Pokecube-Development/Pokecube-Issues-and-Wiki/files/9312983/latest.log)

**Comment by Thutmose** [comment]
I think I have this fixed, but it would need to be tested with your pack, the next uploaded alpha or release should have the fix.

**Comment by Thutmose** [comment]
Note: the uploaded fix will also require updating forge to 40.1.73

patched alpha is at: https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi/files/3930476

**Comment by JohnsBack** [comment]
Thanks!
