### ISSUE TITLE
cannot revert Sogaleo or Lunala forms after using the n-solarizer/n-lunarizer

### ISSUE THREAD

**Issue by ItsEtc** [Pokecube-Development/Pokecube-Issues-and-Wiki#963]
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here.

Can't revert Sogaleo or Lunala forms after using the n-solarizer / n-lunarizer (once you turn it into sogaleo_dusk it wont turn back into Sogaleo the same goes with Lunala)

1.Give n-solarizer to sogaleo/n-lunarizer to lunala
2.Let it turn into the necrozma forms (dusk mane etc...)
3.Take n-solarizer / n-lunarizer out and it won't change forms
 
- Pokecube AIO:3.16.1
- Minecraft: 1.18.1
- Forge: 39.1.2
mods:clumps-forge, collective, crafting automata, easy villagers, fullbrightnesstoggle, infinitetrading, jei, journeyman, optifine, oreexcavation, pokecube aio, shulkerbox tooltips, shutupexperimentalsettings, speedyhoppers

**Comment by Thutmose** [comment]
Tested in the 3.17.0.4 alpha, and it seems to work fine. If you recall it while it is trying to revert however, it can cancel it. Try giving it the item back, and then taking it away and waiting to see if it reverts?
