### ISSUE TITLE
dusk mane sogaleo dossen't have a face

### ISSUE THREAD

**Issue by ItsEtc** [Pokecube-Development/Pokecube-Issues-and-Wiki#964]
Sogaleo when turned into dusk form does not have a face in front of the necrozma mask. This might be a texture issue

-Pokecube AIO:3.16.1
-Minecraft: 1.18.1
-Forge: 39.1.2
mods:clumps-forge, collective, crafting automata, easy villagers, fullbrightnesstoggle, infinitetrading, jei, journeyman, optifine, oreexcavation, pokecube aio, shulkerbox tooltips, shutupexperimentalsettings, speedyhoppers

**Comment by Thutmose** [comment]
![image](https://user-images.githubusercontent.com/2363472/184454882-8ee85988-0ec9-4aaa-868c-286c50a67cd3.png)
seems present at least in the 1.18.2 alphas
