### ISSUE TITLE
pokemobs hatched from eggs become tamed to the pokemob closest to it

### ISSUE THREAD

**Issue by monkeycrazie** [Pokecube-Development/Pokecube-Issues-and-Wiki#989]
#### Issue Description:
if two pokemobs breed and are stay near the egg when it hatches it will not hatch wild but be tamed to its parents or any pokemob closest to it.

#### What happens:
egg hatches tamed to closest pokemob when should be wild

#### What you expected to happen:
for all eggs to hatch and be wild when made in the wild and be able to be caught

#### Steps to reproduce:

1.get two pokemobs to breed
2.leave one of the parents near the egg
3.when it hatches it will be tamed to the parent instead of being wild
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Pokecube AIO: 3.17.2
- Minecraft: 1.18.2
- Forge: 40.1.73

**Comment by Thutmose** [comment]
this is how it works, unless the owner is actually the pokemob and not the pokemob's owner, re-open issue if that is the case.

**Comment by monkeycrazie** [comment]
Re open it

**Comment by Thutmose** [comment]
explain why?  I see no extended description, nor screenshots
