### ISSUE TITLE
Couple of questions, not issues.

### ISSUE THREAD

**Issue by HavelockVimes** [Pokecube-Development/Pokecube-Issues-and-Wiki#99]
Sorry if there's a FAQ somewhere that answers these, I've been googling for a while and didn't find anything. I am not even sure if the project is still active.

Is there a way to break down or move pokecenters? I placed one a square to the left from what I wanted and now it's destroying my mudhut's feng shui.

Also, I don't know if this is pokecube's mod in specific, but how does the keybind for the bag works? The message says alt + none, and I assume I need to set up a second button, but can't find the correct menu.

**Comment by Thutmose** [comment]
the keybinds should be in the wearables section of the keys, iirc it is the back slot for the bag.

For breaking blocks you placed, try left clicking them with a stick
